// Code generated by ent, DO NOT EDIT.

package invoiceapplication

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the invoiceapplication type in the database.
	Label = "invoice_application"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldInvoiceType holds the string denoting the invoice_type field in the database.
	FieldInvoiceType = "invoice_type"
	// FieldHeaderType holds the string denoting the header_type field in the database.
	FieldHeaderType = "header_type"
	// FieldHeaderTitle holds the string denoting the header_title field in the database.
	FieldHeaderTitle = "header_title"
	// FieldHeaderTaxNumber holds the string denoting the header_tax_number field in the database.
	FieldHeaderTaxNumber = "header_tax_number"
	// FieldHeaderEmail holds the string denoting the header_email field in the database.
	FieldHeaderEmail = "header_email"
	// FieldHeaderPhone holds the string denoting the header_phone field in the database.
	FieldHeaderPhone = "header_phone"
	// FieldHeaderAddress holds the string denoting the header_address field in the database.
	FieldHeaderAddress = "header_address"
	// FieldTotalAmount holds the string denoting the total_amount field in the database.
	FieldTotalAmount = "total_amount"
	// FieldHandledBy holds the string denoting the handled_by field in the database.
	FieldHandledBy = "handled_by"
	// FieldRejectionReason holds the string denoting the rejection_reason field in the database.
	FieldRejectionReason = "rejection_reason"
	// FieldAdminNote holds the string denoting the admin_note field in the database.
	FieldAdminNote = "admin_note"
	// FieldInvoiceNumber holds the string denoting the invoice_number field in the database.
	FieldInvoiceNumber = "invoice_number"
	// FieldProcessedAt holds the string denoting the processed_at field in the database.
	FieldProcessedAt = "processed_at"
	// FieldInvoicedAt holds the string denoting the invoiced_at field in the database.
	FieldInvoicedAt = "invoiced_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeOrders holds the string denoting the orders edge name in mutations.
	EdgeOrders = "orders"
	// Table holds the table name of the invoiceapplication in the database.
	Table = "invoice_applications"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "invoice_applications"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// OrdersTable is the table that holds the orders relation/edge.
	OrdersTable = "invoice_application_orders"
	// OrdersInverseTable is the table name for the InvoiceApplicationOrder entity.
	// It exists in this package in order to avoid circular dependency with the "invoiceapplicationorder" package.
	OrdersInverseTable = "invoice_application_orders"
	// OrdersColumn is the table column denoting the orders relation/edge.
	OrdersColumn = "application_id"
)

// Columns holds all SQL columns for invoiceapplication fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldStatus,
	FieldInvoiceType,
	FieldHeaderType,
	FieldHeaderTitle,
	FieldHeaderTaxNumber,
	FieldHeaderEmail,
	FieldHeaderPhone,
	FieldHeaderAddress,
	FieldTotalAmount,
	FieldHandledBy,
	FieldRejectionReason,
	FieldAdminNote,
	FieldInvoiceNumber,
	FieldProcessedAt,
	FieldInvoicedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultInvoiceType holds the default value on creation for the "invoice_type" field.
	DefaultInvoiceType string
	// InvoiceTypeValidator is a validator for the "invoice_type" field. It is called by the builders before save.
	InvoiceTypeValidator func(string) error
	// HeaderTypeValidator is a validator for the "header_type" field. It is called by the builders before save.
	HeaderTypeValidator func(string) error
	// HeaderTitleValidator is a validator for the "header_title" field. It is called by the builders before save.
	HeaderTitleValidator func(string) error
	// DefaultHeaderTaxNumber holds the default value on creation for the "header_tax_number" field.
	DefaultHeaderTaxNumber string
	// HeaderTaxNumberValidator is a validator for the "header_tax_number" field. It is called by the builders before save.
	HeaderTaxNumberValidator func(string) error
	// DefaultHeaderEmail holds the default value on creation for the "header_email" field.
	DefaultHeaderEmail string
	// HeaderEmailValidator is a validator for the "header_email" field. It is called by the builders before save.
	HeaderEmailValidator func(string) error
	// DefaultHeaderPhone holds the default value on creation for the "header_phone" field.
	DefaultHeaderPhone string
	// HeaderPhoneValidator is a validator for the "header_phone" field. It is called by the builders before save.
	HeaderPhoneValidator func(string) error
	// DefaultInvoiceNumber holds the default value on creation for the "invoice_number" field.
	DefaultInvoiceNumber string
	// InvoiceNumberValidator is a validator for the "invoice_number" field. It is called by the builders before save.
	InvoiceNumberValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the InvoiceApplication queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByInvoiceType orders the results by the invoice_type field.
func ByInvoiceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoiceType, opts...).ToFunc()
}

// ByHeaderType orders the results by the header_type field.
func ByHeaderType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeaderType, opts...).ToFunc()
}

// ByHeaderTitle orders the results by the header_title field.
func ByHeaderTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeaderTitle, opts...).ToFunc()
}

// ByHeaderTaxNumber orders the results by the header_tax_number field.
func ByHeaderTaxNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeaderTaxNumber, opts...).ToFunc()
}

// ByHeaderEmail orders the results by the header_email field.
func ByHeaderEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeaderEmail, opts...).ToFunc()
}

// ByHeaderPhone orders the results by the header_phone field.
func ByHeaderPhone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeaderPhone, opts...).ToFunc()
}

// ByHeaderAddress orders the results by the header_address field.
func ByHeaderAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeaderAddress, opts...).ToFunc()
}

// ByTotalAmount orders the results by the total_amount field.
func ByTotalAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalAmount, opts...).ToFunc()
}

// ByHandledBy orders the results by the handled_by field.
func ByHandledBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHandledBy, opts...).ToFunc()
}

// ByRejectionReason orders the results by the rejection_reason field.
func ByRejectionReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRejectionReason, opts...).ToFunc()
}

// ByAdminNote orders the results by the admin_note field.
func ByAdminNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdminNote, opts...).ToFunc()
}

// ByInvoiceNumber orders the results by the invoice_number field.
func ByInvoiceNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoiceNumber, opts...).ToFunc()
}

// ByProcessedAt orders the results by the processed_at field.
func ByProcessedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProcessedAt, opts...).ToFunc()
}

// ByInvoicedAt orders the results by the invoiced_at field.
func ByInvoicedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoicedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByOrdersCount orders the results by orders count.
func ByOrdersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOrdersStep(), opts...)
	}
}

// ByOrders orders the results by orders terms.
func ByOrders(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOrdersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newOrdersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OrdersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, OrdersTable, OrdersColumn),
	)
}
