// Code generated by ent, DO NOT EDIT.

package invoiceapplication

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldUserID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldStatus, v))
}

// InvoiceType applies equality check predicate on the "invoice_type" field. It's identical to InvoiceTypeEQ.
func InvoiceType(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldInvoiceType, v))
}

// HeaderType applies equality check predicate on the "header_type" field. It's identical to HeaderTypeEQ.
func HeaderType(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldHeaderType, v))
}

// HeaderTitle applies equality check predicate on the "header_title" field. It's identical to HeaderTitleEQ.
func HeaderTitle(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldHeaderTitle, v))
}

// HeaderTaxNumber applies equality check predicate on the "header_tax_number" field. It's identical to HeaderTaxNumberEQ.
func HeaderTaxNumber(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldHeaderTaxNumber, v))
}

// HeaderEmail applies equality check predicate on the "header_email" field. It's identical to HeaderEmailEQ.
func HeaderEmail(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldHeaderEmail, v))
}

// HeaderPhone applies equality check predicate on the "header_phone" field. It's identical to HeaderPhoneEQ.
func HeaderPhone(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldHeaderPhone, v))
}

// HeaderAddress applies equality check predicate on the "header_address" field. It's identical to HeaderAddressEQ.
func HeaderAddress(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldHeaderAddress, v))
}

// TotalAmount applies equality check predicate on the "total_amount" field. It's identical to TotalAmountEQ.
func TotalAmount(v float64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldTotalAmount, v))
}

// HandledBy applies equality check predicate on the "handled_by" field. It's identical to HandledByEQ.
func HandledBy(v int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldHandledBy, v))
}

// RejectionReason applies equality check predicate on the "rejection_reason" field. It's identical to RejectionReasonEQ.
func RejectionReason(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldRejectionReason, v))
}

// AdminNote applies equality check predicate on the "admin_note" field. It's identical to AdminNoteEQ.
func AdminNote(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldAdminNote, v))
}

// InvoiceNumber applies equality check predicate on the "invoice_number" field. It's identical to InvoiceNumberEQ.
func InvoiceNumber(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldInvoiceNumber, v))
}

// ProcessedAt applies equality check predicate on the "processed_at" field. It's identical to ProcessedAtEQ.
func ProcessedAt(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldProcessedAt, v))
}

// InvoicedAt applies equality check predicate on the "invoiced_at" field. It's identical to InvoicedAtEQ.
func InvoicedAt(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldInvoicedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldUserID, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldStatus, v))
}

// InvoiceTypeEQ applies the EQ predicate on the "invoice_type" field.
func InvoiceTypeEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldInvoiceType, v))
}

// InvoiceTypeNEQ applies the NEQ predicate on the "invoice_type" field.
func InvoiceTypeNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldInvoiceType, v))
}

// InvoiceTypeIn applies the In predicate on the "invoice_type" field.
func InvoiceTypeIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldInvoiceType, vs...))
}

// InvoiceTypeNotIn applies the NotIn predicate on the "invoice_type" field.
func InvoiceTypeNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldInvoiceType, vs...))
}

// InvoiceTypeGT applies the GT predicate on the "invoice_type" field.
func InvoiceTypeGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldInvoiceType, v))
}

// InvoiceTypeGTE applies the GTE predicate on the "invoice_type" field.
func InvoiceTypeGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldInvoiceType, v))
}

// InvoiceTypeLT applies the LT predicate on the "invoice_type" field.
func InvoiceTypeLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldInvoiceType, v))
}

// InvoiceTypeLTE applies the LTE predicate on the "invoice_type" field.
func InvoiceTypeLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldInvoiceType, v))
}

// InvoiceTypeContains applies the Contains predicate on the "invoice_type" field.
func InvoiceTypeContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldInvoiceType, v))
}

// InvoiceTypeHasPrefix applies the HasPrefix predicate on the "invoice_type" field.
func InvoiceTypeHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldInvoiceType, v))
}

// InvoiceTypeHasSuffix applies the HasSuffix predicate on the "invoice_type" field.
func InvoiceTypeHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldInvoiceType, v))
}

// InvoiceTypeEqualFold applies the EqualFold predicate on the "invoice_type" field.
func InvoiceTypeEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldInvoiceType, v))
}

// InvoiceTypeContainsFold applies the ContainsFold predicate on the "invoice_type" field.
func InvoiceTypeContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldInvoiceType, v))
}

// HeaderTypeEQ applies the EQ predicate on the "header_type" field.
func HeaderTypeEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldHeaderType, v))
}

// HeaderTypeNEQ applies the NEQ predicate on the "header_type" field.
func HeaderTypeNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldHeaderType, v))
}

// HeaderTypeIn applies the In predicate on the "header_type" field.
func HeaderTypeIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldHeaderType, vs...))
}

// HeaderTypeNotIn applies the NotIn predicate on the "header_type" field.
func HeaderTypeNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldHeaderType, vs...))
}

// HeaderTypeGT applies the GT predicate on the "header_type" field.
func HeaderTypeGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldHeaderType, v))
}

// HeaderTypeGTE applies the GTE predicate on the "header_type" field.
func HeaderTypeGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldHeaderType, v))
}

// HeaderTypeLT applies the LT predicate on the "header_type" field.
func HeaderTypeLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldHeaderType, v))
}

// HeaderTypeLTE applies the LTE predicate on the "header_type" field.
func HeaderTypeLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldHeaderType, v))
}

// HeaderTypeContains applies the Contains predicate on the "header_type" field.
func HeaderTypeContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldHeaderType, v))
}

// HeaderTypeHasPrefix applies the HasPrefix predicate on the "header_type" field.
func HeaderTypeHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldHeaderType, v))
}

// HeaderTypeHasSuffix applies the HasSuffix predicate on the "header_type" field.
func HeaderTypeHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldHeaderType, v))
}

// HeaderTypeEqualFold applies the EqualFold predicate on the "header_type" field.
func HeaderTypeEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldHeaderType, v))
}

// HeaderTypeContainsFold applies the ContainsFold predicate on the "header_type" field.
func HeaderTypeContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldHeaderType, v))
}

// HeaderTitleEQ applies the EQ predicate on the "header_title" field.
func HeaderTitleEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldHeaderTitle, v))
}

// HeaderTitleNEQ applies the NEQ predicate on the "header_title" field.
func HeaderTitleNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldHeaderTitle, v))
}

// HeaderTitleIn applies the In predicate on the "header_title" field.
func HeaderTitleIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldHeaderTitle, vs...))
}

// HeaderTitleNotIn applies the NotIn predicate on the "header_title" field.
func HeaderTitleNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldHeaderTitle, vs...))
}

// HeaderTitleGT applies the GT predicate on the "header_title" field.
func HeaderTitleGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldHeaderTitle, v))
}

// HeaderTitleGTE applies the GTE predicate on the "header_title" field.
func HeaderTitleGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldHeaderTitle, v))
}

// HeaderTitleLT applies the LT predicate on the "header_title" field.
func HeaderTitleLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldHeaderTitle, v))
}

// HeaderTitleLTE applies the LTE predicate on the "header_title" field.
func HeaderTitleLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldHeaderTitle, v))
}

// HeaderTitleContains applies the Contains predicate on the "header_title" field.
func HeaderTitleContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldHeaderTitle, v))
}

// HeaderTitleHasPrefix applies the HasPrefix predicate on the "header_title" field.
func HeaderTitleHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldHeaderTitle, v))
}

// HeaderTitleHasSuffix applies the HasSuffix predicate on the "header_title" field.
func HeaderTitleHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldHeaderTitle, v))
}

// HeaderTitleEqualFold applies the EqualFold predicate on the "header_title" field.
func HeaderTitleEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldHeaderTitle, v))
}

// HeaderTitleContainsFold applies the ContainsFold predicate on the "header_title" field.
func HeaderTitleContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldHeaderTitle, v))
}

// HeaderTaxNumberEQ applies the EQ predicate on the "header_tax_number" field.
func HeaderTaxNumberEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldHeaderTaxNumber, v))
}

// HeaderTaxNumberNEQ applies the NEQ predicate on the "header_tax_number" field.
func HeaderTaxNumberNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldHeaderTaxNumber, v))
}

// HeaderTaxNumberIn applies the In predicate on the "header_tax_number" field.
func HeaderTaxNumberIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldHeaderTaxNumber, vs...))
}

// HeaderTaxNumberNotIn applies the NotIn predicate on the "header_tax_number" field.
func HeaderTaxNumberNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldHeaderTaxNumber, vs...))
}

// HeaderTaxNumberGT applies the GT predicate on the "header_tax_number" field.
func HeaderTaxNumberGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldHeaderTaxNumber, v))
}

// HeaderTaxNumberGTE applies the GTE predicate on the "header_tax_number" field.
func HeaderTaxNumberGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldHeaderTaxNumber, v))
}

// HeaderTaxNumberLT applies the LT predicate on the "header_tax_number" field.
func HeaderTaxNumberLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldHeaderTaxNumber, v))
}

// HeaderTaxNumberLTE applies the LTE predicate on the "header_tax_number" field.
func HeaderTaxNumberLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldHeaderTaxNumber, v))
}

// HeaderTaxNumberContains applies the Contains predicate on the "header_tax_number" field.
func HeaderTaxNumberContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldHeaderTaxNumber, v))
}

// HeaderTaxNumberHasPrefix applies the HasPrefix predicate on the "header_tax_number" field.
func HeaderTaxNumberHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldHeaderTaxNumber, v))
}

// HeaderTaxNumberHasSuffix applies the HasSuffix predicate on the "header_tax_number" field.
func HeaderTaxNumberHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldHeaderTaxNumber, v))
}

// HeaderTaxNumberEqualFold applies the EqualFold predicate on the "header_tax_number" field.
func HeaderTaxNumberEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldHeaderTaxNumber, v))
}

// HeaderTaxNumberContainsFold applies the ContainsFold predicate on the "header_tax_number" field.
func HeaderTaxNumberContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldHeaderTaxNumber, v))
}

// HeaderEmailEQ applies the EQ predicate on the "header_email" field.
func HeaderEmailEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldHeaderEmail, v))
}

// HeaderEmailNEQ applies the NEQ predicate on the "header_email" field.
func HeaderEmailNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldHeaderEmail, v))
}

// HeaderEmailIn applies the In predicate on the "header_email" field.
func HeaderEmailIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldHeaderEmail, vs...))
}

// HeaderEmailNotIn applies the NotIn predicate on the "header_email" field.
func HeaderEmailNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldHeaderEmail, vs...))
}

// HeaderEmailGT applies the GT predicate on the "header_email" field.
func HeaderEmailGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldHeaderEmail, v))
}

// HeaderEmailGTE applies the GTE predicate on the "header_email" field.
func HeaderEmailGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldHeaderEmail, v))
}

// HeaderEmailLT applies the LT predicate on the "header_email" field.
func HeaderEmailLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldHeaderEmail, v))
}

// HeaderEmailLTE applies the LTE predicate on the "header_email" field.
func HeaderEmailLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldHeaderEmail, v))
}

// HeaderEmailContains applies the Contains predicate on the "header_email" field.
func HeaderEmailContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldHeaderEmail, v))
}

// HeaderEmailHasPrefix applies the HasPrefix predicate on the "header_email" field.
func HeaderEmailHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldHeaderEmail, v))
}

// HeaderEmailHasSuffix applies the HasSuffix predicate on the "header_email" field.
func HeaderEmailHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldHeaderEmail, v))
}

// HeaderEmailEqualFold applies the EqualFold predicate on the "header_email" field.
func HeaderEmailEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldHeaderEmail, v))
}

// HeaderEmailContainsFold applies the ContainsFold predicate on the "header_email" field.
func HeaderEmailContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldHeaderEmail, v))
}

// HeaderPhoneEQ applies the EQ predicate on the "header_phone" field.
func HeaderPhoneEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldHeaderPhone, v))
}

// HeaderPhoneNEQ applies the NEQ predicate on the "header_phone" field.
func HeaderPhoneNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldHeaderPhone, v))
}

// HeaderPhoneIn applies the In predicate on the "header_phone" field.
func HeaderPhoneIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldHeaderPhone, vs...))
}

// HeaderPhoneNotIn applies the NotIn predicate on the "header_phone" field.
func HeaderPhoneNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldHeaderPhone, vs...))
}

// HeaderPhoneGT applies the GT predicate on the "header_phone" field.
func HeaderPhoneGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldHeaderPhone, v))
}

// HeaderPhoneGTE applies the GTE predicate on the "header_phone" field.
func HeaderPhoneGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldHeaderPhone, v))
}

// HeaderPhoneLT applies the LT predicate on the "header_phone" field.
func HeaderPhoneLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldHeaderPhone, v))
}

// HeaderPhoneLTE applies the LTE predicate on the "header_phone" field.
func HeaderPhoneLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldHeaderPhone, v))
}

// HeaderPhoneContains applies the Contains predicate on the "header_phone" field.
func HeaderPhoneContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldHeaderPhone, v))
}

// HeaderPhoneHasPrefix applies the HasPrefix predicate on the "header_phone" field.
func HeaderPhoneHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldHeaderPhone, v))
}

// HeaderPhoneHasSuffix applies the HasSuffix predicate on the "header_phone" field.
func HeaderPhoneHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldHeaderPhone, v))
}

// HeaderPhoneEqualFold applies the EqualFold predicate on the "header_phone" field.
func HeaderPhoneEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldHeaderPhone, v))
}

// HeaderPhoneContainsFold applies the ContainsFold predicate on the "header_phone" field.
func HeaderPhoneContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldHeaderPhone, v))
}

// HeaderAddressEQ applies the EQ predicate on the "header_address" field.
func HeaderAddressEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldHeaderAddress, v))
}

// HeaderAddressNEQ applies the NEQ predicate on the "header_address" field.
func HeaderAddressNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldHeaderAddress, v))
}

// HeaderAddressIn applies the In predicate on the "header_address" field.
func HeaderAddressIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldHeaderAddress, vs...))
}

// HeaderAddressNotIn applies the NotIn predicate on the "header_address" field.
func HeaderAddressNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldHeaderAddress, vs...))
}

// HeaderAddressGT applies the GT predicate on the "header_address" field.
func HeaderAddressGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldHeaderAddress, v))
}

// HeaderAddressGTE applies the GTE predicate on the "header_address" field.
func HeaderAddressGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldHeaderAddress, v))
}

// HeaderAddressLT applies the LT predicate on the "header_address" field.
func HeaderAddressLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldHeaderAddress, v))
}

// HeaderAddressLTE applies the LTE predicate on the "header_address" field.
func HeaderAddressLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldHeaderAddress, v))
}

// HeaderAddressContains applies the Contains predicate on the "header_address" field.
func HeaderAddressContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldHeaderAddress, v))
}

// HeaderAddressHasPrefix applies the HasPrefix predicate on the "header_address" field.
func HeaderAddressHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldHeaderAddress, v))
}

// HeaderAddressHasSuffix applies the HasSuffix predicate on the "header_address" field.
func HeaderAddressHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldHeaderAddress, v))
}

// HeaderAddressIsNil applies the IsNil predicate on the "header_address" field.
func HeaderAddressIsNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIsNull(FieldHeaderAddress))
}

// HeaderAddressNotNil applies the NotNil predicate on the "header_address" field.
func HeaderAddressNotNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotNull(FieldHeaderAddress))
}

// HeaderAddressEqualFold applies the EqualFold predicate on the "header_address" field.
func HeaderAddressEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldHeaderAddress, v))
}

// HeaderAddressContainsFold applies the ContainsFold predicate on the "header_address" field.
func HeaderAddressContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldHeaderAddress, v))
}

// TotalAmountEQ applies the EQ predicate on the "total_amount" field.
func TotalAmountEQ(v float64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldTotalAmount, v))
}

// TotalAmountNEQ applies the NEQ predicate on the "total_amount" field.
func TotalAmountNEQ(v float64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldTotalAmount, v))
}

// TotalAmountIn applies the In predicate on the "total_amount" field.
func TotalAmountIn(vs ...float64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldTotalAmount, vs...))
}

// TotalAmountNotIn applies the NotIn predicate on the "total_amount" field.
func TotalAmountNotIn(vs ...float64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldTotalAmount, vs...))
}

// TotalAmountGT applies the GT predicate on the "total_amount" field.
func TotalAmountGT(v float64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldTotalAmount, v))
}

// TotalAmountGTE applies the GTE predicate on the "total_amount" field.
func TotalAmountGTE(v float64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldTotalAmount, v))
}

// TotalAmountLT applies the LT predicate on the "total_amount" field.
func TotalAmountLT(v float64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldTotalAmount, v))
}

// TotalAmountLTE applies the LTE predicate on the "total_amount" field.
func TotalAmountLTE(v float64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldTotalAmount, v))
}

// HandledByEQ applies the EQ predicate on the "handled_by" field.
func HandledByEQ(v int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldHandledBy, v))
}

// HandledByNEQ applies the NEQ predicate on the "handled_by" field.
func HandledByNEQ(v int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldHandledBy, v))
}

// HandledByIn applies the In predicate on the "handled_by" field.
func HandledByIn(vs ...int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldHandledBy, vs...))
}

// HandledByNotIn applies the NotIn predicate on the "handled_by" field.
func HandledByNotIn(vs ...int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldHandledBy, vs...))
}

// HandledByGT applies the GT predicate on the "handled_by" field.
func HandledByGT(v int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldHandledBy, v))
}

// HandledByGTE applies the GTE predicate on the "handled_by" field.
func HandledByGTE(v int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldHandledBy, v))
}

// HandledByLT applies the LT predicate on the "handled_by" field.
func HandledByLT(v int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldHandledBy, v))
}

// HandledByLTE applies the LTE predicate on the "handled_by" field.
func HandledByLTE(v int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldHandledBy, v))
}

// HandledByIsNil applies the IsNil predicate on the "handled_by" field.
func HandledByIsNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIsNull(FieldHandledBy))
}

// HandledByNotNil applies the NotNil predicate on the "handled_by" field.
func HandledByNotNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotNull(FieldHandledBy))
}

// RejectionReasonEQ applies the EQ predicate on the "rejection_reason" field.
func RejectionReasonEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldRejectionReason, v))
}

// RejectionReasonNEQ applies the NEQ predicate on the "rejection_reason" field.
func RejectionReasonNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldRejectionReason, v))
}

// RejectionReasonIn applies the In predicate on the "rejection_reason" field.
func RejectionReasonIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldRejectionReason, vs...))
}

// RejectionReasonNotIn applies the NotIn predicate on the "rejection_reason" field.
func RejectionReasonNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldRejectionReason, vs...))
}

// RejectionReasonGT applies the GT predicate on the "rejection_reason" field.
func RejectionReasonGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldRejectionReason, v))
}

// RejectionReasonGTE applies the GTE predicate on the "rejection_reason" field.
func RejectionReasonGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldRejectionReason, v))
}

// RejectionReasonLT applies the LT predicate on the "rejection_reason" field.
func RejectionReasonLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldRejectionReason, v))
}

// RejectionReasonLTE applies the LTE predicate on the "rejection_reason" field.
func RejectionReasonLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldRejectionReason, v))
}

// RejectionReasonContains applies the Contains predicate on the "rejection_reason" field.
func RejectionReasonContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldRejectionReason, v))
}

// RejectionReasonHasPrefix applies the HasPrefix predicate on the "rejection_reason" field.
func RejectionReasonHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldRejectionReason, v))
}

// RejectionReasonHasSuffix applies the HasSuffix predicate on the "rejection_reason" field.
func RejectionReasonHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldRejectionReason, v))
}

// RejectionReasonIsNil applies the IsNil predicate on the "rejection_reason" field.
func RejectionReasonIsNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIsNull(FieldRejectionReason))
}

// RejectionReasonNotNil applies the NotNil predicate on the "rejection_reason" field.
func RejectionReasonNotNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotNull(FieldRejectionReason))
}

// RejectionReasonEqualFold applies the EqualFold predicate on the "rejection_reason" field.
func RejectionReasonEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldRejectionReason, v))
}

// RejectionReasonContainsFold applies the ContainsFold predicate on the "rejection_reason" field.
func RejectionReasonContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldRejectionReason, v))
}

// AdminNoteEQ applies the EQ predicate on the "admin_note" field.
func AdminNoteEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldAdminNote, v))
}

// AdminNoteNEQ applies the NEQ predicate on the "admin_note" field.
func AdminNoteNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldAdminNote, v))
}

// AdminNoteIn applies the In predicate on the "admin_note" field.
func AdminNoteIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldAdminNote, vs...))
}

// AdminNoteNotIn applies the NotIn predicate on the "admin_note" field.
func AdminNoteNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldAdminNote, vs...))
}

// AdminNoteGT applies the GT predicate on the "admin_note" field.
func AdminNoteGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldAdminNote, v))
}

// AdminNoteGTE applies the GTE predicate on the "admin_note" field.
func AdminNoteGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldAdminNote, v))
}

// AdminNoteLT applies the LT predicate on the "admin_note" field.
func AdminNoteLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldAdminNote, v))
}

// AdminNoteLTE applies the LTE predicate on the "admin_note" field.
func AdminNoteLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldAdminNote, v))
}

// AdminNoteContains applies the Contains predicate on the "admin_note" field.
func AdminNoteContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldAdminNote, v))
}

// AdminNoteHasPrefix applies the HasPrefix predicate on the "admin_note" field.
func AdminNoteHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldAdminNote, v))
}

// AdminNoteHasSuffix applies the HasSuffix predicate on the "admin_note" field.
func AdminNoteHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldAdminNote, v))
}

// AdminNoteIsNil applies the IsNil predicate on the "admin_note" field.
func AdminNoteIsNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIsNull(FieldAdminNote))
}

// AdminNoteNotNil applies the NotNil predicate on the "admin_note" field.
func AdminNoteNotNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotNull(FieldAdminNote))
}

// AdminNoteEqualFold applies the EqualFold predicate on the "admin_note" field.
func AdminNoteEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldAdminNote, v))
}

// AdminNoteContainsFold applies the ContainsFold predicate on the "admin_note" field.
func AdminNoteContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldAdminNote, v))
}

// InvoiceNumberEQ applies the EQ predicate on the "invoice_number" field.
func InvoiceNumberEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldInvoiceNumber, v))
}

// InvoiceNumberNEQ applies the NEQ predicate on the "invoice_number" field.
func InvoiceNumberNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldInvoiceNumber, v))
}

// InvoiceNumberIn applies the In predicate on the "invoice_number" field.
func InvoiceNumberIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldInvoiceNumber, vs...))
}

// InvoiceNumberNotIn applies the NotIn predicate on the "invoice_number" field.
func InvoiceNumberNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldInvoiceNumber, vs...))
}

// InvoiceNumberGT applies the GT predicate on the "invoice_number" field.
func InvoiceNumberGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldInvoiceNumber, v))
}

// InvoiceNumberGTE applies the GTE predicate on the "invoice_number" field.
func InvoiceNumberGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldInvoiceNumber, v))
}

// InvoiceNumberLT applies the LT predicate on the "invoice_number" field.
func InvoiceNumberLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldInvoiceNumber, v))
}

// InvoiceNumberLTE applies the LTE predicate on the "invoice_number" field.
func InvoiceNumberLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldInvoiceNumber, v))
}

// InvoiceNumberContains applies the Contains predicate on the "invoice_number" field.
func InvoiceNumberContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldInvoiceNumber, v))
}

// InvoiceNumberHasPrefix applies the HasPrefix predicate on the "invoice_number" field.
func InvoiceNumberHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldInvoiceNumber, v))
}

// InvoiceNumberHasSuffix applies the HasSuffix predicate on the "invoice_number" field.
func InvoiceNumberHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldInvoiceNumber, v))
}

// InvoiceNumberEqualFold applies the EqualFold predicate on the "invoice_number" field.
func InvoiceNumberEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldInvoiceNumber, v))
}

// InvoiceNumberContainsFold applies the ContainsFold predicate on the "invoice_number" field.
func InvoiceNumberContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldInvoiceNumber, v))
}

// ProcessedAtEQ applies the EQ predicate on the "processed_at" field.
func ProcessedAtEQ(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldProcessedAt, v))
}

// ProcessedAtNEQ applies the NEQ predicate on the "processed_at" field.
func ProcessedAtNEQ(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldProcessedAt, v))
}

// ProcessedAtIn applies the In predicate on the "processed_at" field.
func ProcessedAtIn(vs ...time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldProcessedAt, vs...))
}

// ProcessedAtNotIn applies the NotIn predicate on the "processed_at" field.
func ProcessedAtNotIn(vs ...time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldProcessedAt, vs...))
}

// ProcessedAtGT applies the GT predicate on the "processed_at" field.
func ProcessedAtGT(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldProcessedAt, v))
}

// ProcessedAtGTE applies the GTE predicate on the "processed_at" field.
func ProcessedAtGTE(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldProcessedAt, v))
}

// ProcessedAtLT applies the LT predicate on the "processed_at" field.
func ProcessedAtLT(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldProcessedAt, v))
}

// ProcessedAtLTE applies the LTE predicate on the "processed_at" field.
func ProcessedAtLTE(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldProcessedAt, v))
}

// ProcessedAtIsNil applies the IsNil predicate on the "processed_at" field.
func ProcessedAtIsNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIsNull(FieldProcessedAt))
}

// ProcessedAtNotNil applies the NotNil predicate on the "processed_at" field.
func ProcessedAtNotNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotNull(FieldProcessedAt))
}

// InvoicedAtEQ applies the EQ predicate on the "invoiced_at" field.
func InvoicedAtEQ(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldInvoicedAt, v))
}

// InvoicedAtNEQ applies the NEQ predicate on the "invoiced_at" field.
func InvoicedAtNEQ(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldInvoicedAt, v))
}

// InvoicedAtIn applies the In predicate on the "invoiced_at" field.
func InvoicedAtIn(vs ...time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldInvoicedAt, vs...))
}

// InvoicedAtNotIn applies the NotIn predicate on the "invoiced_at" field.
func InvoicedAtNotIn(vs ...time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldInvoicedAt, vs...))
}

// InvoicedAtGT applies the GT predicate on the "invoiced_at" field.
func InvoicedAtGT(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldInvoicedAt, v))
}

// InvoicedAtGTE applies the GTE predicate on the "invoiced_at" field.
func InvoicedAtGTE(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldInvoicedAt, v))
}

// InvoicedAtLT applies the LT predicate on the "invoiced_at" field.
func InvoicedAtLT(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldInvoicedAt, v))
}

// InvoicedAtLTE applies the LTE predicate on the "invoiced_at" field.
func InvoicedAtLTE(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldInvoicedAt, v))
}

// InvoicedAtIsNil applies the IsNil predicate on the "invoiced_at" field.
func InvoicedAtIsNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIsNull(FieldInvoicedAt))
}

// InvoicedAtNotNil applies the NotNil predicate on the "invoiced_at" field.
func InvoicedAtNotNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotNull(FieldInvoicedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOrders applies the HasEdge predicate on the "orders" edge.
func HasOrders() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, OrdersTable, OrdersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrdersWith applies the HasEdge predicate on the "orders" edge with a given conditions (other predicates).
func HasOrdersWith(preds ...predicate.InvoiceApplicationOrder) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(func(s *sql.Selector) {
		step := newOrdersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InvoiceApplication) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InvoiceApplication) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InvoiceApplication) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.NotPredicates(p))
}
