// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/coupon"
	"github.com/Wei-Shaw/sub2api/ent/couponusage"
)

// CouponCreate is the builder for creating a Coupon entity.
type CouponCreate struct {
	config
	mutation *CouponMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCode sets the "code" field.
func (_c *CouponCreate) SetCode(v string) *CouponCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetType sets the "type" field.
func (_c *CouponCreate) SetType(v string) *CouponCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *CouponCreate) SetValue(v float64) *CouponCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetMinAmount sets the "min_amount" field.
func (_c *CouponCreate) SetMinAmount(v float64) *CouponCreate {
	_c.mutation.SetMinAmount(v)
	return _c
}

// SetNillableMinAmount sets the "min_amount" field if the given value is not nil.
func (_c *CouponCreate) SetNillableMinAmount(v *float64) *CouponCreate {
	if v != nil {
		_c.SetMinAmount(*v)
	}
	return _c
}

// SetMaxDiscount sets the "max_discount" field.
func (_c *CouponCreate) SetMaxDiscount(v float64) *CouponCreate {
	_c.mutation.SetMaxDiscount(v)
	return _c
}

// SetNillableMaxDiscount sets the "max_discount" field if the given value is not nil.
func (_c *CouponCreate) SetNillableMaxDiscount(v *float64) *CouponCreate {
	if v != nil {
		_c.SetMaxDiscount(*v)
	}
	return _c
}

// SetScope sets the "scope" field.
func (_c *CouponCreate) SetScope(v string) *CouponCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_c *CouponCreate) SetNillableScope(v *string) *CouponCreate {
	if v != nil {
		_c.SetScope(*v)
	}
	return _c
}

// SetMaxUses sets the "max_uses" field.
func (_c *CouponCreate) SetMaxUses(v int) *CouponCreate {
	_c.mutation.SetMaxUses(v)
	return _c
}

// SetNillableMaxUses sets the "max_uses" field if the given value is not nil.
func (_c *CouponCreate) SetNillableMaxUses(v *int) *CouponCreate {
	if v != nil {
		_c.SetMaxUses(*v)
	}
	return _c
}

// SetUsedCount sets the "used_count" field.
func (_c *CouponCreate) SetUsedCount(v int) *CouponCreate {
	_c.mutation.SetUsedCount(v)
	return _c
}

// SetNillableUsedCount sets the "used_count" field if the given value is not nil.
func (_c *CouponCreate) SetNillableUsedCount(v *int) *CouponCreate {
	if v != nil {
		_c.SetUsedCount(*v)
	}
	return _c
}

// SetPerUserLimit sets the "per_user_limit" field.
func (_c *CouponCreate) SetPerUserLimit(v int) *CouponCreate {
	_c.mutation.SetPerUserLimit(v)
	return _c
}

// SetNillablePerUserLimit sets the "per_user_limit" field if the given value is not nil.
func (_c *CouponCreate) SetNillablePerUserLimit(v *int) *CouponCreate {
	if v != nil {
		_c.SetPerUserLimit(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *CouponCreate) SetStatus(v string) *CouponCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *CouponCreate) SetNillableStatus(v *string) *CouponCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetStartsAt sets the "starts_at" field.
func (_c *CouponCreate) SetStartsAt(v time.Time) *CouponCreate {
	_c.mutation.SetStartsAt(v)
	return _c
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_c *CouponCreate) SetNillableStartsAt(v *time.Time) *CouponCreate {
	if v != nil {
		_c.SetStartsAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *CouponCreate) SetExpiresAt(v time.Time) *CouponCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *CouponCreate) SetNillableExpiresAt(v *time.Time) *CouponCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *CouponCreate) SetNotes(v string) *CouponCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *CouponCreate) SetNillableNotes(v *string) *CouponCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CouponCreate) SetCreatedAt(v time.Time) *CouponCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CouponCreate) SetNillableCreatedAt(v *time.Time) *CouponCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CouponCreate) SetUpdatedAt(v time.Time) *CouponCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CouponCreate) SetNillableUpdatedAt(v *time.Time) *CouponCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddUsageRecordIDs adds the "usage_records" edge to the CouponUsage entity by IDs.
func (_c *CouponCreate) AddUsageRecordIDs(ids ...int64) *CouponCreate {
	_c.mutation.AddUsageRecordIDs(ids...)
	return _c
}

// AddUsageRecords adds the "usage_records" edges to the CouponUsage entity.
func (_c *CouponCreate) AddUsageRecords(v ...*CouponUsage) *CouponCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUsageRecordIDs(ids...)
}

// Mutation returns the CouponMutation object of the builder.
func (_c *CouponCreate) Mutation() *CouponMutation {
	return _c.mutation
}

// Save creates the Coupon in the database.
func (_c *CouponCreate) Save(ctx context.Context) (*Coupon, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CouponCreate) SaveX(ctx context.Context) *Coupon {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CouponCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CouponCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CouponCreate) defaults() {
	if _, ok := _c.mutation.MinAmount(); !ok {
		v := coupon.DefaultMinAmount
		_c.mutation.SetMinAmount(v)
	}
	if _, ok := _c.mutation.MaxDiscount(); !ok {
		v := coupon.DefaultMaxDiscount
		_c.mutation.SetMaxDiscount(v)
	}
	if _, ok := _c.mutation.Scope(); !ok {
		v := coupon.DefaultScope
		_c.mutation.SetScope(v)
	}
	if _, ok := _c.mutation.MaxUses(); !ok {
		v := coupon.DefaultMaxUses
		_c.mutation.SetMaxUses(v)
	}
	if _, ok := _c.mutation.UsedCount(); !ok {
		v := coupon.DefaultUsedCount
		_c.mutation.SetUsedCount(v)
	}
	if _, ok := _c.mutation.PerUserLimit(); !ok {
		v := coupon.DefaultPerUserLimit
		_c.mutation.SetPerUserLimit(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := coupon.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := coupon.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := coupon.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CouponCreate) check() error {
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Coupon.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := coupon.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Coupon.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Coupon.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := coupon.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Coupon.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "Coupon.value"`)}
	}
	if _, ok := _c.mutation.MinAmount(); !ok {
		return &ValidationError{Name: "min_amount", err: errors.New(`ent: missing required field "Coupon.min_amount"`)}
	}
	if _, ok := _c.mutation.MaxDiscount(); !ok {
		return &ValidationError{Name: "max_discount", err: errors.New(`ent: missing required field "Coupon.max_discount"`)}
	}
	if _, ok := _c.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "Coupon.scope"`)}
	}
	if v, ok := _c.mutation.Scope(); ok {
		if err := coupon.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "Coupon.scope": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MaxUses(); !ok {
		return &ValidationError{Name: "max_uses", err: errors.New(`ent: missing required field "Coupon.max_uses"`)}
	}
	if _, ok := _c.mutation.UsedCount(); !ok {
		return &ValidationError{Name: "used_count", err: errors.New(`ent: missing required field "Coupon.used_count"`)}
	}
	if _, ok := _c.mutation.PerUserLimit(); !ok {
		return &ValidationError{Name: "per_user_limit", err: errors.New(`ent: missing required field "Coupon.per_user_limit"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Coupon.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := coupon.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Coupon.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Coupon.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Coupon.updated_at"`)}
	}
	return nil
}

func (_c *CouponCreate) sqlSave(ctx context.Context) (*Coupon, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CouponCreate) createSpec() (*Coupon, *sqlgraph.CreateSpec) {
	var (
		_node = &Coupon{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(coupon.Table, sqlgraph.NewFieldSpec(coupon.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(coupon.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(coupon.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(coupon.FieldValue, field.TypeFloat64, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.MinAmount(); ok {
		_spec.SetField(coupon.FieldMinAmount, field.TypeFloat64, value)
		_node.MinAmount = value
	}
	if value, ok := _c.mutation.MaxDiscount(); ok {
		_spec.SetField(coupon.FieldMaxDiscount, field.TypeFloat64, value)
		_node.MaxDiscount = value
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(coupon.FieldScope, field.TypeString, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.MaxUses(); ok {
		_spec.SetField(coupon.FieldMaxUses, field.TypeInt, value)
		_node.MaxUses = value
	}
	if value, ok := _c.mutation.UsedCount(); ok {
		_spec.SetField(coupon.FieldUsedCount, field.TypeInt, value)
		_node.UsedCount = value
	}
	if value, ok := _c.mutation.PerUserLimit(); ok {
		_spec.SetField(coupon.FieldPerUserLimit, field.TypeInt, value)
		_node.PerUserLimit = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(coupon.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.StartsAt(); ok {
		_spec.SetField(coupon.FieldStartsAt, field.TypeTime, value)
		_node.StartsAt = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(coupon.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(coupon.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(coupon.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(coupon.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UsageRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   coupon.UsageRecordsTable,
			Columns: []string{coupon.UsageRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(couponusage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Coupon.Create().
//		SetCode(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CouponUpsert) {
//			SetCode(v+v).
//		}).
//		Exec(ctx)
func (_c *CouponCreate) OnConflict(opts ...sql.ConflictOption) *CouponUpsertOne {
	_c.conflict = opts
	return &CouponUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Coupon.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CouponCreate) OnConflictColumns(columns ...string) *CouponUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CouponUpsertOne{
		create: _c,
	}
}

type (
	// CouponUpsertOne is the builder for "upsert"-ing
	//  one Coupon node.
	CouponUpsertOne struct {
		create *CouponCreate
	}

	// CouponUpsert is the "OnConflict" setter.
	CouponUpsert struct {
		*sql.UpdateSet
	}
)

// SetCode sets the "code" field.
func (u *CouponUpsert) SetCode(v string) *CouponUpsert {
	u.Set(coupon.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *CouponUpsert) UpdateCode() *CouponUpsert {
	u.SetExcluded(coupon.FieldCode)
	return u
}

// SetType sets the "type" field.
func (u *CouponUpsert) SetType(v string) *CouponUpsert {
	u.Set(coupon.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *CouponUpsert) UpdateType() *CouponUpsert {
	u.SetExcluded(coupon.FieldType)
	return u
}

// SetValue sets the "value" field.
func (u *CouponUpsert) SetValue(v float64) *CouponUpsert {
	u.Set(coupon.FieldValue, v)
	return u
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *CouponUpsert) UpdateValue() *CouponUpsert {
	u.SetExcluded(coupon.FieldValue)
	return u
}

// AddValue adds v to the "value" field.
func (u *CouponUpsert) AddValue(v float64) *CouponUpsert {
	u.Add(coupon.FieldValue, v)
	return u
}

// SetMinAmount sets the "min_amount" field.
func (u *CouponUpsert) SetMinAmount(v float64) *CouponUpsert {
	u.Set(coupon.FieldMinAmount, v)
	return u
}

// UpdateMinAmount sets the "min_amount" field to the value that was provided on create.
func (u *CouponUpsert) UpdateMinAmount() *CouponUpsert {
	u.SetExcluded(coupon.FieldMinAmount)
	return u
}

// AddMinAmount adds v to the "min_amount" field.
func (u *CouponUpsert) AddMinAmount(v float64) *CouponUpsert {
	u.Add(coupon.FieldMinAmount, v)
	return u
}

// SetMaxDiscount sets the "max_discount" field.
func (u *CouponUpsert) SetMaxDiscount(v float64) *CouponUpsert {
	u.Set(coupon.FieldMaxDiscount, v)
	return u
}

// UpdateMaxDiscount sets the "max_discount" field to the value that was provided on create.
func (u *CouponUpsert) UpdateMaxDiscount() *CouponUpsert {
	u.SetExcluded(coupon.FieldMaxDiscount)
	return u
}

// AddMaxDiscount adds v to the "max_discount" field.
func (u *CouponUpsert) AddMaxDiscount(v float64) *CouponUpsert {
	u.Add(coupon.FieldMaxDiscount, v)
	return u
}

// SetScope sets the "scope" field.
func (u *CouponUpsert) SetScope(v string) *CouponUpsert {
	u.Set(coupon.FieldScope, v)
	return u
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *CouponUpsert) UpdateScope() *CouponUpsert {
	u.SetExcluded(coupon.FieldScope)
	return u
}

// SetMaxUses sets the "max_uses" field.
func (u *CouponUpsert) SetMaxUses(v int) *CouponUpsert {
	u.Set(coupon.FieldMaxUses, v)
	return u
}

// UpdateMaxUses sets the "max_uses" field to the value that was provided on create.
func (u *CouponUpsert) UpdateMaxUses() *CouponUpsert {
	u.SetExcluded(coupon.FieldMaxUses)
	return u
}

// AddMaxUses adds v to the "max_uses" field.
func (u *CouponUpsert) AddMaxUses(v int) *CouponUpsert {
	u.Add(coupon.FieldMaxUses, v)
	return u
}

// SetUsedCount sets the "used_count" field.
func (u *CouponUpsert) SetUsedCount(v int) *CouponUpsert {
	u.Set(coupon.FieldUsedCount, v)
	return u
}

// UpdateUsedCount sets the "used_count" field to the value that was provided on create.
func (u *CouponUpsert) UpdateUsedCount() *CouponUpsert {
	u.SetExcluded(coupon.FieldUsedCount)
	return u
}

// AddUsedCount adds v to the "used_count" field.
func (u *CouponUpsert) AddUsedCount(v int) *CouponUpsert {
	u.Add(coupon.FieldUsedCount, v)
	return u
}

// SetPerUserLimit sets the "per_user_limit" field.
func (u *CouponUpsert) SetPerUserLimit(v int) *CouponUpsert {
	u.Set(coupon.FieldPerUserLimit, v)
	return u
}

// UpdatePerUserLimit sets the "per_user_limit" field to the value that was provided on create.
func (u *CouponUpsert) UpdatePerUserLimit() *CouponUpsert {
	u.SetExcluded(coupon.FieldPerUserLimit)
	return u
}

// AddPerUserLimit adds v to the "per_user_limit" field.
func (u *CouponUpsert) AddPerUserLimit(v int) *CouponUpsert {
	u.Add(coupon.FieldPerUserLimit, v)
	return u
}

// SetStatus sets the "status" field.
func (u *CouponUpsert) SetStatus(v string) *CouponUpsert {
	u.Set(coupon.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CouponUpsert) UpdateStatus() *CouponUpsert {
	u.SetExcluded(coupon.FieldStatus)
	return u
}

// SetStartsAt sets the "starts_at" field.
func (u *CouponUpsert) SetStartsAt(v time.Time) *CouponUpsert {
	u.Set(coupon.FieldStartsAt, v)
	return u
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *CouponUpsert) UpdateStartsAt() *CouponUpsert {
	u.SetExcluded(coupon.FieldStartsAt)
	return u
}

// ClearStartsAt clears the value of the "starts_at" field.
func (u *CouponUpsert) ClearStartsAt() *CouponUpsert {
	u.SetNull(coupon.FieldStartsAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *CouponUpsert) SetExpiresAt(v time.Time) *CouponUpsert {
	u.Set(coupon.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *CouponUpsert) UpdateExpiresAt() *CouponUpsert {
	u.SetExcluded(coupon.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *CouponUpsert) ClearExpiresAt() *CouponUpsert {
	u.SetNull(coupon.FieldExpiresAt)
	return u
}

// SetNotes sets the "notes" field.
func (u *CouponUpsert) SetNotes(v string) *CouponUpsert {
	u.Set(coupon.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *CouponUpsert) UpdateNotes() *CouponUpsert {
	u.SetExcluded(coupon.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *CouponUpsert) ClearNotes() *CouponUpsert {
	u.SetNull(coupon.FieldNotes)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CouponUpsert) SetUpdatedAt(v time.Time) *CouponUpsert {
	u.Set(coupon.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CouponUpsert) UpdateUpdatedAt() *CouponUpsert {
	u.SetExcluded(coupon.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Coupon.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CouponUpsertOne) UpdateNewValues() *CouponUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(coupon.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Coupon.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CouponUpsertOne) Ignore() *CouponUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CouponUpsertOne) DoNothing() *CouponUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CouponCreate.OnConflict
// documentation for more info.
func (u *CouponUpsertOne) Update(set func(*CouponUpsert)) *CouponUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CouponUpsert{UpdateSet: update})
	}))
	return u
}

// SetCode sets the "code" field.
func (u *CouponUpsertOne) SetCode(v string) *CouponUpsertOne {
	return u.Update(func(s *CouponUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *CouponUpsertOne) UpdateCode() *CouponUpsertOne {
	return u.Update(func(s *CouponUpsert) {
		s.UpdateCode()
	})
}

// SetType sets the "type" field.
func (u *CouponUpsertOne) SetType(v string) *CouponUpsertOne {
	return u.Update(func(s *CouponUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *CouponUpsertOne) UpdateType() *CouponUpsertOne {
	return u.Update(func(s *CouponUpsert) {
		s.UpdateType()
	})
}

// SetValue sets the "value" field.
func (u *CouponUpsertOne) SetValue(v float64) *CouponUpsertOne {
	return u.Update(func(s *CouponUpsert) {
		s.SetValue(v)
	})
}

// AddValue adds v to the "value" field.
func (u *CouponUpsertOne) AddValue(v float64) *CouponUpsertOne {
	return u.Update(func(s *CouponUpsert) {
		s.AddValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *CouponUpsertOne) UpdateValue() *CouponUpsertOne {
	return u.Update(func(s *CouponUpsert) {
		s.UpdateValue()
	})
}

// SetMinAmount sets the "min_amount" field.
func (u *CouponUpsertOne) SetMinAmount(v float64) *CouponUpsertOne {
	return u.Update(func(s *CouponUpsert) {
		s.SetMinAmount(v)
	})
}

// AddMinAmount adds v to the "min_amount" field.
func (u *CouponUpsertOne) AddMinAmount(v float64) *CouponUpsertOne {
	return u.Update(func(s *CouponUpsert) {
		s.AddMinAmount(v)
	})
}

// UpdateMinAmount sets the "min_amount" field to the value that was provided on create.
func (u *CouponUpsertOne) UpdateMinAmount() *CouponUpsertOne {
	return u.Update(func(s *CouponUpsert) {
		s.UpdateMinAmount()
	})
}

// SetMaxDiscount sets the "max_discount" field.
func (u *CouponUpsertOne) SetMaxDiscount(v float64) *CouponUpsertOne {
	return u.Update(func(s *CouponUpsert) {
		s.SetMaxDiscount(v)
	})
}

// AddMaxDiscount adds v to the "max_discount" field.
func (u *CouponUpsertOne) AddMaxDiscount(v float64) *CouponUpsertOne {
	return u.Update(func(s *CouponUpsert) {
		s.AddMaxDiscount(v)
	})
}

// UpdateMaxDiscount sets the "max_discount" field to the value that was provided on create.
func (u *CouponUpsertOne) UpdateMaxDiscount() *CouponUpsertOne {
	return u.Update(func(s *CouponUpsert) {
		s.UpdateMaxDiscount()
	})
}

// SetScope sets the "scope" field.
func (u *CouponUpsertOne) SetScope(v string) *CouponUpsertOne {
	return u.Update(func(s *CouponUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *CouponUpsertOne) UpdateScope() *CouponUpsertOne {
	return u.Update(func(s *CouponUpsert) {
		s.UpdateScope()
	})
}

// SetMaxUses sets the "max_uses" field.
func (u *CouponUpsertOne) SetMaxUses(v int) *CouponUpsertOne {
	return u.Update(func(s *CouponUpsert) {
		s.SetMaxUses(v)
	})
}

// AddMaxUses adds v to the "max_uses" field.
func (u *CouponUpsertOne) AddMaxUses(v int) *CouponUpsertOne {
	return u.Update(func(s *CouponUpsert) {
		s.AddMaxUses(v)
	})
}

// UpdateMaxUses sets the "max_uses" field to the value that was provided on create.
func (u *CouponUpsertOne) UpdateMaxUses() *CouponUpsertOne {
	return u.Update(func(s *CouponUpsert) {
		s.UpdateMaxUses()
	})
}

// SetUsedCount sets the "used_count" field.
func (u *CouponUpsertOne) SetUsedCount(v int) *CouponUpsertOne {
	return u.Update(func(s *CouponUpsert) {
		s.SetUsedCount(v)
	})
}

// AddUsedCount adds v to the "used_count" field.
func (u *CouponUpsertOne) AddUsedCount(v int) *CouponUpsertOne {
	return u.Update(func(s *CouponUpsert) {
		s.AddUsedCount(v)
	})
}

// UpdateUsedCount sets the "used_count" field to the value that was provided on create.
func (u *CouponUpsertOne) UpdateUsedCount() *CouponUpsertOne {
	return u.Update(func(s *CouponUpsert) {
		s.UpdateUsedCount()
	})
}

// SetPerUserLimit sets the "per_user_limit" field.
func (u *CouponUpsertOne) SetPerUserLimit(v int) *CouponUpsertOne {
	return u.Update(func(s *CouponUpsert) {
		s.SetPerUserLimit(v)
	})
}

// AddPerUserLimit adds v to the "per_user_limit" field.
func (u *CouponUpsertOne) AddPerUserLimit(v int) *CouponUpsertOne {
	return u.Update(func(s *CouponUpsert) {
		s.AddPerUserLimit(v)
	})
}

// UpdatePerUserLimit sets the "per_user_limit" field to the value that was provided on create.
func (u *CouponUpsertOne) UpdatePerUserLimit() *CouponUpsertOne {
	return u.Update(func(s *CouponUpsert) {
		s.UpdatePerUserLimit()
	})
}

// SetStatus sets the "status" field.
func (u *CouponUpsertOne) SetStatus(v string) *CouponUpsertOne {
	return u.Update(func(s *CouponUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CouponUpsertOne) UpdateStatus() *CouponUpsertOne {
	return u.Update(func(s *CouponUpsert) {
		s.UpdateStatus()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *CouponUpsertOne) SetStartsAt(v time.Time) *CouponUpsertOne {
	return u.Update(func(s *CouponUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *CouponUpsertOne) UpdateStartsAt() *CouponUpsertOne {
	return u.Update(func(s *CouponUpsert) {
		s.UpdateStartsAt()
	})
}

// ClearStartsAt clears the value of the "starts_at" field.
func (u *CouponUpsertOne) ClearStartsAt() *CouponUpsertOne {
	return u.Update(func(s *CouponUpsert) {
		s.ClearStartsAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *CouponUpsertOne) SetExpiresAt(v time.Time) *CouponUpsertOne {
	return u.Update(func(s *CouponUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *CouponUpsertOne) UpdateExpiresAt() *CouponUpsertOne {
	return u.Update(func(s *CouponUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *CouponUpsertOne) ClearExpiresAt() *CouponUpsertOne {
	return u.Update(func(s *CouponUpsert) {
		s.ClearExpiresAt()
	})
}

// SetNotes sets the "notes" field.
func (u *CouponUpsertOne) SetNotes(v string) *CouponUpsertOne {
	return u.Update(func(s *CouponUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *CouponUpsertOne) UpdateNotes() *CouponUpsertOne {
	return u.Update(func(s *CouponUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *CouponUpsertOne) ClearNotes() *CouponUpsertOne {
	return u.Update(func(s *CouponUpsert) {
		s.ClearNotes()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CouponUpsertOne) SetUpdatedAt(v time.Time) *CouponUpsertOne {
	return u.Update(func(s *CouponUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CouponUpsertOne) UpdateUpdatedAt() *CouponUpsertOne {
	return u.Update(func(s *CouponUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CouponUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CouponCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CouponUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CouponUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CouponUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CouponCreateBulk is the builder for creating many Coupon entities in bulk.
type CouponCreateBulk struct {
	config
	err      error
	builders []*CouponCreate
	conflict []sql.ConflictOption
}

// Save creates the Coupon entities in the database.
func (_c *CouponCreateBulk) Save(ctx context.Context) ([]*Coupon, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Coupon, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CouponMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CouponCreateBulk) SaveX(ctx context.Context) []*Coupon {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CouponCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CouponCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Coupon.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CouponUpsert) {
//			SetCode(v+v).
//		}).
//		Exec(ctx)
func (_c *CouponCreateBulk) OnConflict(opts ...sql.ConflictOption) *CouponUpsertBulk {
	_c.conflict = opts
	return &CouponUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Coupon.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CouponCreateBulk) OnConflictColumns(columns ...string) *CouponUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CouponUpsertBulk{
		create: _c,
	}
}

// CouponUpsertBulk is the builder for "upsert"-ing
// a bulk of Coupon nodes.
type CouponUpsertBulk struct {
	create *CouponCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Coupon.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CouponUpsertBulk) UpdateNewValues() *CouponUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(coupon.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Coupon.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CouponUpsertBulk) Ignore() *CouponUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CouponUpsertBulk) DoNothing() *CouponUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CouponCreateBulk.OnConflict
// documentation for more info.
func (u *CouponUpsertBulk) Update(set func(*CouponUpsert)) *CouponUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CouponUpsert{UpdateSet: update})
	}))
	return u
}

// SetCode sets the "code" field.
func (u *CouponUpsertBulk) SetCode(v string) *CouponUpsertBulk {
	return u.Update(func(s *CouponUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *CouponUpsertBulk) UpdateCode() *CouponUpsertBulk {
	return u.Update(func(s *CouponUpsert) {
		s.UpdateCode()
	})
}

// SetType sets the "type" field.
func (u *CouponUpsertBulk) SetType(v string) *CouponUpsertBulk {
	return u.Update(func(s *CouponUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *CouponUpsertBulk) UpdateType() *CouponUpsertBulk {
	return u.Update(func(s *CouponUpsert) {
		s.UpdateType()
	})
}

// SetValue sets the "value" field.
func (u *CouponUpsertBulk) SetValue(v float64) *CouponUpsertBulk {
	return u.Update(func(s *CouponUpsert) {
		s.SetValue(v)
	})
}

// AddValue adds v to the "value" field.
func (u *CouponUpsertBulk) AddValue(v float64) *CouponUpsertBulk {
	return u.Update(func(s *CouponUpsert) {
		s.AddValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *CouponUpsertBulk) UpdateValue() *CouponUpsertBulk {
	return u.Update(func(s *CouponUpsert) {
		s.UpdateValue()
	})
}

// SetMinAmount sets the "min_amount" field.
func (u *CouponUpsertBulk) SetMinAmount(v float64) *CouponUpsertBulk {
	return u.Update(func(s *CouponUpsert) {
		s.SetMinAmount(v)
	})
}

// AddMinAmount adds v to the "min_amount" field.
func (u *CouponUpsertBulk) AddMinAmount(v float64) *CouponUpsertBulk {
	return u.Update(func(s *CouponUpsert) {
		s.AddMinAmount(v)
	})
}

// UpdateMinAmount sets the "min_amount" field to the value that was provided on create.
func (u *CouponUpsertBulk) UpdateMinAmount() *CouponUpsertBulk {
	return u.Update(func(s *CouponUpsert) {
		s.UpdateMinAmount()
	})
}

// SetMaxDiscount sets the "max_discount" field.
func (u *CouponUpsertBulk) SetMaxDiscount(v float64) *CouponUpsertBulk {
	return u.Update(func(s *CouponUpsert) {
		s.SetMaxDiscount(v)
	})
}

// AddMaxDiscount adds v to the "max_discount" field.
func (u *CouponUpsertBulk) AddMaxDiscount(v float64) *CouponUpsertBulk {
	return u.Update(func(s *CouponUpsert) {
		s.AddMaxDiscount(v)
	})
}

// UpdateMaxDiscount sets the "max_discount" field to the value that was provided on create.
func (u *CouponUpsertBulk) UpdateMaxDiscount() *CouponUpsertBulk {
	return u.Update(func(s *CouponUpsert) {
		s.UpdateMaxDiscount()
	})
}

// SetScope sets the "scope" field.
func (u *CouponUpsertBulk) SetScope(v string) *CouponUpsertBulk {
	return u.Update(func(s *CouponUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *CouponUpsertBulk) UpdateScope() *CouponUpsertBulk {
	return u.Update(func(s *CouponUpsert) {
		s.UpdateScope()
	})
}

// SetMaxUses sets the "max_uses" field.
func (u *CouponUpsertBulk) SetMaxUses(v int) *CouponUpsertBulk {
	return u.Update(func(s *CouponUpsert) {
		s.SetMaxUses(v)
	})
}

// AddMaxUses adds v to the "max_uses" field.
func (u *CouponUpsertBulk) AddMaxUses(v int) *CouponUpsertBulk {
	return u.Update(func(s *CouponUpsert) {
		s.AddMaxUses(v)
	})
}

// UpdateMaxUses sets the "max_uses" field to the value that was provided on create.
func (u *CouponUpsertBulk) UpdateMaxUses() *CouponUpsertBulk {
	return u.Update(func(s *CouponUpsert) {
		s.UpdateMaxUses()
	})
}

// SetUsedCount sets the "used_count" field.
func (u *CouponUpsertBulk) SetUsedCount(v int) *CouponUpsertBulk {
	return u.Update(func(s *CouponUpsert) {
		s.SetUsedCount(v)
	})
}

// AddUsedCount adds v to the "used_count" field.
func (u *CouponUpsertBulk) AddUsedCount(v int) *CouponUpsertBulk {
	return u.Update(func(s *CouponUpsert) {
		s.AddUsedCount(v)
	})
}

// UpdateUsedCount sets the "used_count" field to the value that was provided on create.
func (u *CouponUpsertBulk) UpdateUsedCount() *CouponUpsertBulk {
	return u.Update(func(s *CouponUpsert) {
		s.UpdateUsedCount()
	})
}

// SetPerUserLimit sets the "per_user_limit" field.
func (u *CouponUpsertBulk) SetPerUserLimit(v int) *CouponUpsertBulk {
	return u.Update(func(s *CouponUpsert) {
		s.SetPerUserLimit(v)
	})
}

// AddPerUserLimit adds v to the "per_user_limit" field.
func (u *CouponUpsertBulk) AddPerUserLimit(v int) *CouponUpsertBulk {
	return u.Update(func(s *CouponUpsert) {
		s.AddPerUserLimit(v)
	})
}

// UpdatePerUserLimit sets the "per_user_limit" field to the value that was provided on create.
func (u *CouponUpsertBulk) UpdatePerUserLimit() *CouponUpsertBulk {
	return u.Update(func(s *CouponUpsert) {
		s.UpdatePerUserLimit()
	})
}

// SetStatus sets the "status" field.
func (u *CouponUpsertBulk) SetStatus(v string) *CouponUpsertBulk {
	return u.Update(func(s *CouponUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CouponUpsertBulk) UpdateStatus() *CouponUpsertBulk {
	return u.Update(func(s *CouponUpsert) {
		s.UpdateStatus()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *CouponUpsertBulk) SetStartsAt(v time.Time) *CouponUpsertBulk {
	return u.Update(func(s *CouponUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *CouponUpsertBulk) UpdateStartsAt() *CouponUpsertBulk {
	return u.Update(func(s *CouponUpsert) {
		s.UpdateStartsAt()
	})
}

// ClearStartsAt clears the value of the "starts_at" field.
func (u *CouponUpsertBulk) ClearStartsAt() *CouponUpsertBulk {
	return u.Update(func(s *CouponUpsert) {
		s.ClearStartsAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *CouponUpsertBulk) SetExpiresAt(v time.Time) *CouponUpsertBulk {
	return u.Update(func(s *CouponUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *CouponUpsertBulk) UpdateExpiresAt() *CouponUpsertBulk {
	return u.Update(func(s *CouponUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *CouponUpsertBulk) ClearExpiresAt() *CouponUpsertBulk {
	return u.Update(func(s *CouponUpsert) {
		s.ClearExpiresAt()
	})
}

// SetNotes sets the "notes" field.
func (u *CouponUpsertBulk) SetNotes(v string) *CouponUpsertBulk {
	return u.Update(func(s *CouponUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *CouponUpsertBulk) UpdateNotes() *CouponUpsertBulk {
	return u.Update(func(s *CouponUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *CouponUpsertBulk) ClearNotes() *CouponUpsertBulk {
	return u.Update(func(s *CouponUpsert) {
		s.ClearNotes()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CouponUpsertBulk) SetUpdatedAt(v time.Time) *CouponUpsertBulk {
	return u.Update(func(s *CouponUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CouponUpsertBulk) UpdateUpdatedAt() *CouponUpsertBulk {
	return u.Update(func(s *CouponUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CouponUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CouponCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CouponCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CouponUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
