// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/coupon"
	"github.com/Wei-Shaw/sub2api/ent/couponusage"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CouponUpdate is the builder for updating Coupon entities.
type CouponUpdate struct {
	config
	hooks    []Hook
	mutation *CouponMutation
}

// Where appends a list predicates to the CouponUpdate builder.
func (_u *CouponUpdate) Where(ps ...predicate.Coupon) *CouponUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCode sets the "code" field.
func (_u *CouponUpdate) SetCode(v string) *CouponUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *CouponUpdate) SetNillableCode(v *string) *CouponUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *CouponUpdate) SetType(v string) *CouponUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *CouponUpdate) SetNillableType(v *string) *CouponUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *CouponUpdate) SetValue(v float64) *CouponUpdate {
	_u.mutation.ResetValue()
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *CouponUpdate) SetNillableValue(v *float64) *CouponUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// AddValue adds value to the "value" field.
func (_u *CouponUpdate) AddValue(v float64) *CouponUpdate {
	_u.mutation.AddValue(v)
	return _u
}

// SetMinAmount sets the "min_amount" field.
func (_u *CouponUpdate) SetMinAmount(v float64) *CouponUpdate {
	_u.mutation.ResetMinAmount()
	_u.mutation.SetMinAmount(v)
	return _u
}

// SetNillableMinAmount sets the "min_amount" field if the given value is not nil.
func (_u *CouponUpdate) SetNillableMinAmount(v *float64) *CouponUpdate {
	if v != nil {
		_u.SetMinAmount(*v)
	}
	return _u
}

// AddMinAmount adds value to the "min_amount" field.
func (_u *CouponUpdate) AddMinAmount(v float64) *CouponUpdate {
	_u.mutation.AddMinAmount(v)
	return _u
}

// SetMaxDiscount sets the "max_discount" field.
func (_u *CouponUpdate) SetMaxDiscount(v float64) *CouponUpdate {
	_u.mutation.ResetMaxDiscount()
	_u.mutation.SetMaxDiscount(v)
	return _u
}

// SetNillableMaxDiscount sets the "max_discount" field if the given value is not nil.
func (_u *CouponUpdate) SetNillableMaxDiscount(v *float64) *CouponUpdate {
	if v != nil {
		_u.SetMaxDiscount(*v)
	}
	return _u
}

// AddMaxDiscount adds value to the "max_discount" field.
func (_u *CouponUpdate) AddMaxDiscount(v float64) *CouponUpdate {
	_u.mutation.AddMaxDiscount(v)
	return _u
}

// SetScope sets the "scope" field.
func (_u *CouponUpdate) SetScope(v string) *CouponUpdate {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *CouponUpdate) SetNillableScope(v *string) *CouponUpdate {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetMaxUses sets the "max_uses" field.
func (_u *CouponUpdate) SetMaxUses(v int) *CouponUpdate {
	_u.mutation.ResetMaxUses()
	_u.mutation.SetMaxUses(v)
	return _u
}

// SetNillableMaxUses sets the "max_uses" field if the given value is not nil.
func (_u *CouponUpdate) SetNillableMaxUses(v *int) *CouponUpdate {
	if v != nil {
		_u.SetMaxUses(*v)
	}
	return _u
}

// AddMaxUses adds value to the "max_uses" field.
func (_u *CouponUpdate) AddMaxUses(v int) *CouponUpdate {
	_u.mutation.AddMaxUses(v)
	return _u
}

// SetUsedCount sets the "used_count" field.
func (_u *CouponUpdate) SetUsedCount(v int) *CouponUpdate {
	_u.mutation.ResetUsedCount()
	_u.mutation.SetUsedCount(v)
	return _u
}

// SetNillableUsedCount sets the "used_count" field if the given value is not nil.
func (_u *CouponUpdate) SetNillableUsedCount(v *int) *CouponUpdate {
	if v != nil {
		_u.SetUsedCount(*v)
	}
	return _u
}

// AddUsedCount adds value to the "used_count" field.
func (_u *CouponUpdate) AddUsedCount(v int) *CouponUpdate {
	_u.mutation.AddUsedCount(v)
	return _u
}

// SetPerUserLimit sets the "per_user_limit" field.
func (_u *CouponUpdate) SetPerUserLimit(v int) *CouponUpdate {
	_u.mutation.ResetPerUserLimit()
	_u.mutation.SetPerUserLimit(v)
	return _u
}

// SetNillablePerUserLimit sets the "per_user_limit" field if the given value is not nil.
func (_u *CouponUpdate) SetNillablePerUserLimit(v *int) *CouponUpdate {
	if v != nil {
		_u.SetPerUserLimit(*v)
	}
	return _u
}

// AddPerUserLimit adds value to the "per_user_limit" field.
func (_u *CouponUpdate) AddPerUserLimit(v int) *CouponUpdate {
	_u.mutation.AddPerUserLimit(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *CouponUpdate) SetStatus(v string) *CouponUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CouponUpdate) SetNillableStatus(v *string) *CouponUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *CouponUpdate) SetStartsAt(v time.Time) *CouponUpdate {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *CouponUpdate) SetNillableStartsAt(v *time.Time) *CouponUpdate {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// ClearStartsAt clears the value of the "starts_at" field.
func (_u *CouponUpdate) ClearStartsAt() *CouponUpdate {
	_u.mutation.ClearStartsAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *CouponUpdate) SetExpiresAt(v time.Time) *CouponUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *CouponUpdate) SetNillableExpiresAt(v *time.Time) *CouponUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *CouponUpdate) ClearExpiresAt() *CouponUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *CouponUpdate) SetNotes(v string) *CouponUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *CouponUpdate) SetNillableNotes(v *string) *CouponUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *CouponUpdate) ClearNotes() *CouponUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CouponUpdate) SetUpdatedAt(v time.Time) *CouponUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUsageRecordIDs adds the "usage_records" edge to the CouponUsage entity by IDs.
func (_u *CouponUpdate) AddUsageRecordIDs(ids ...int64) *CouponUpdate {
	_u.mutation.AddUsageRecordIDs(ids...)
	return _u
}

// AddUsageRecords adds the "usage_records" edges to the CouponUsage entity.
func (_u *CouponUpdate) AddUsageRecords(v ...*CouponUsage) *CouponUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageRecordIDs(ids...)
}

// Mutation returns the CouponMutation object of the builder.
func (_u *CouponUpdate) Mutation() *CouponMutation {
	return _u.mutation
}

// ClearUsageRecords clears all "usage_records" edges to the CouponUsage entity.
func (_u *CouponUpdate) ClearUsageRecords() *CouponUpdate {
	_u.mutation.ClearUsageRecords()
	return _u
}

// RemoveUsageRecordIDs removes the "usage_records" edge to CouponUsage entities by IDs.
func (_u *CouponUpdate) RemoveUsageRecordIDs(ids ...int64) *CouponUpdate {
	_u.mutation.RemoveUsageRecordIDs(ids...)
	return _u
}

// RemoveUsageRecords removes "usage_records" edges to CouponUsage entities.
func (_u *CouponUpdate) RemoveUsageRecords(v ...*CouponUsage) *CouponUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageRecordIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CouponUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CouponUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CouponUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CouponUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CouponUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := coupon.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CouponUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := coupon.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Coupon.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := coupon.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Coupon.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Scope(); ok {
		if err := coupon.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "Coupon.scope": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := coupon.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Coupon.status": %w`, err)}
		}
	}
	return nil
}

func (_u *CouponUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(coupon.Table, coupon.Columns, sqlgraph.NewFieldSpec(coupon.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(coupon.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(coupon.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(coupon.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedValue(); ok {
		_spec.AddField(coupon.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MinAmount(); ok {
		_spec.SetField(coupon.FieldMinAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMinAmount(); ok {
		_spec.AddField(coupon.FieldMinAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxDiscount(); ok {
		_spec.SetField(coupon.FieldMaxDiscount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxDiscount(); ok {
		_spec.AddField(coupon.FieldMaxDiscount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(coupon.FieldScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.MaxUses(); ok {
		_spec.SetField(coupon.FieldMaxUses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxUses(); ok {
		_spec.AddField(coupon.FieldMaxUses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UsedCount(); ok {
		_spec.SetField(coupon.FieldUsedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUsedCount(); ok {
		_spec.AddField(coupon.FieldUsedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PerUserLimit(); ok {
		_spec.SetField(coupon.FieldPerUserLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPerUserLimit(); ok {
		_spec.AddField(coupon.FieldPerUserLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(coupon.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(coupon.FieldStartsAt, field.TypeTime, value)
	}
	if _u.mutation.StartsAtCleared() {
		_spec.ClearField(coupon.FieldStartsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(coupon.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(coupon.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(coupon.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(coupon.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(coupon.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UsageRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   coupon.UsageRecordsTable,
			Columns: []string{coupon.UsageRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(couponusage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageRecordsIDs(); len(nodes) > 0 && !_u.mutation.UsageRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   coupon.UsageRecordsTable,
			Columns: []string{coupon.UsageRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(couponusage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   coupon.UsageRecordsTable,
			Columns: []string{coupon.UsageRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(couponusage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{coupon.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CouponUpdateOne is the builder for updating a single Coupon entity.
type CouponUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CouponMutation
}

// SetCode sets the "code" field.
func (_u *CouponUpdateOne) SetCode(v string) *CouponUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *CouponUpdateOne) SetNillableCode(v *string) *CouponUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *CouponUpdateOne) SetType(v string) *CouponUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *CouponUpdateOne) SetNillableType(v *string) *CouponUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *CouponUpdateOne) SetValue(v float64) *CouponUpdateOne {
	_u.mutation.ResetValue()
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *CouponUpdateOne) SetNillableValue(v *float64) *CouponUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// AddValue adds value to the "value" field.
func (_u *CouponUpdateOne) AddValue(v float64) *CouponUpdateOne {
	_u.mutation.AddValue(v)
	return _u
}

// SetMinAmount sets the "min_amount" field.
func (_u *CouponUpdateOne) SetMinAmount(v float64) *CouponUpdateOne {
	_u.mutation.ResetMinAmount()
	_u.mutation.SetMinAmount(v)
	return _u
}

// SetNillableMinAmount sets the "min_amount" field if the given value is not nil.
func (_u *CouponUpdateOne) SetNillableMinAmount(v *float64) *CouponUpdateOne {
	if v != nil {
		_u.SetMinAmount(*v)
	}
	return _u
}

// AddMinAmount adds value to the "min_amount" field.
func (_u *CouponUpdateOne) AddMinAmount(v float64) *CouponUpdateOne {
	_u.mutation.AddMinAmount(v)
	return _u
}

// SetMaxDiscount sets the "max_discount" field.
func (_u *CouponUpdateOne) SetMaxDiscount(v float64) *CouponUpdateOne {
	_u.mutation.ResetMaxDiscount()
	_u.mutation.SetMaxDiscount(v)
	return _u
}

// SetNillableMaxDiscount sets the "max_discount" field if the given value is not nil.
func (_u *CouponUpdateOne) SetNillableMaxDiscount(v *float64) *CouponUpdateOne {
	if v != nil {
		_u.SetMaxDiscount(*v)
	}
	return _u
}

// AddMaxDiscount adds value to the "max_discount" field.
func (_u *CouponUpdateOne) AddMaxDiscount(v float64) *CouponUpdateOne {
	_u.mutation.AddMaxDiscount(v)
	return _u
}

// SetScope sets the "scope" field.
func (_u *CouponUpdateOne) SetScope(v string) *CouponUpdateOne {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *CouponUpdateOne) SetNillableScope(v *string) *CouponUpdateOne {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetMaxUses sets the "max_uses" field.
func (_u *CouponUpdateOne) SetMaxUses(v int) *CouponUpdateOne {
	_u.mutation.ResetMaxUses()
	_u.mutation.SetMaxUses(v)
	return _u
}

// SetNillableMaxUses sets the "max_uses" field if the given value is not nil.
func (_u *CouponUpdateOne) SetNillableMaxUses(v *int) *CouponUpdateOne {
	if v != nil {
		_u.SetMaxUses(*v)
	}
	return _u
}

// AddMaxUses adds value to the "max_uses" field.
func (_u *CouponUpdateOne) AddMaxUses(v int) *CouponUpdateOne {
	_u.mutation.AddMaxUses(v)
	return _u
}

// SetUsedCount sets the "used_count" field.
func (_u *CouponUpdateOne) SetUsedCount(v int) *CouponUpdateOne {
	_u.mutation.ResetUsedCount()
	_u.mutation.SetUsedCount(v)
	return _u
}

// SetNillableUsedCount sets the "used_count" field if the given value is not nil.
func (_u *CouponUpdateOne) SetNillableUsedCount(v *int) *CouponUpdateOne {
	if v != nil {
		_u.SetUsedCount(*v)
	}
	return _u
}

// AddUsedCount adds value to the "used_count" field.
func (_u *CouponUpdateOne) AddUsedCount(v int) *CouponUpdateOne {
	_u.mutation.AddUsedCount(v)
	return _u
}

// SetPerUserLimit sets the "per_user_limit" field.
func (_u *CouponUpdateOne) SetPerUserLimit(v int) *CouponUpdateOne {
	_u.mutation.ResetPerUserLimit()
	_u.mutation.SetPerUserLimit(v)
	return _u
}

// SetNillablePerUserLimit sets the "per_user_limit" field if the given value is not nil.
func (_u *CouponUpdateOne) SetNillablePerUserLimit(v *int) *CouponUpdateOne {
	if v != nil {
		_u.SetPerUserLimit(*v)
	}
	return _u
}

// AddPerUserLimit adds value to the "per_user_limit" field.
func (_u *CouponUpdateOne) AddPerUserLimit(v int) *CouponUpdateOne {
	_u.mutation.AddPerUserLimit(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *CouponUpdateOne) SetStatus(v string) *CouponUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CouponUpdateOne) SetNillableStatus(v *string) *CouponUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *CouponUpdateOne) SetStartsAt(v time.Time) *CouponUpdateOne {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *CouponUpdateOne) SetNillableStartsAt(v *time.Time) *CouponUpdateOne {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// ClearStartsAt clears the value of the "starts_at" field.
func (_u *CouponUpdateOne) ClearStartsAt() *CouponUpdateOne {
	_u.mutation.ClearStartsAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *CouponUpdateOne) SetExpiresAt(v time.Time) *CouponUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *CouponUpdateOne) SetNillableExpiresAt(v *time.Time) *CouponUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *CouponUpdateOne) ClearExpiresAt() *CouponUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *CouponUpdateOne) SetNotes(v string) *CouponUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *CouponUpdateOne) SetNillableNotes(v *string) *CouponUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *CouponUpdateOne) ClearNotes() *CouponUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CouponUpdateOne) SetUpdatedAt(v time.Time) *CouponUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUsageRecordIDs adds the "usage_records" edge to the CouponUsage entity by IDs.
func (_u *CouponUpdateOne) AddUsageRecordIDs(ids ...int64) *CouponUpdateOne {
	_u.mutation.AddUsageRecordIDs(ids...)
	return _u
}

// AddUsageRecords adds the "usage_records" edges to the CouponUsage entity.
func (_u *CouponUpdateOne) AddUsageRecords(v ...*CouponUsage) *CouponUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageRecordIDs(ids...)
}

// Mutation returns the CouponMutation object of the builder.
func (_u *CouponUpdateOne) Mutation() *CouponMutation {
	return _u.mutation
}

// ClearUsageRecords clears all "usage_records" edges to the CouponUsage entity.
func (_u *CouponUpdateOne) ClearUsageRecords() *CouponUpdateOne {
	_u.mutation.ClearUsageRecords()
	return _u
}

// RemoveUsageRecordIDs removes the "usage_records" edge to CouponUsage entities by IDs.
func (_u *CouponUpdateOne) RemoveUsageRecordIDs(ids ...int64) *CouponUpdateOne {
	_u.mutation.RemoveUsageRecordIDs(ids...)
	return _u
}

// RemoveUsageRecords removes "usage_records" edges to CouponUsage entities.
func (_u *CouponUpdateOne) RemoveUsageRecords(v ...*CouponUsage) *CouponUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageRecordIDs(ids...)
}

// Where appends a list predicates to the CouponUpdate builder.
func (_u *CouponUpdateOne) Where(ps ...predicate.Coupon) *CouponUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CouponUpdateOne) Select(field string, fields ...string) *CouponUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Coupon entity.
func (_u *CouponUpdateOne) Save(ctx context.Context) (*Coupon, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CouponUpdateOne) SaveX(ctx context.Context) *Coupon {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CouponUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CouponUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CouponUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := coupon.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CouponUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := coupon.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Coupon.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := coupon.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Coupon.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Scope(); ok {
		if err := coupon.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "Coupon.scope": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := coupon.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Coupon.status": %w`, err)}
		}
	}
	return nil
}

func (_u *CouponUpdateOne) sqlSave(ctx context.Context) (_node *Coupon, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(coupon.Table, coupon.Columns, sqlgraph.NewFieldSpec(coupon.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Coupon.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, coupon.FieldID)
		for _, f := range fields {
			if !coupon.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != coupon.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(coupon.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(coupon.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(coupon.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedValue(); ok {
		_spec.AddField(coupon.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MinAmount(); ok {
		_spec.SetField(coupon.FieldMinAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMinAmount(); ok {
		_spec.AddField(coupon.FieldMinAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxDiscount(); ok {
		_spec.SetField(coupon.FieldMaxDiscount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxDiscount(); ok {
		_spec.AddField(coupon.FieldMaxDiscount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(coupon.FieldScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.MaxUses(); ok {
		_spec.SetField(coupon.FieldMaxUses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxUses(); ok {
		_spec.AddField(coupon.FieldMaxUses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UsedCount(); ok {
		_spec.SetField(coupon.FieldUsedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUsedCount(); ok {
		_spec.AddField(coupon.FieldUsedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PerUserLimit(); ok {
		_spec.SetField(coupon.FieldPerUserLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPerUserLimit(); ok {
		_spec.AddField(coupon.FieldPerUserLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(coupon.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(coupon.FieldStartsAt, field.TypeTime, value)
	}
	if _u.mutation.StartsAtCleared() {
		_spec.ClearField(coupon.FieldStartsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(coupon.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(coupon.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(coupon.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(coupon.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(coupon.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UsageRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   coupon.UsageRecordsTable,
			Columns: []string{coupon.UsageRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(couponusage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageRecordsIDs(); len(nodes) > 0 && !_u.mutation.UsageRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   coupon.UsageRecordsTable,
			Columns: []string{coupon.UsageRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(couponusage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   coupon.UsageRecordsTable,
			Columns: []string{coupon.UsageRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(couponusage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Coupon{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{coupon.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
