// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/invoiceapplication"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// InvoiceApplication is the model entity for the InvoiceApplication schema.
type InvoiceApplication struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// InvoiceType holds the value of the "invoice_type" field.
	InvoiceType string `json:"invoice_type,omitempty"`
	// HeaderType holds the value of the "header_type" field.
	HeaderType string `json:"header_type,omitempty"`
	// HeaderTitle holds the value of the "header_title" field.
	HeaderTitle string `json:"header_title,omitempty"`
	// HeaderTaxNumber holds the value of the "header_tax_number" field.
	HeaderTaxNumber string `json:"header_tax_number,omitempty"`
	// HeaderEmail holds the value of the "header_email" field.
	HeaderEmail string `json:"header_email,omitempty"`
	// HeaderPhone holds the value of the "header_phone" field.
	HeaderPhone string `json:"header_phone,omitempty"`
	// HeaderAddress holds the value of the "header_address" field.
	HeaderAddress *string `json:"header_address,omitempty"`
	// TotalAmount holds the value of the "total_amount" field.
	TotalAmount float64 `json:"total_amount,omitempty"`
	// HandledBy holds the value of the "handled_by" field.
	HandledBy *int64 `json:"handled_by,omitempty"`
	// RejectionReason holds the value of the "rejection_reason" field.
	RejectionReason *string `json:"rejection_reason,omitempty"`
	// AdminNote holds the value of the "admin_note" field.
	AdminNote *string `json:"admin_note,omitempty"`
	// InvoiceNumber holds the value of the "invoice_number" field.
	InvoiceNumber string `json:"invoice_number,omitempty"`
	// ProcessedAt holds the value of the "processed_at" field.
	ProcessedAt *time.Time `json:"processed_at,omitempty"`
	// InvoicedAt holds the value of the "invoiced_at" field.
	InvoicedAt *time.Time `json:"invoiced_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the InvoiceApplicationQuery when eager-loading is set.
	Edges        InvoiceApplicationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// InvoiceApplicationEdges holds the relations/edges for other nodes in the graph.
type InvoiceApplicationEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Orders holds the value of the orders edge.
	Orders []*InvoiceApplicationOrder `json:"orders,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InvoiceApplicationEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// OrdersOrErr returns the Orders value or an error if the edge
// was not loaded in eager-loading.
func (e InvoiceApplicationEdges) OrdersOrErr() ([]*InvoiceApplicationOrder, error) {
	if e.loadedTypes[1] {
		return e.Orders, nil
	}
	return nil, &NotLoadedError{edge: "orders"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InvoiceApplication) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case invoiceapplication.FieldTotalAmount:
			values[i] = new(sql.NullFloat64)
		case invoiceapplication.FieldID, invoiceapplication.FieldUserID, invoiceapplication.FieldHandledBy:
			values[i] = new(sql.NullInt64)
		case invoiceapplication.FieldStatus, invoiceapplication.FieldInvoiceType, invoiceapplication.FieldHeaderType, invoiceapplication.FieldHeaderTitle, invoiceapplication.FieldHeaderTaxNumber, invoiceapplication.FieldHeaderEmail, invoiceapplication.FieldHeaderPhone, invoiceapplication.FieldHeaderAddress, invoiceapplication.FieldRejectionReason, invoiceapplication.FieldAdminNote, invoiceapplication.FieldInvoiceNumber:
			values[i] = new(sql.NullString)
		case invoiceapplication.FieldProcessedAt, invoiceapplication.FieldInvoicedAt, invoiceapplication.FieldCreatedAt, invoiceapplication.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InvoiceApplication fields.
func (_m *InvoiceApplication) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case invoiceapplication.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case invoiceapplication.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case invoiceapplication.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case invoiceapplication.FieldInvoiceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field invoice_type", values[i])
			} else if value.Valid {
				_m.InvoiceType = value.String
			}
		case invoiceapplication.FieldHeaderType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field header_type", values[i])
			} else if value.Valid {
				_m.HeaderType = value.String
			}
		case invoiceapplication.FieldHeaderTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field header_title", values[i])
			} else if value.Valid {
				_m.HeaderTitle = value.String
			}
		case invoiceapplication.FieldHeaderTaxNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field header_tax_number", values[i])
			} else if value.Valid {
				_m.HeaderTaxNumber = value.String
			}
		case invoiceapplication.FieldHeaderEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field header_email", values[i])
			} else if value.Valid {
				_m.HeaderEmail = value.String
			}
		case invoiceapplication.FieldHeaderPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field header_phone", values[i])
			} else if value.Valid {
				_m.HeaderPhone = value.String
			}
		case invoiceapplication.FieldHeaderAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field header_address", values[i])
			} else if value.Valid {
				_m.HeaderAddress = new(string)
				*_m.HeaderAddress = value.String
			}
		case invoiceapplication.FieldTotalAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_amount", values[i])
			} else if value.Valid {
				_m.TotalAmount = value.Float64
			}
		case invoiceapplication.FieldHandledBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field handled_by", values[i])
			} else if value.Valid {
				_m.HandledBy = new(int64)
				*_m.HandledBy = value.Int64
			}
		case invoiceapplication.FieldRejectionReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rejection_reason", values[i])
			} else if value.Valid {
				_m.RejectionReason = new(string)
				*_m.RejectionReason = value.String
			}
		case invoiceapplication.FieldAdminNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field admin_note", values[i])
			} else if value.Valid {
				_m.AdminNote = new(string)
				*_m.AdminNote = value.String
			}
		case invoiceapplication.FieldInvoiceNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field invoice_number", values[i])
			} else if value.Valid {
				_m.InvoiceNumber = value.String
			}
		case invoiceapplication.FieldProcessedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field processed_at", values[i])
			} else if value.Valid {
				_m.ProcessedAt = new(time.Time)
				*_m.ProcessedAt = value.Time
			}
		case invoiceapplication.FieldInvoicedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field invoiced_at", values[i])
			} else if value.Valid {
				_m.InvoicedAt = new(time.Time)
				*_m.InvoicedAt = value.Time
			}
		case invoiceapplication.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case invoiceapplication.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InvoiceApplication.
// This includes values selected through modifiers, order, etc.
func (_m *InvoiceApplication) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the InvoiceApplication entity.
func (_m *InvoiceApplication) QueryUser() *UserQuery {
	return NewInvoiceApplicationClient(_m.config).QueryUser(_m)
}

// QueryOrders queries the "orders" edge of the InvoiceApplication entity.
func (_m *InvoiceApplication) QueryOrders() *InvoiceApplicationOrderQuery {
	return NewInvoiceApplicationClient(_m.config).QueryOrders(_m)
}

// Update returns a builder for updating this InvoiceApplication.
// Note that you need to call InvoiceApplication.Unwrap() before calling this method if this InvoiceApplication
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InvoiceApplication) Update() *InvoiceApplicationUpdateOne {
	return NewInvoiceApplicationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InvoiceApplication entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InvoiceApplication) Unwrap() *InvoiceApplication {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InvoiceApplication is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InvoiceApplication) String() string {
	var builder strings.Builder
	builder.WriteString("InvoiceApplication(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("invoice_type=")
	builder.WriteString(_m.InvoiceType)
	builder.WriteString(", ")
	builder.WriteString("header_type=")
	builder.WriteString(_m.HeaderType)
	builder.WriteString(", ")
	builder.WriteString("header_title=")
	builder.WriteString(_m.HeaderTitle)
	builder.WriteString(", ")
	builder.WriteString("header_tax_number=")
	builder.WriteString(_m.HeaderTaxNumber)
	builder.WriteString(", ")
	builder.WriteString("header_email=")
	builder.WriteString(_m.HeaderEmail)
	builder.WriteString(", ")
	builder.WriteString("header_phone=")
	builder.WriteString(_m.HeaderPhone)
	builder.WriteString(", ")
	if v := _m.HeaderAddress; v != nil {
		builder.WriteString("header_address=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("total_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalAmount))
	builder.WriteString(", ")
	if v := _m.HandledBy; v != nil {
		builder.WriteString("handled_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RejectionReason; v != nil {
		builder.WriteString("rejection_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.AdminNote; v != nil {
		builder.WriteString("admin_note=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("invoice_number=")
	builder.WriteString(_m.InvoiceNumber)
	builder.WriteString(", ")
	if v := _m.ProcessedAt; v != nil {
		builder.WriteString("processed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.InvoicedAt; v != nil {
		builder.WriteString("invoiced_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// InvoiceApplications is a parsable slice of InvoiceApplication.
type InvoiceApplications []*InvoiceApplication
