// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoiceheader"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// InvoiceHeaderDelete is the builder for deleting a InvoiceHeader entity.
type InvoiceHeaderDelete struct {
	config
	hooks    []Hook
	mutation *InvoiceHeaderMutation
}

// Where appends a list predicates to the InvoiceHeaderDelete builder.
func (_d *InvoiceHeaderDelete) Where(ps ...predicate.InvoiceHeader) *InvoiceHeaderDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *InvoiceHeaderDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *InvoiceHeaderDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *InvoiceHeaderDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(invoiceheader.Table, sqlgraph.NewFieldSpec(invoiceheader.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// InvoiceHeaderDeleteOne is the builder for deleting a single InvoiceHeader entity.
type InvoiceHeaderDeleteOne struct {
	_d *InvoiceHeaderDelete
}

// Where appends a list predicates to the InvoiceHeaderDelete builder.
func (_d *InvoiceHeaderDeleteOne) Where(ps ...predicate.InvoiceHeader) *InvoiceHeaderDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *InvoiceHeaderDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{invoiceheader.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *InvoiceHeaderDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
