// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoiceapplication"
	"github.com/Wei-Shaw/sub2api/ent/invoiceapplicationorder"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
)

// InvoiceApplicationOrderCreate is the builder for creating a InvoiceApplicationOrder entity.
type InvoiceApplicationOrderCreate struct {
	config
	mutation *InvoiceApplicationOrderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetApplicationID sets the "application_id" field.
func (_c *InvoiceApplicationOrderCreate) SetApplicationID(v int64) *InvoiceApplicationOrderCreate {
	_c.mutation.SetApplicationID(v)
	return _c
}

// SetOrderID sets the "order_id" field.
func (_c *InvoiceApplicationOrderCreate) SetOrderID(v int64) *InvoiceApplicationOrderCreate {
	_c.mutation.SetOrderID(v)
	return _c
}

// SetOrderNo sets the "order_no" field.
func (_c *InvoiceApplicationOrderCreate) SetOrderNo(v string) *InvoiceApplicationOrderCreate {
	_c.mutation.SetOrderNo(v)
	return _c
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_c *InvoiceApplicationOrderCreate) SetNillableOrderNo(v *string) *InvoiceApplicationOrderCreate {
	if v != nil {
		_c.SetOrderNo(*v)
	}
	return _c
}

// SetOrderType sets the "order_type" field.
func (_c *InvoiceApplicationOrderCreate) SetOrderType(v string) *InvoiceApplicationOrderCreate {
	_c.mutation.SetOrderType(v)
	return _c
}

// SetNillableOrderType sets the "order_type" field if the given value is not nil.
func (_c *InvoiceApplicationOrderCreate) SetNillableOrderType(v *string) *InvoiceApplicationOrderCreate {
	if v != nil {
		_c.SetOrderType(*v)
	}
	return _c
}

// SetAmount sets the "amount" field.
func (_c *InvoiceApplicationOrderCreate) SetAmount(v float64) *InvoiceApplicationOrderCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetPaidAt sets the "paid_at" field.
func (_c *InvoiceApplicationOrderCreate) SetPaidAt(v time.Time) *InvoiceApplicationOrderCreate {
	_c.mutation.SetPaidAt(v)
	return _c
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_c *InvoiceApplicationOrderCreate) SetNillablePaidAt(v *time.Time) *InvoiceApplicationOrderCreate {
	if v != nil {
		_c.SetPaidAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InvoiceApplicationOrderCreate) SetCreatedAt(v time.Time) *InvoiceApplicationOrderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InvoiceApplicationOrderCreate) SetNillableCreatedAt(v *time.Time) *InvoiceApplicationOrderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetApplication sets the "application" edge to the InvoiceApplication entity.
func (_c *InvoiceApplicationOrderCreate) SetApplication(v *InvoiceApplication) *InvoiceApplicationOrderCreate {
	return _c.SetApplicationID(v.ID)
}

// SetPaymentOrderID sets the "payment_order" edge to the PaymentOrder entity by ID.
func (_c *InvoiceApplicationOrderCreate) SetPaymentOrderID(id int64) *InvoiceApplicationOrderCreate {
	_c.mutation.SetPaymentOrderID(id)
	return _c
}

// SetPaymentOrder sets the "payment_order" edge to the PaymentOrder entity.
func (_c *InvoiceApplicationOrderCreate) SetPaymentOrder(v *PaymentOrder) *InvoiceApplicationOrderCreate {
	return _c.SetPaymentOrderID(v.ID)
}

// Mutation returns the InvoiceApplicationOrderMutation object of the builder.
func (_c *InvoiceApplicationOrderCreate) Mutation() *InvoiceApplicationOrderMutation {
	return _c.mutation
}

// Save creates the InvoiceApplicationOrder in the database.
func (_c *InvoiceApplicationOrderCreate) Save(ctx context.Context) (*InvoiceApplicationOrder, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InvoiceApplicationOrderCreate) SaveX(ctx context.Context) *InvoiceApplicationOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceApplicationOrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceApplicationOrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InvoiceApplicationOrderCreate) defaults() {
	if _, ok := _c.mutation.OrderNo(); !ok {
		v := invoiceapplicationorder.DefaultOrderNo
		_c.mutation.SetOrderNo(v)
	}
	if _, ok := _c.mutation.OrderType(); !ok {
		v := invoiceapplicationorder.DefaultOrderType
		_c.mutation.SetOrderType(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := invoiceapplicationorder.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InvoiceApplicationOrderCreate) check() error {
	if _, ok := _c.mutation.ApplicationID(); !ok {
		return &ValidationError{Name: "application_id", err: errors.New(`ent: missing required field "InvoiceApplicationOrder.application_id"`)}
	}
	if _, ok := _c.mutation.OrderID(); !ok {
		return &ValidationError{Name: "order_id", err: errors.New(`ent: missing required field "InvoiceApplicationOrder.order_id"`)}
	}
	if _, ok := _c.mutation.OrderNo(); !ok {
		return &ValidationError{Name: "order_no", err: errors.New(`ent: missing required field "InvoiceApplicationOrder.order_no"`)}
	}
	if v, ok := _c.mutation.OrderNo(); ok {
		if err := invoiceapplicationorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplicationOrder.order_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OrderType(); !ok {
		return &ValidationError{Name: "order_type", err: errors.New(`ent: missing required field "InvoiceApplicationOrder.order_type"`)}
	}
	if v, ok := _c.mutation.OrderType(); ok {
		if err := invoiceapplicationorder.OrderTypeValidator(v); err != nil {
			return &ValidationError{Name: "order_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplicationOrder.order_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "InvoiceApplicationOrder.amount"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "InvoiceApplicationOrder.created_at"`)}
	}
	if len(_c.mutation.ApplicationIDs()) == 0 {
		return &ValidationError{Name: "application", err: errors.New(`ent: missing required edge "InvoiceApplicationOrder.application"`)}
	}
	if len(_c.mutation.PaymentOrderIDs()) == 0 {
		return &ValidationError{Name: "payment_order", err: errors.New(`ent: missing required edge "InvoiceApplicationOrder.payment_order"`)}
	}
	return nil
}

func (_c *InvoiceApplicationOrderCreate) sqlSave(ctx context.Context) (*InvoiceApplicationOrder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InvoiceApplicationOrderCreate) createSpec() (*InvoiceApplicationOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &InvoiceApplicationOrder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(invoiceapplicationorder.Table, sqlgraph.NewFieldSpec(invoiceapplicationorder.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.OrderNo(); ok {
		_spec.SetField(invoiceapplicationorder.FieldOrderNo, field.TypeString, value)
		_node.OrderNo = value
	}
	if value, ok := _c.mutation.OrderType(); ok {
		_spec.SetField(invoiceapplicationorder.FieldOrderType, field.TypeString, value)
		_node.OrderType = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(invoiceapplicationorder.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.PaidAt(); ok {
		_spec.SetField(invoiceapplicationorder.FieldPaidAt, field.TypeTime, value)
		_node.PaidAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(invoiceapplicationorder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ApplicationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceapplicationorder.ApplicationTable,
			Columns: []string{invoiceapplicationorder.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceapplication.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ApplicationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PaymentOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceapplicationorder.PaymentOrderTable,
			Columns: []string{invoiceapplicationorder.PaymentOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrderID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceApplicationOrder.Create().
//		SetApplicationID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceApplicationOrderUpsert) {
//			SetApplicationID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceApplicationOrderCreate) OnConflict(opts ...sql.ConflictOption) *InvoiceApplicationOrderUpsertOne {
	_c.conflict = opts
	return &InvoiceApplicationOrderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceApplicationOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceApplicationOrderCreate) OnConflictColumns(columns ...string) *InvoiceApplicationOrderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceApplicationOrderUpsertOne{
		create: _c,
	}
}

type (
	// InvoiceApplicationOrderUpsertOne is the builder for "upsert"-ing
	//  one InvoiceApplicationOrder node.
	InvoiceApplicationOrderUpsertOne struct {
		create *InvoiceApplicationOrderCreate
	}

	// InvoiceApplicationOrderUpsert is the "OnConflict" setter.
	InvoiceApplicationOrderUpsert struct {
		*sql.UpdateSet
	}
)

// SetApplicationID sets the "application_id" field.
func (u *InvoiceApplicationOrderUpsert) SetApplicationID(v int64) *InvoiceApplicationOrderUpsert {
	u.Set(invoiceapplicationorder.FieldApplicationID, v)
	return u
}

// UpdateApplicationID sets the "application_id" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsert) UpdateApplicationID() *InvoiceApplicationOrderUpsert {
	u.SetExcluded(invoiceapplicationorder.FieldApplicationID)
	return u
}

// SetOrderID sets the "order_id" field.
func (u *InvoiceApplicationOrderUpsert) SetOrderID(v int64) *InvoiceApplicationOrderUpsert {
	u.Set(invoiceapplicationorder.FieldOrderID, v)
	return u
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsert) UpdateOrderID() *InvoiceApplicationOrderUpsert {
	u.SetExcluded(invoiceapplicationorder.FieldOrderID)
	return u
}

// SetOrderNo sets the "order_no" field.
func (u *InvoiceApplicationOrderUpsert) SetOrderNo(v string) *InvoiceApplicationOrderUpsert {
	u.Set(invoiceapplicationorder.FieldOrderNo, v)
	return u
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsert) UpdateOrderNo() *InvoiceApplicationOrderUpsert {
	u.SetExcluded(invoiceapplicationorder.FieldOrderNo)
	return u
}

// SetOrderType sets the "order_type" field.
func (u *InvoiceApplicationOrderUpsert) SetOrderType(v string) *InvoiceApplicationOrderUpsert {
	u.Set(invoiceapplicationorder.FieldOrderType, v)
	return u
}

// UpdateOrderType sets the "order_type" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsert) UpdateOrderType() *InvoiceApplicationOrderUpsert {
	u.SetExcluded(invoiceapplicationorder.FieldOrderType)
	return u
}

// SetAmount sets the "amount" field.
func (u *InvoiceApplicationOrderUpsert) SetAmount(v float64) *InvoiceApplicationOrderUpsert {
	u.Set(invoiceapplicationorder.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsert) UpdateAmount() *InvoiceApplicationOrderUpsert {
	u.SetExcluded(invoiceapplicationorder.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *InvoiceApplicationOrderUpsert) AddAmount(v float64) *InvoiceApplicationOrderUpsert {
	u.Add(invoiceapplicationorder.FieldAmount, v)
	return u
}

// SetPaidAt sets the "paid_at" field.
func (u *InvoiceApplicationOrderUpsert) SetPaidAt(v time.Time) *InvoiceApplicationOrderUpsert {
	u.Set(invoiceapplicationorder.FieldPaidAt, v)
	return u
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsert) UpdatePaidAt() *InvoiceApplicationOrderUpsert {
	u.SetExcluded(invoiceapplicationorder.FieldPaidAt)
	return u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *InvoiceApplicationOrderUpsert) ClearPaidAt() *InvoiceApplicationOrderUpsert {
	u.SetNull(invoiceapplicationorder.FieldPaidAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.InvoiceApplicationOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceApplicationOrderUpsertOne) UpdateNewValues() *InvoiceApplicationOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(invoiceapplicationorder.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceApplicationOrder.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InvoiceApplicationOrderUpsertOne) Ignore() *InvoiceApplicationOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceApplicationOrderUpsertOne) DoNothing() *InvoiceApplicationOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceApplicationOrderCreate.OnConflict
// documentation for more info.
func (u *InvoiceApplicationOrderUpsertOne) Update(set func(*InvoiceApplicationOrderUpsert)) *InvoiceApplicationOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceApplicationOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetApplicationID sets the "application_id" field.
func (u *InvoiceApplicationOrderUpsertOne) SetApplicationID(v int64) *InvoiceApplicationOrderUpsertOne {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.SetApplicationID(v)
	})
}

// UpdateApplicationID sets the "application_id" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsertOne) UpdateApplicationID() *InvoiceApplicationOrderUpsertOne {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.UpdateApplicationID()
	})
}

// SetOrderID sets the "order_id" field.
func (u *InvoiceApplicationOrderUpsertOne) SetOrderID(v int64) *InvoiceApplicationOrderUpsertOne {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.SetOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsertOne) UpdateOrderID() *InvoiceApplicationOrderUpsertOne {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.UpdateOrderID()
	})
}

// SetOrderNo sets the "order_no" field.
func (u *InvoiceApplicationOrderUpsertOne) SetOrderNo(v string) *InvoiceApplicationOrderUpsertOne {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.SetOrderNo(v)
	})
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsertOne) UpdateOrderNo() *InvoiceApplicationOrderUpsertOne {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.UpdateOrderNo()
	})
}

// SetOrderType sets the "order_type" field.
func (u *InvoiceApplicationOrderUpsertOne) SetOrderType(v string) *InvoiceApplicationOrderUpsertOne {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.SetOrderType(v)
	})
}

// UpdateOrderType sets the "order_type" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsertOne) UpdateOrderType() *InvoiceApplicationOrderUpsertOne {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.UpdateOrderType()
	})
}

// SetAmount sets the "amount" field.
func (u *InvoiceApplicationOrderUpsertOne) SetAmount(v float64) *InvoiceApplicationOrderUpsertOne {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *InvoiceApplicationOrderUpsertOne) AddAmount(v float64) *InvoiceApplicationOrderUpsertOne {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsertOne) UpdateAmount() *InvoiceApplicationOrderUpsertOne {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.UpdateAmount()
	})
}

// SetPaidAt sets the "paid_at" field.
func (u *InvoiceApplicationOrderUpsertOne) SetPaidAt(v time.Time) *InvoiceApplicationOrderUpsertOne {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.SetPaidAt(v)
	})
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsertOne) UpdatePaidAt() *InvoiceApplicationOrderUpsertOne {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.UpdatePaidAt()
	})
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *InvoiceApplicationOrderUpsertOne) ClearPaidAt() *InvoiceApplicationOrderUpsertOne {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.ClearPaidAt()
	})
}

// Exec executes the query.
func (u *InvoiceApplicationOrderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceApplicationOrderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceApplicationOrderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InvoiceApplicationOrderUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InvoiceApplicationOrderUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InvoiceApplicationOrderCreateBulk is the builder for creating many InvoiceApplicationOrder entities in bulk.
type InvoiceApplicationOrderCreateBulk struct {
	config
	err      error
	builders []*InvoiceApplicationOrderCreate
	conflict []sql.ConflictOption
}

// Save creates the InvoiceApplicationOrder entities in the database.
func (_c *InvoiceApplicationOrderCreateBulk) Save(ctx context.Context) ([]*InvoiceApplicationOrder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InvoiceApplicationOrder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InvoiceApplicationOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InvoiceApplicationOrderCreateBulk) SaveX(ctx context.Context) []*InvoiceApplicationOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceApplicationOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceApplicationOrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceApplicationOrder.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceApplicationOrderUpsert) {
//			SetApplicationID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceApplicationOrderCreateBulk) OnConflict(opts ...sql.ConflictOption) *InvoiceApplicationOrderUpsertBulk {
	_c.conflict = opts
	return &InvoiceApplicationOrderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceApplicationOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceApplicationOrderCreateBulk) OnConflictColumns(columns ...string) *InvoiceApplicationOrderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceApplicationOrderUpsertBulk{
		create: _c,
	}
}

// InvoiceApplicationOrderUpsertBulk is the builder for "upsert"-ing
// a bulk of InvoiceApplicationOrder nodes.
type InvoiceApplicationOrderUpsertBulk struct {
	create *InvoiceApplicationOrderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.InvoiceApplicationOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceApplicationOrderUpsertBulk) UpdateNewValues() *InvoiceApplicationOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(invoiceapplicationorder.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceApplicationOrder.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InvoiceApplicationOrderUpsertBulk) Ignore() *InvoiceApplicationOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceApplicationOrderUpsertBulk) DoNothing() *InvoiceApplicationOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceApplicationOrderCreateBulk.OnConflict
// documentation for more info.
func (u *InvoiceApplicationOrderUpsertBulk) Update(set func(*InvoiceApplicationOrderUpsert)) *InvoiceApplicationOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceApplicationOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetApplicationID sets the "application_id" field.
func (u *InvoiceApplicationOrderUpsertBulk) SetApplicationID(v int64) *InvoiceApplicationOrderUpsertBulk {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.SetApplicationID(v)
	})
}

// UpdateApplicationID sets the "application_id" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsertBulk) UpdateApplicationID() *InvoiceApplicationOrderUpsertBulk {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.UpdateApplicationID()
	})
}

// SetOrderID sets the "order_id" field.
func (u *InvoiceApplicationOrderUpsertBulk) SetOrderID(v int64) *InvoiceApplicationOrderUpsertBulk {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.SetOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsertBulk) UpdateOrderID() *InvoiceApplicationOrderUpsertBulk {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.UpdateOrderID()
	})
}

// SetOrderNo sets the "order_no" field.
func (u *InvoiceApplicationOrderUpsertBulk) SetOrderNo(v string) *InvoiceApplicationOrderUpsertBulk {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.SetOrderNo(v)
	})
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsertBulk) UpdateOrderNo() *InvoiceApplicationOrderUpsertBulk {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.UpdateOrderNo()
	})
}

// SetOrderType sets the "order_type" field.
func (u *InvoiceApplicationOrderUpsertBulk) SetOrderType(v string) *InvoiceApplicationOrderUpsertBulk {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.SetOrderType(v)
	})
}

// UpdateOrderType sets the "order_type" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsertBulk) UpdateOrderType() *InvoiceApplicationOrderUpsertBulk {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.UpdateOrderType()
	})
}

// SetAmount sets the "amount" field.
func (u *InvoiceApplicationOrderUpsertBulk) SetAmount(v float64) *InvoiceApplicationOrderUpsertBulk {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *InvoiceApplicationOrderUpsertBulk) AddAmount(v float64) *InvoiceApplicationOrderUpsertBulk {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsertBulk) UpdateAmount() *InvoiceApplicationOrderUpsertBulk {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.UpdateAmount()
	})
}

// SetPaidAt sets the "paid_at" field.
func (u *InvoiceApplicationOrderUpsertBulk) SetPaidAt(v time.Time) *InvoiceApplicationOrderUpsertBulk {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.SetPaidAt(v)
	})
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsertBulk) UpdatePaidAt() *InvoiceApplicationOrderUpsertBulk {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.UpdatePaidAt()
	})
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *InvoiceApplicationOrderUpsertBulk) ClearPaidAt() *InvoiceApplicationOrderUpsertBulk {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.ClearPaidAt()
	})
}

// Exec executes the query.
func (u *InvoiceApplicationOrderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InvoiceApplicationOrderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceApplicationOrderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceApplicationOrderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
