// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoiceheader"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// InvoiceHeaderUpdate is the builder for updating InvoiceHeader entities.
type InvoiceHeaderUpdate struct {
	config
	hooks    []Hook
	mutation *InvoiceHeaderMutation
}

// Where appends a list predicates to the InvoiceHeaderUpdate builder.
func (_u *InvoiceHeaderUpdate) Where(ps ...predicate.InvoiceHeader) *InvoiceHeaderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *InvoiceHeaderUpdate) SetUserID(v int64) *InvoiceHeaderUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *InvoiceHeaderUpdate) SetNillableUserID(v *int64) *InvoiceHeaderUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTitleType sets the "title_type" field.
func (_u *InvoiceHeaderUpdate) SetTitleType(v string) *InvoiceHeaderUpdate {
	_u.mutation.SetTitleType(v)
	return _u
}

// SetNillableTitleType sets the "title_type" field if the given value is not nil.
func (_u *InvoiceHeaderUpdate) SetNillableTitleType(v *string) *InvoiceHeaderUpdate {
	if v != nil {
		_u.SetTitleType(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *InvoiceHeaderUpdate) SetTitle(v string) *InvoiceHeaderUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *InvoiceHeaderUpdate) SetNillableTitle(v *string) *InvoiceHeaderUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetTaxNumber sets the "tax_number" field.
func (_u *InvoiceHeaderUpdate) SetTaxNumber(v string) *InvoiceHeaderUpdate {
	_u.mutation.SetTaxNumber(v)
	return _u
}

// SetNillableTaxNumber sets the "tax_number" field if the given value is not nil.
func (_u *InvoiceHeaderUpdate) SetNillableTaxNumber(v *string) *InvoiceHeaderUpdate {
	if v != nil {
		_u.SetTaxNumber(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *InvoiceHeaderUpdate) SetEmail(v string) *InvoiceHeaderUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *InvoiceHeaderUpdate) SetNillableEmail(v *string) *InvoiceHeaderUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPhone sets the "phone" field.
func (_u *InvoiceHeaderUpdate) SetPhone(v string) *InvoiceHeaderUpdate {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *InvoiceHeaderUpdate) SetNillablePhone(v *string) *InvoiceHeaderUpdate {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *InvoiceHeaderUpdate) SetAddress(v string) *InvoiceHeaderUpdate {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *InvoiceHeaderUpdate) SetNillableAddress(v *string) *InvoiceHeaderUpdate {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// ClearAddress clears the value of the "address" field.
func (_u *InvoiceHeaderUpdate) ClearAddress() *InvoiceHeaderUpdate {
	_u.mutation.ClearAddress()
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *InvoiceHeaderUpdate) SetIsDefault(v bool) *InvoiceHeaderUpdate {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *InvoiceHeaderUpdate) SetNillableIsDefault(v *bool) *InvoiceHeaderUpdate {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InvoiceHeaderUpdate) SetUpdatedAt(v time.Time) *InvoiceHeaderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *InvoiceHeaderUpdate) SetUser(v *User) *InvoiceHeaderUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the InvoiceHeaderMutation object of the builder.
func (_u *InvoiceHeaderUpdate) Mutation() *InvoiceHeaderMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *InvoiceHeaderUpdate) ClearUser() *InvoiceHeaderUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InvoiceHeaderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceHeaderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InvoiceHeaderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceHeaderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InvoiceHeaderUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := invoiceheader.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceHeaderUpdate) check() error {
	if v, ok := _u.mutation.TitleType(); ok {
		if err := invoiceheader.TitleTypeValidator(v); err != nil {
			return &ValidationError{Name: "title_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceHeader.title_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := invoiceheader.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "InvoiceHeader.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaxNumber(); ok {
		if err := invoiceheader.TaxNumberValidator(v); err != nil {
			return &ValidationError{Name: "tax_number", err: fmt.Errorf(`ent: validator failed for field "InvoiceHeader.tax_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := invoiceheader.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "InvoiceHeader.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Phone(); ok {
		if err := invoiceheader.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "InvoiceHeader.phone": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InvoiceHeader.user"`)
	}
	return nil
}

func (_u *InvoiceHeaderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoiceheader.Table, invoiceheader.Columns, sqlgraph.NewFieldSpec(invoiceheader.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TitleType(); ok {
		_spec.SetField(invoiceheader.FieldTitleType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(invoiceheader.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaxNumber(); ok {
		_spec.SetField(invoiceheader.FieldTaxNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(invoiceheader.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(invoiceheader.FieldPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(invoiceheader.FieldAddress, field.TypeString, value)
	}
	if _u.mutation.AddressCleared() {
		_spec.ClearField(invoiceheader.FieldAddress, field.TypeString)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(invoiceheader.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invoiceheader.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceheader.UserTable,
			Columns: []string{invoiceheader.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceheader.UserTable,
			Columns: []string{invoiceheader.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoiceheader.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InvoiceHeaderUpdateOne is the builder for updating a single InvoiceHeader entity.
type InvoiceHeaderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InvoiceHeaderMutation
}

// SetUserID sets the "user_id" field.
func (_u *InvoiceHeaderUpdateOne) SetUserID(v int64) *InvoiceHeaderUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *InvoiceHeaderUpdateOne) SetNillableUserID(v *int64) *InvoiceHeaderUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTitleType sets the "title_type" field.
func (_u *InvoiceHeaderUpdateOne) SetTitleType(v string) *InvoiceHeaderUpdateOne {
	_u.mutation.SetTitleType(v)
	return _u
}

// SetNillableTitleType sets the "title_type" field if the given value is not nil.
func (_u *InvoiceHeaderUpdateOne) SetNillableTitleType(v *string) *InvoiceHeaderUpdateOne {
	if v != nil {
		_u.SetTitleType(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *InvoiceHeaderUpdateOne) SetTitle(v string) *InvoiceHeaderUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *InvoiceHeaderUpdateOne) SetNillableTitle(v *string) *InvoiceHeaderUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetTaxNumber sets the "tax_number" field.
func (_u *InvoiceHeaderUpdateOne) SetTaxNumber(v string) *InvoiceHeaderUpdateOne {
	_u.mutation.SetTaxNumber(v)
	return _u
}

// SetNillableTaxNumber sets the "tax_number" field if the given value is not nil.
func (_u *InvoiceHeaderUpdateOne) SetNillableTaxNumber(v *string) *InvoiceHeaderUpdateOne {
	if v != nil {
		_u.SetTaxNumber(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *InvoiceHeaderUpdateOne) SetEmail(v string) *InvoiceHeaderUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *InvoiceHeaderUpdateOne) SetNillableEmail(v *string) *InvoiceHeaderUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPhone sets the "phone" field.
func (_u *InvoiceHeaderUpdateOne) SetPhone(v string) *InvoiceHeaderUpdateOne {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *InvoiceHeaderUpdateOne) SetNillablePhone(v *string) *InvoiceHeaderUpdateOne {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *InvoiceHeaderUpdateOne) SetAddress(v string) *InvoiceHeaderUpdateOne {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *InvoiceHeaderUpdateOne) SetNillableAddress(v *string) *InvoiceHeaderUpdateOne {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// ClearAddress clears the value of the "address" field.
func (_u *InvoiceHeaderUpdateOne) ClearAddress() *InvoiceHeaderUpdateOne {
	_u.mutation.ClearAddress()
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *InvoiceHeaderUpdateOne) SetIsDefault(v bool) *InvoiceHeaderUpdateOne {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *InvoiceHeaderUpdateOne) SetNillableIsDefault(v *bool) *InvoiceHeaderUpdateOne {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InvoiceHeaderUpdateOne) SetUpdatedAt(v time.Time) *InvoiceHeaderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *InvoiceHeaderUpdateOne) SetUser(v *User) *InvoiceHeaderUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the InvoiceHeaderMutation object of the builder.
func (_u *InvoiceHeaderUpdateOne) Mutation() *InvoiceHeaderMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *InvoiceHeaderUpdateOne) ClearUser() *InvoiceHeaderUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the InvoiceHeaderUpdate builder.
func (_u *InvoiceHeaderUpdateOne) Where(ps ...predicate.InvoiceHeader) *InvoiceHeaderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InvoiceHeaderUpdateOne) Select(field string, fields ...string) *InvoiceHeaderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InvoiceHeader entity.
func (_u *InvoiceHeaderUpdateOne) Save(ctx context.Context) (*InvoiceHeader, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceHeaderUpdateOne) SaveX(ctx context.Context) *InvoiceHeader {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InvoiceHeaderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceHeaderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InvoiceHeaderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := invoiceheader.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceHeaderUpdateOne) check() error {
	if v, ok := _u.mutation.TitleType(); ok {
		if err := invoiceheader.TitleTypeValidator(v); err != nil {
			return &ValidationError{Name: "title_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceHeader.title_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := invoiceheader.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "InvoiceHeader.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaxNumber(); ok {
		if err := invoiceheader.TaxNumberValidator(v); err != nil {
			return &ValidationError{Name: "tax_number", err: fmt.Errorf(`ent: validator failed for field "InvoiceHeader.tax_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := invoiceheader.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "InvoiceHeader.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Phone(); ok {
		if err := invoiceheader.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "InvoiceHeader.phone": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InvoiceHeader.user"`)
	}
	return nil
}

func (_u *InvoiceHeaderUpdateOne) sqlSave(ctx context.Context) (_node *InvoiceHeader, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoiceheader.Table, invoiceheader.Columns, sqlgraph.NewFieldSpec(invoiceheader.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InvoiceHeader.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invoiceheader.FieldID)
		for _, f := range fields {
			if !invoiceheader.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invoiceheader.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TitleType(); ok {
		_spec.SetField(invoiceheader.FieldTitleType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(invoiceheader.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaxNumber(); ok {
		_spec.SetField(invoiceheader.FieldTaxNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(invoiceheader.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(invoiceheader.FieldPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(invoiceheader.FieldAddress, field.TypeString, value)
	}
	if _u.mutation.AddressCleared() {
		_spec.ClearField(invoiceheader.FieldAddress, field.TypeString)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(invoiceheader.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invoiceheader.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceheader.UserTable,
			Columns: []string{invoiceheader.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceheader.UserTable,
			Columns: []string{invoiceheader.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &InvoiceHeader{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoiceheader.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
