// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoiceapplication"
	"github.com/Wei-Shaw/sub2api/ent/invoiceapplicationorder"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// InvoiceApplicationCreate is the builder for creating a InvoiceApplication entity.
type InvoiceApplicationCreate struct {
	config
	mutation *InvoiceApplicationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *InvoiceApplicationCreate) SetUserID(v int64) *InvoiceApplicationCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *InvoiceApplicationCreate) SetStatus(v string) *InvoiceApplicationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableStatus(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetInvoiceType sets the "invoice_type" field.
func (_c *InvoiceApplicationCreate) SetInvoiceType(v string) *InvoiceApplicationCreate {
	_c.mutation.SetInvoiceType(v)
	return _c
}

// SetNillableInvoiceType sets the "invoice_type" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableInvoiceType(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetInvoiceType(*v)
	}
	return _c
}

// SetHeaderType sets the "header_type" field.
func (_c *InvoiceApplicationCreate) SetHeaderType(v string) *InvoiceApplicationCreate {
	_c.mutation.SetHeaderType(v)
	return _c
}

// SetHeaderTitle sets the "header_title" field.
func (_c *InvoiceApplicationCreate) SetHeaderTitle(v string) *InvoiceApplicationCreate {
	_c.mutation.SetHeaderTitle(v)
	return _c
}

// SetHeaderTaxNumber sets the "header_tax_number" field.
func (_c *InvoiceApplicationCreate) SetHeaderTaxNumber(v string) *InvoiceApplicationCreate {
	_c.mutation.SetHeaderTaxNumber(v)
	return _c
}

// SetNillableHeaderTaxNumber sets the "header_tax_number" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableHeaderTaxNumber(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetHeaderTaxNumber(*v)
	}
	return _c
}

// SetHeaderEmail sets the "header_email" field.
func (_c *InvoiceApplicationCreate) SetHeaderEmail(v string) *InvoiceApplicationCreate {
	_c.mutation.SetHeaderEmail(v)
	return _c
}

// SetNillableHeaderEmail sets the "header_email" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableHeaderEmail(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetHeaderEmail(*v)
	}
	return _c
}

// SetHeaderPhone sets the "header_phone" field.
func (_c *InvoiceApplicationCreate) SetHeaderPhone(v string) *InvoiceApplicationCreate {
	_c.mutation.SetHeaderPhone(v)
	return _c
}

// SetNillableHeaderPhone sets the "header_phone" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableHeaderPhone(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetHeaderPhone(*v)
	}
	return _c
}

// SetHeaderAddress sets the "header_address" field.
func (_c *InvoiceApplicationCreate) SetHeaderAddress(v string) *InvoiceApplicationCreate {
	_c.mutation.SetHeaderAddress(v)
	return _c
}

// SetNillableHeaderAddress sets the "header_address" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableHeaderAddress(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetHeaderAddress(*v)
	}
	return _c
}

// SetTotalAmount sets the "total_amount" field.
func (_c *InvoiceApplicationCreate) SetTotalAmount(v float64) *InvoiceApplicationCreate {
	_c.mutation.SetTotalAmount(v)
	return _c
}

// SetHandledBy sets the "handled_by" field.
func (_c *InvoiceApplicationCreate) SetHandledBy(v int64) *InvoiceApplicationCreate {
	_c.mutation.SetHandledBy(v)
	return _c
}

// SetNillableHandledBy sets the "handled_by" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableHandledBy(v *int64) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetHandledBy(*v)
	}
	return _c
}

// SetRejectionReason sets the "rejection_reason" field.
func (_c *InvoiceApplicationCreate) SetRejectionReason(v string) *InvoiceApplicationCreate {
	_c.mutation.SetRejectionReason(v)
	return _c
}

// SetNillableRejectionReason sets the "rejection_reason" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableRejectionReason(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetRejectionReason(*v)
	}
	return _c
}

// SetAdminNote sets the "admin_note" field.
func (_c *InvoiceApplicationCreate) SetAdminNote(v string) *InvoiceApplicationCreate {
	_c.mutation.SetAdminNote(v)
	return _c
}

// SetNillableAdminNote sets the "admin_note" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableAdminNote(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetAdminNote(*v)
	}
	return _c
}

// SetInvoiceNumber sets the "invoice_number" field.
func (_c *InvoiceApplicationCreate) SetInvoiceNumber(v string) *InvoiceApplicationCreate {
	_c.mutation.SetInvoiceNumber(v)
	return _c
}

// SetNillableInvoiceNumber sets the "invoice_number" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableInvoiceNumber(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetInvoiceNumber(*v)
	}
	return _c
}

// SetProcessedAt sets the "processed_at" field.
func (_c *InvoiceApplicationCreate) SetProcessedAt(v time.Time) *InvoiceApplicationCreate {
	_c.mutation.SetProcessedAt(v)
	return _c
}

// SetNillableProcessedAt sets the "processed_at" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableProcessedAt(v *time.Time) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetProcessedAt(*v)
	}
	return _c
}

// SetInvoicedAt sets the "invoiced_at" field.
func (_c *InvoiceApplicationCreate) SetInvoicedAt(v time.Time) *InvoiceApplicationCreate {
	_c.mutation.SetInvoicedAt(v)
	return _c
}

// SetNillableInvoicedAt sets the "invoiced_at" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableInvoicedAt(v *time.Time) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetInvoicedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InvoiceApplicationCreate) SetCreatedAt(v time.Time) *InvoiceApplicationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableCreatedAt(v *time.Time) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *InvoiceApplicationCreate) SetUpdatedAt(v time.Time) *InvoiceApplicationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableUpdatedAt(v *time.Time) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *InvoiceApplicationCreate) SetUser(v *User) *InvoiceApplicationCreate {
	return _c.SetUserID(v.ID)
}

// AddOrderIDs adds the "orders" edge to the InvoiceApplicationOrder entity by IDs.
func (_c *InvoiceApplicationCreate) AddOrderIDs(ids ...int64) *InvoiceApplicationCreate {
	_c.mutation.AddOrderIDs(ids...)
	return _c
}

// AddOrders adds the "orders" edges to the InvoiceApplicationOrder entity.
func (_c *InvoiceApplicationCreate) AddOrders(v ...*InvoiceApplicationOrder) *InvoiceApplicationCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOrderIDs(ids...)
}

// Mutation returns the InvoiceApplicationMutation object of the builder.
func (_c *InvoiceApplicationCreate) Mutation() *InvoiceApplicationMutation {
	return _c.mutation
}

// Save creates the InvoiceApplication in the database.
func (_c *InvoiceApplicationCreate) Save(ctx context.Context) (*InvoiceApplication, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InvoiceApplicationCreate) SaveX(ctx context.Context) *InvoiceApplication {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceApplicationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceApplicationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InvoiceApplicationCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := invoiceapplication.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.InvoiceType(); !ok {
		v := invoiceapplication.DefaultInvoiceType
		_c.mutation.SetInvoiceType(v)
	}
	if _, ok := _c.mutation.HeaderTaxNumber(); !ok {
		v := invoiceapplication.DefaultHeaderTaxNumber
		_c.mutation.SetHeaderTaxNumber(v)
	}
	if _, ok := _c.mutation.HeaderEmail(); !ok {
		v := invoiceapplication.DefaultHeaderEmail
		_c.mutation.SetHeaderEmail(v)
	}
	if _, ok := _c.mutation.HeaderPhone(); !ok {
		v := invoiceapplication.DefaultHeaderPhone
		_c.mutation.SetHeaderPhone(v)
	}
	if _, ok := _c.mutation.InvoiceNumber(); !ok {
		v := invoiceapplication.DefaultInvoiceNumber
		_c.mutation.SetInvoiceNumber(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := invoiceapplication.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := invoiceapplication.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InvoiceApplicationCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "InvoiceApplication.user_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "InvoiceApplication.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := invoiceapplication.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InvoiceType(); !ok {
		return &ValidationError{Name: "invoice_type", err: errors.New(`ent: missing required field "InvoiceApplication.invoice_type"`)}
	}
	if v, ok := _c.mutation.InvoiceType(); ok {
		if err := invoiceapplication.InvoiceTypeValidator(v); err != nil {
			return &ValidationError{Name: "invoice_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.invoice_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.HeaderType(); !ok {
		return &ValidationError{Name: "header_type", err: errors.New(`ent: missing required field "InvoiceApplication.header_type"`)}
	}
	if v, ok := _c.mutation.HeaderType(); ok {
		if err := invoiceapplication.HeaderTypeValidator(v); err != nil {
			return &ValidationError{Name: "header_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.header_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.HeaderTitle(); !ok {
		return &ValidationError{Name: "header_title", err: errors.New(`ent: missing required field "InvoiceApplication.header_title"`)}
	}
	if v, ok := _c.mutation.HeaderTitle(); ok {
		if err := invoiceapplication.HeaderTitleValidator(v); err != nil {
			return &ValidationError{Name: "header_title", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.header_title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.HeaderTaxNumber(); !ok {
		return &ValidationError{Name: "header_tax_number", err: errors.New(`ent: missing required field "InvoiceApplication.header_tax_number"`)}
	}
	if v, ok := _c.mutation.HeaderTaxNumber(); ok {
		if err := invoiceapplication.HeaderTaxNumberValidator(v); err != nil {
			return &ValidationError{Name: "header_tax_number", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.header_tax_number": %w`, err)}
		}
	}
	if _, ok := _c.mutation.HeaderEmail(); !ok {
		return &ValidationError{Name: "header_email", err: errors.New(`ent: missing required field "InvoiceApplication.header_email"`)}
	}
	if v, ok := _c.mutation.HeaderEmail(); ok {
		if err := invoiceapplication.HeaderEmailValidator(v); err != nil {
			return &ValidationError{Name: "header_email", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.header_email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.HeaderPhone(); !ok {
		return &ValidationError{Name: "header_phone", err: errors.New(`ent: missing required field "InvoiceApplication.header_phone"`)}
	}
	if v, ok := _c.mutation.HeaderPhone(); ok {
		if err := invoiceapplication.HeaderPhoneValidator(v); err != nil {
			return &ValidationError{Name: "header_phone", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.header_phone": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TotalAmount(); !ok {
		return &ValidationError{Name: "total_amount", err: errors.New(`ent: missing required field "InvoiceApplication.total_amount"`)}
	}
	if _, ok := _c.mutation.InvoiceNumber(); !ok {
		return &ValidationError{Name: "invoice_number", err: errors.New(`ent: missing required field "InvoiceApplication.invoice_number"`)}
	}
	if v, ok := _c.mutation.InvoiceNumber(); ok {
		if err := invoiceapplication.InvoiceNumberValidator(v); err != nil {
			return &ValidationError{Name: "invoice_number", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.invoice_number": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "InvoiceApplication.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "InvoiceApplication.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "InvoiceApplication.user"`)}
	}
	return nil
}

func (_c *InvoiceApplicationCreate) sqlSave(ctx context.Context) (*InvoiceApplication, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InvoiceApplicationCreate) createSpec() (*InvoiceApplication, *sqlgraph.CreateSpec) {
	var (
		_node = &InvoiceApplication{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(invoiceapplication.Table, sqlgraph.NewFieldSpec(invoiceapplication.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(invoiceapplication.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.InvoiceType(); ok {
		_spec.SetField(invoiceapplication.FieldInvoiceType, field.TypeString, value)
		_node.InvoiceType = value
	}
	if value, ok := _c.mutation.HeaderType(); ok {
		_spec.SetField(invoiceapplication.FieldHeaderType, field.TypeString, value)
		_node.HeaderType = value
	}
	if value, ok := _c.mutation.HeaderTitle(); ok {
		_spec.SetField(invoiceapplication.FieldHeaderTitle, field.TypeString, value)
		_node.HeaderTitle = value
	}
	if value, ok := _c.mutation.HeaderTaxNumber(); ok {
		_spec.SetField(invoiceapplication.FieldHeaderTaxNumber, field.TypeString, value)
		_node.HeaderTaxNumber = value
	}
	if value, ok := _c.mutation.HeaderEmail(); ok {
		_spec.SetField(invoiceapplication.FieldHeaderEmail, field.TypeString, value)
		_node.HeaderEmail = value
	}
	if value, ok := _c.mutation.HeaderPhone(); ok {
		_spec.SetField(invoiceapplication.FieldHeaderPhone, field.TypeString, value)
		_node.HeaderPhone = value
	}
	if value, ok := _c.mutation.HeaderAddress(); ok {
		_spec.SetField(invoiceapplication.FieldHeaderAddress, field.TypeString, value)
		_node.HeaderAddress = &value
	}
	if value, ok := _c.mutation.TotalAmount(); ok {
		_spec.SetField(invoiceapplication.FieldTotalAmount, field.TypeFloat64, value)
		_node.TotalAmount = value
	}
	if value, ok := _c.mutation.HandledBy(); ok {
		_spec.SetField(invoiceapplication.FieldHandledBy, field.TypeInt64, value)
		_node.HandledBy = &value
	}
	if value, ok := _c.mutation.RejectionReason(); ok {
		_spec.SetField(invoiceapplication.FieldRejectionReason, field.TypeString, value)
		_node.RejectionReason = &value
	}
	if value, ok := _c.mutation.AdminNote(); ok {
		_spec.SetField(invoiceapplication.FieldAdminNote, field.TypeString, value)
		_node.AdminNote = &value
	}
	if value, ok := _c.mutation.InvoiceNumber(); ok {
		_spec.SetField(invoiceapplication.FieldInvoiceNumber, field.TypeString, value)
		_node.InvoiceNumber = value
	}
	if value, ok := _c.mutation.ProcessedAt(); ok {
		_spec.SetField(invoiceapplication.FieldProcessedAt, field.TypeTime, value)
		_node.ProcessedAt = &value
	}
	if value, ok := _c.mutation.InvoicedAt(); ok {
		_spec.SetField(invoiceapplication.FieldInvoicedAt, field.TypeTime, value)
		_node.InvoicedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(invoiceapplication.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(invoiceapplication.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceapplication.UserTable,
			Columns: []string{invoiceapplication.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoiceapplication.OrdersTable,
			Columns: []string{invoiceapplication.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceapplicationorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceApplication.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceApplicationUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceApplicationCreate) OnConflict(opts ...sql.ConflictOption) *InvoiceApplicationUpsertOne {
	_c.conflict = opts
	return &InvoiceApplicationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceApplication.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceApplicationCreate) OnConflictColumns(columns ...string) *InvoiceApplicationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceApplicationUpsertOne{
		create: _c,
	}
}

type (
	// InvoiceApplicationUpsertOne is the builder for "upsert"-ing
	//  one InvoiceApplication node.
	InvoiceApplicationUpsertOne struct {
		create *InvoiceApplicationCreate
	}

	// InvoiceApplicationUpsert is the "OnConflict" setter.
	InvoiceApplicationUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *InvoiceApplicationUpsert) SetUserID(v int64) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateUserID() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldUserID)
	return u
}

// SetStatus sets the "status" field.
func (u *InvoiceApplicationUpsert) SetStatus(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateStatus() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldStatus)
	return u
}

// SetInvoiceType sets the "invoice_type" field.
func (u *InvoiceApplicationUpsert) SetInvoiceType(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldInvoiceType, v)
	return u
}

// UpdateInvoiceType sets the "invoice_type" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateInvoiceType() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldInvoiceType)
	return u
}

// SetHeaderType sets the "header_type" field.
func (u *InvoiceApplicationUpsert) SetHeaderType(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldHeaderType, v)
	return u
}

// UpdateHeaderType sets the "header_type" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateHeaderType() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldHeaderType)
	return u
}

// SetHeaderTitle sets the "header_title" field.
func (u *InvoiceApplicationUpsert) SetHeaderTitle(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldHeaderTitle, v)
	return u
}

// UpdateHeaderTitle sets the "header_title" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateHeaderTitle() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldHeaderTitle)
	return u
}

// SetHeaderTaxNumber sets the "header_tax_number" field.
func (u *InvoiceApplicationUpsert) SetHeaderTaxNumber(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldHeaderTaxNumber, v)
	return u
}

// UpdateHeaderTaxNumber sets the "header_tax_number" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateHeaderTaxNumber() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldHeaderTaxNumber)
	return u
}

// SetHeaderEmail sets the "header_email" field.
func (u *InvoiceApplicationUpsert) SetHeaderEmail(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldHeaderEmail, v)
	return u
}

// UpdateHeaderEmail sets the "header_email" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateHeaderEmail() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldHeaderEmail)
	return u
}

// SetHeaderPhone sets the "header_phone" field.
func (u *InvoiceApplicationUpsert) SetHeaderPhone(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldHeaderPhone, v)
	return u
}

// UpdateHeaderPhone sets the "header_phone" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateHeaderPhone() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldHeaderPhone)
	return u
}

// SetHeaderAddress sets the "header_address" field.
func (u *InvoiceApplicationUpsert) SetHeaderAddress(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldHeaderAddress, v)
	return u
}

// UpdateHeaderAddress sets the "header_address" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateHeaderAddress() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldHeaderAddress)
	return u
}

// ClearHeaderAddress clears the value of the "header_address" field.
func (u *InvoiceApplicationUpsert) ClearHeaderAddress() *InvoiceApplicationUpsert {
	u.SetNull(invoiceapplication.FieldHeaderAddress)
	return u
}

// SetTotalAmount sets the "total_amount" field.
func (u *InvoiceApplicationUpsert) SetTotalAmount(v float64) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldTotalAmount, v)
	return u
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateTotalAmount() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldTotalAmount)
	return u
}

// AddTotalAmount adds v to the "total_amount" field.
func (u *InvoiceApplicationUpsert) AddTotalAmount(v float64) *InvoiceApplicationUpsert {
	u.Add(invoiceapplication.FieldTotalAmount, v)
	return u
}

// SetHandledBy sets the "handled_by" field.
func (u *InvoiceApplicationUpsert) SetHandledBy(v int64) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldHandledBy, v)
	return u
}

// UpdateHandledBy sets the "handled_by" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateHandledBy() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldHandledBy)
	return u
}

// AddHandledBy adds v to the "handled_by" field.
func (u *InvoiceApplicationUpsert) AddHandledBy(v int64) *InvoiceApplicationUpsert {
	u.Add(invoiceapplication.FieldHandledBy, v)
	return u
}

// ClearHandledBy clears the value of the "handled_by" field.
func (u *InvoiceApplicationUpsert) ClearHandledBy() *InvoiceApplicationUpsert {
	u.SetNull(invoiceapplication.FieldHandledBy)
	return u
}

// SetRejectionReason sets the "rejection_reason" field.
func (u *InvoiceApplicationUpsert) SetRejectionReason(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldRejectionReason, v)
	return u
}

// UpdateRejectionReason sets the "rejection_reason" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateRejectionReason() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldRejectionReason)
	return u
}

// ClearRejectionReason clears the value of the "rejection_reason" field.
func (u *InvoiceApplicationUpsert) ClearRejectionReason() *InvoiceApplicationUpsert {
	u.SetNull(invoiceapplication.FieldRejectionReason)
	return u
}

// SetAdminNote sets the "admin_note" field.
func (u *InvoiceApplicationUpsert) SetAdminNote(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldAdminNote, v)
	return u
}

// UpdateAdminNote sets the "admin_note" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateAdminNote() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldAdminNote)
	return u
}

// ClearAdminNote clears the value of the "admin_note" field.
func (u *InvoiceApplicationUpsert) ClearAdminNote() *InvoiceApplicationUpsert {
	u.SetNull(invoiceapplication.FieldAdminNote)
	return u
}

// SetInvoiceNumber sets the "invoice_number" field.
func (u *InvoiceApplicationUpsert) SetInvoiceNumber(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldInvoiceNumber, v)
	return u
}

// UpdateInvoiceNumber sets the "invoice_number" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateInvoiceNumber() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldInvoiceNumber)
	return u
}

// SetProcessedAt sets the "processed_at" field.
func (u *InvoiceApplicationUpsert) SetProcessedAt(v time.Time) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldProcessedAt, v)
	return u
}

// UpdateProcessedAt sets the "processed_at" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateProcessedAt() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldProcessedAt)
	return u
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (u *InvoiceApplicationUpsert) ClearProcessedAt() *InvoiceApplicationUpsert {
	u.SetNull(invoiceapplication.FieldProcessedAt)
	return u
}

// SetInvoicedAt sets the "invoiced_at" field.
func (u *InvoiceApplicationUpsert) SetInvoicedAt(v time.Time) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldInvoicedAt, v)
	return u
}

// UpdateInvoicedAt sets the "invoiced_at" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateInvoicedAt() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldInvoicedAt)
	return u
}

// ClearInvoicedAt clears the value of the "invoiced_at" field.
func (u *InvoiceApplicationUpsert) ClearInvoicedAt() *InvoiceApplicationUpsert {
	u.SetNull(invoiceapplication.FieldInvoicedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceApplicationUpsert) SetUpdatedAt(v time.Time) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateUpdatedAt() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.InvoiceApplication.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceApplicationUpsertOne) UpdateNewValues() *InvoiceApplicationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(invoiceapplication.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceApplication.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InvoiceApplicationUpsertOne) Ignore() *InvoiceApplicationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceApplicationUpsertOne) DoNothing() *InvoiceApplicationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceApplicationCreate.OnConflict
// documentation for more info.
func (u *InvoiceApplicationUpsertOne) Update(set func(*InvoiceApplicationUpsert)) *InvoiceApplicationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceApplicationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *InvoiceApplicationUpsertOne) SetUserID(v int64) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateUserID() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateUserID()
	})
}

// SetStatus sets the "status" field.
func (u *InvoiceApplicationUpsertOne) SetStatus(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateStatus() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateStatus()
	})
}

// SetInvoiceType sets the "invoice_type" field.
func (u *InvoiceApplicationUpsertOne) SetInvoiceType(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetInvoiceType(v)
	})
}

// UpdateInvoiceType sets the "invoice_type" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateInvoiceType() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateInvoiceType()
	})
}

// SetHeaderType sets the "header_type" field.
func (u *InvoiceApplicationUpsertOne) SetHeaderType(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetHeaderType(v)
	})
}

// UpdateHeaderType sets the "header_type" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateHeaderType() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateHeaderType()
	})
}

// SetHeaderTitle sets the "header_title" field.
func (u *InvoiceApplicationUpsertOne) SetHeaderTitle(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetHeaderTitle(v)
	})
}

// UpdateHeaderTitle sets the "header_title" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateHeaderTitle() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateHeaderTitle()
	})
}

// SetHeaderTaxNumber sets the "header_tax_number" field.
func (u *InvoiceApplicationUpsertOne) SetHeaderTaxNumber(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetHeaderTaxNumber(v)
	})
}

// UpdateHeaderTaxNumber sets the "header_tax_number" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateHeaderTaxNumber() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateHeaderTaxNumber()
	})
}

// SetHeaderEmail sets the "header_email" field.
func (u *InvoiceApplicationUpsertOne) SetHeaderEmail(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetHeaderEmail(v)
	})
}

// UpdateHeaderEmail sets the "header_email" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateHeaderEmail() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateHeaderEmail()
	})
}

// SetHeaderPhone sets the "header_phone" field.
func (u *InvoiceApplicationUpsertOne) SetHeaderPhone(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetHeaderPhone(v)
	})
}

// UpdateHeaderPhone sets the "header_phone" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateHeaderPhone() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateHeaderPhone()
	})
}

// SetHeaderAddress sets the "header_address" field.
func (u *InvoiceApplicationUpsertOne) SetHeaderAddress(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetHeaderAddress(v)
	})
}

// UpdateHeaderAddress sets the "header_address" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateHeaderAddress() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateHeaderAddress()
	})
}

// ClearHeaderAddress clears the value of the "header_address" field.
func (u *InvoiceApplicationUpsertOne) ClearHeaderAddress() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearHeaderAddress()
	})
}

// SetTotalAmount sets the "total_amount" field.
func (u *InvoiceApplicationUpsertOne) SetTotalAmount(v float64) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetTotalAmount(v)
	})
}

// AddTotalAmount adds v to the "total_amount" field.
func (u *InvoiceApplicationUpsertOne) AddTotalAmount(v float64) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.AddTotalAmount(v)
	})
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateTotalAmount() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateTotalAmount()
	})
}

// SetHandledBy sets the "handled_by" field.
func (u *InvoiceApplicationUpsertOne) SetHandledBy(v int64) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetHandledBy(v)
	})
}

// AddHandledBy adds v to the "handled_by" field.
func (u *InvoiceApplicationUpsertOne) AddHandledBy(v int64) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.AddHandledBy(v)
	})
}

// UpdateHandledBy sets the "handled_by" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateHandledBy() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateHandledBy()
	})
}

// ClearHandledBy clears the value of the "handled_by" field.
func (u *InvoiceApplicationUpsertOne) ClearHandledBy() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearHandledBy()
	})
}

// SetRejectionReason sets the "rejection_reason" field.
func (u *InvoiceApplicationUpsertOne) SetRejectionReason(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetRejectionReason(v)
	})
}

// UpdateRejectionReason sets the "rejection_reason" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateRejectionReason() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateRejectionReason()
	})
}

// ClearRejectionReason clears the value of the "rejection_reason" field.
func (u *InvoiceApplicationUpsertOne) ClearRejectionReason() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearRejectionReason()
	})
}

// SetAdminNote sets the "admin_note" field.
func (u *InvoiceApplicationUpsertOne) SetAdminNote(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetAdminNote(v)
	})
}

// UpdateAdminNote sets the "admin_note" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateAdminNote() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateAdminNote()
	})
}

// ClearAdminNote clears the value of the "admin_note" field.
func (u *InvoiceApplicationUpsertOne) ClearAdminNote() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearAdminNote()
	})
}

// SetInvoiceNumber sets the "invoice_number" field.
func (u *InvoiceApplicationUpsertOne) SetInvoiceNumber(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetInvoiceNumber(v)
	})
}

// UpdateInvoiceNumber sets the "invoice_number" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateInvoiceNumber() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateInvoiceNumber()
	})
}

// SetProcessedAt sets the "processed_at" field.
func (u *InvoiceApplicationUpsertOne) SetProcessedAt(v time.Time) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetProcessedAt(v)
	})
}

// UpdateProcessedAt sets the "processed_at" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateProcessedAt() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateProcessedAt()
	})
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (u *InvoiceApplicationUpsertOne) ClearProcessedAt() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearProcessedAt()
	})
}

// SetInvoicedAt sets the "invoiced_at" field.
func (u *InvoiceApplicationUpsertOne) SetInvoicedAt(v time.Time) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetInvoicedAt(v)
	})
}

// UpdateInvoicedAt sets the "invoiced_at" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateInvoicedAt() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateInvoicedAt()
	})
}

// ClearInvoicedAt clears the value of the "invoiced_at" field.
func (u *InvoiceApplicationUpsertOne) ClearInvoicedAt() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearInvoicedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceApplicationUpsertOne) SetUpdatedAt(v time.Time) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateUpdatedAt() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *InvoiceApplicationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceApplicationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceApplicationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InvoiceApplicationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InvoiceApplicationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InvoiceApplicationCreateBulk is the builder for creating many InvoiceApplication entities in bulk.
type InvoiceApplicationCreateBulk struct {
	config
	err      error
	builders []*InvoiceApplicationCreate
	conflict []sql.ConflictOption
}

// Save creates the InvoiceApplication entities in the database.
func (_c *InvoiceApplicationCreateBulk) Save(ctx context.Context) ([]*InvoiceApplication, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InvoiceApplication, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InvoiceApplicationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InvoiceApplicationCreateBulk) SaveX(ctx context.Context) []*InvoiceApplication {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceApplicationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceApplicationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceApplication.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceApplicationUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceApplicationCreateBulk) OnConflict(opts ...sql.ConflictOption) *InvoiceApplicationUpsertBulk {
	_c.conflict = opts
	return &InvoiceApplicationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceApplication.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceApplicationCreateBulk) OnConflictColumns(columns ...string) *InvoiceApplicationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceApplicationUpsertBulk{
		create: _c,
	}
}

// InvoiceApplicationUpsertBulk is the builder for "upsert"-ing
// a bulk of InvoiceApplication nodes.
type InvoiceApplicationUpsertBulk struct {
	create *InvoiceApplicationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.InvoiceApplication.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceApplicationUpsertBulk) UpdateNewValues() *InvoiceApplicationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(invoiceapplication.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceApplication.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InvoiceApplicationUpsertBulk) Ignore() *InvoiceApplicationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceApplicationUpsertBulk) DoNothing() *InvoiceApplicationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceApplicationCreateBulk.OnConflict
// documentation for more info.
func (u *InvoiceApplicationUpsertBulk) Update(set func(*InvoiceApplicationUpsert)) *InvoiceApplicationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceApplicationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *InvoiceApplicationUpsertBulk) SetUserID(v int64) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateUserID() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateUserID()
	})
}

// SetStatus sets the "status" field.
func (u *InvoiceApplicationUpsertBulk) SetStatus(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateStatus() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateStatus()
	})
}

// SetInvoiceType sets the "invoice_type" field.
func (u *InvoiceApplicationUpsertBulk) SetInvoiceType(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetInvoiceType(v)
	})
}

// UpdateInvoiceType sets the "invoice_type" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateInvoiceType() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateInvoiceType()
	})
}

// SetHeaderType sets the "header_type" field.
func (u *InvoiceApplicationUpsertBulk) SetHeaderType(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetHeaderType(v)
	})
}

// UpdateHeaderType sets the "header_type" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateHeaderType() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateHeaderType()
	})
}

// SetHeaderTitle sets the "header_title" field.
func (u *InvoiceApplicationUpsertBulk) SetHeaderTitle(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetHeaderTitle(v)
	})
}

// UpdateHeaderTitle sets the "header_title" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateHeaderTitle() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateHeaderTitle()
	})
}

// SetHeaderTaxNumber sets the "header_tax_number" field.
func (u *InvoiceApplicationUpsertBulk) SetHeaderTaxNumber(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetHeaderTaxNumber(v)
	})
}

// UpdateHeaderTaxNumber sets the "header_tax_number" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateHeaderTaxNumber() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateHeaderTaxNumber()
	})
}

// SetHeaderEmail sets the "header_email" field.
func (u *InvoiceApplicationUpsertBulk) SetHeaderEmail(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetHeaderEmail(v)
	})
}

// UpdateHeaderEmail sets the "header_email" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateHeaderEmail() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateHeaderEmail()
	})
}

// SetHeaderPhone sets the "header_phone" field.
func (u *InvoiceApplicationUpsertBulk) SetHeaderPhone(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetHeaderPhone(v)
	})
}

// UpdateHeaderPhone sets the "header_phone" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateHeaderPhone() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateHeaderPhone()
	})
}

// SetHeaderAddress sets the "header_address" field.
func (u *InvoiceApplicationUpsertBulk) SetHeaderAddress(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetHeaderAddress(v)
	})
}

// UpdateHeaderAddress sets the "header_address" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateHeaderAddress() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateHeaderAddress()
	})
}

// ClearHeaderAddress clears the value of the "header_address" field.
func (u *InvoiceApplicationUpsertBulk) ClearHeaderAddress() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearHeaderAddress()
	})
}

// SetTotalAmount sets the "total_amount" field.
func (u *InvoiceApplicationUpsertBulk) SetTotalAmount(v float64) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetTotalAmount(v)
	})
}

// AddTotalAmount adds v to the "total_amount" field.
func (u *InvoiceApplicationUpsertBulk) AddTotalAmount(v float64) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.AddTotalAmount(v)
	})
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateTotalAmount() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateTotalAmount()
	})
}

// SetHandledBy sets the "handled_by" field.
func (u *InvoiceApplicationUpsertBulk) SetHandledBy(v int64) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetHandledBy(v)
	})
}

// AddHandledBy adds v to the "handled_by" field.
func (u *InvoiceApplicationUpsertBulk) AddHandledBy(v int64) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.AddHandledBy(v)
	})
}

// UpdateHandledBy sets the "handled_by" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateHandledBy() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateHandledBy()
	})
}

// ClearHandledBy clears the value of the "handled_by" field.
func (u *InvoiceApplicationUpsertBulk) ClearHandledBy() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearHandledBy()
	})
}

// SetRejectionReason sets the "rejection_reason" field.
func (u *InvoiceApplicationUpsertBulk) SetRejectionReason(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetRejectionReason(v)
	})
}

// UpdateRejectionReason sets the "rejection_reason" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateRejectionReason() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateRejectionReason()
	})
}

// ClearRejectionReason clears the value of the "rejection_reason" field.
func (u *InvoiceApplicationUpsertBulk) ClearRejectionReason() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearRejectionReason()
	})
}

// SetAdminNote sets the "admin_note" field.
func (u *InvoiceApplicationUpsertBulk) SetAdminNote(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetAdminNote(v)
	})
}

// UpdateAdminNote sets the "admin_note" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateAdminNote() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateAdminNote()
	})
}

// ClearAdminNote clears the value of the "admin_note" field.
func (u *InvoiceApplicationUpsertBulk) ClearAdminNote() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearAdminNote()
	})
}

// SetInvoiceNumber sets the "invoice_number" field.
func (u *InvoiceApplicationUpsertBulk) SetInvoiceNumber(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetInvoiceNumber(v)
	})
}

// UpdateInvoiceNumber sets the "invoice_number" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateInvoiceNumber() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateInvoiceNumber()
	})
}

// SetProcessedAt sets the "processed_at" field.
func (u *InvoiceApplicationUpsertBulk) SetProcessedAt(v time.Time) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetProcessedAt(v)
	})
}

// UpdateProcessedAt sets the "processed_at" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateProcessedAt() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateProcessedAt()
	})
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (u *InvoiceApplicationUpsertBulk) ClearProcessedAt() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearProcessedAt()
	})
}

// SetInvoicedAt sets the "invoiced_at" field.
func (u *InvoiceApplicationUpsertBulk) SetInvoicedAt(v time.Time) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetInvoicedAt(v)
	})
}

// UpdateInvoicedAt sets the "invoiced_at" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateInvoicedAt() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateInvoicedAt()
	})
}

// ClearInvoicedAt clears the value of the "invoiced_at" field.
func (u *InvoiceApplicationUpsertBulk) ClearInvoicedAt() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearInvoicedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceApplicationUpsertBulk) SetUpdatedAt(v time.Time) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateUpdatedAt() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *InvoiceApplicationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InvoiceApplicationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceApplicationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceApplicationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
