// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoiceapplication"
	"github.com/Wei-Shaw/sub2api/ent/invoiceapplicationorder"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// InvoiceApplicationUpdate is the builder for updating InvoiceApplication entities.
type InvoiceApplicationUpdate struct {
	config
	hooks    []Hook
	mutation *InvoiceApplicationMutation
}

// Where appends a list predicates to the InvoiceApplicationUpdate builder.
func (_u *InvoiceApplicationUpdate) Where(ps ...predicate.InvoiceApplication) *InvoiceApplicationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *InvoiceApplicationUpdate) SetUserID(v int64) *InvoiceApplicationUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableUserID(v *int64) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *InvoiceApplicationUpdate) SetStatus(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableStatus(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetInvoiceType sets the "invoice_type" field.
func (_u *InvoiceApplicationUpdate) SetInvoiceType(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetInvoiceType(v)
	return _u
}

// SetNillableInvoiceType sets the "invoice_type" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableInvoiceType(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetInvoiceType(*v)
	}
	return _u
}

// SetHeaderType sets the "header_type" field.
func (_u *InvoiceApplicationUpdate) SetHeaderType(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetHeaderType(v)
	return _u
}

// SetNillableHeaderType sets the "header_type" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableHeaderType(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetHeaderType(*v)
	}
	return _u
}

// SetHeaderTitle sets the "header_title" field.
func (_u *InvoiceApplicationUpdate) SetHeaderTitle(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetHeaderTitle(v)
	return _u
}

// SetNillableHeaderTitle sets the "header_title" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableHeaderTitle(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetHeaderTitle(*v)
	}
	return _u
}

// SetHeaderTaxNumber sets the "header_tax_number" field.
func (_u *InvoiceApplicationUpdate) SetHeaderTaxNumber(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetHeaderTaxNumber(v)
	return _u
}

// SetNillableHeaderTaxNumber sets the "header_tax_number" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableHeaderTaxNumber(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetHeaderTaxNumber(*v)
	}
	return _u
}

// SetHeaderEmail sets the "header_email" field.
func (_u *InvoiceApplicationUpdate) SetHeaderEmail(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetHeaderEmail(v)
	return _u
}

// SetNillableHeaderEmail sets the "header_email" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableHeaderEmail(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetHeaderEmail(*v)
	}
	return _u
}

// SetHeaderPhone sets the "header_phone" field.
func (_u *InvoiceApplicationUpdate) SetHeaderPhone(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetHeaderPhone(v)
	return _u
}

// SetNillableHeaderPhone sets the "header_phone" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableHeaderPhone(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetHeaderPhone(*v)
	}
	return _u
}

// SetHeaderAddress sets the "header_address" field.
func (_u *InvoiceApplicationUpdate) SetHeaderAddress(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetHeaderAddress(v)
	return _u
}

// SetNillableHeaderAddress sets the "header_address" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableHeaderAddress(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetHeaderAddress(*v)
	}
	return _u
}

// ClearHeaderAddress clears the value of the "header_address" field.
func (_u *InvoiceApplicationUpdate) ClearHeaderAddress() *InvoiceApplicationUpdate {
	_u.mutation.ClearHeaderAddress()
	return _u
}

// SetTotalAmount sets the "total_amount" field.
func (_u *InvoiceApplicationUpdate) SetTotalAmount(v float64) *InvoiceApplicationUpdate {
	_u.mutation.ResetTotalAmount()
	_u.mutation.SetTotalAmount(v)
	return _u
}

// SetNillableTotalAmount sets the "total_amount" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableTotalAmount(v *float64) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetTotalAmount(*v)
	}
	return _u
}

// AddTotalAmount adds value to the "total_amount" field.
func (_u *InvoiceApplicationUpdate) AddTotalAmount(v float64) *InvoiceApplicationUpdate {
	_u.mutation.AddTotalAmount(v)
	return _u
}

// SetHandledBy sets the "handled_by" field.
func (_u *InvoiceApplicationUpdate) SetHandledBy(v int64) *InvoiceApplicationUpdate {
	_u.mutation.ResetHandledBy()
	_u.mutation.SetHandledBy(v)
	return _u
}

// SetNillableHandledBy sets the "handled_by" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableHandledBy(v *int64) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetHandledBy(*v)
	}
	return _u
}

// AddHandledBy adds value to the "handled_by" field.
func (_u *InvoiceApplicationUpdate) AddHandledBy(v int64) *InvoiceApplicationUpdate {
	_u.mutation.AddHandledBy(v)
	return _u
}

// ClearHandledBy clears the value of the "handled_by" field.
func (_u *InvoiceApplicationUpdate) ClearHandledBy() *InvoiceApplicationUpdate {
	_u.mutation.ClearHandledBy()
	return _u
}

// SetRejectionReason sets the "rejection_reason" field.
func (_u *InvoiceApplicationUpdate) SetRejectionReason(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetRejectionReason(v)
	return _u
}

// SetNillableRejectionReason sets the "rejection_reason" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableRejectionReason(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetRejectionReason(*v)
	}
	return _u
}

// ClearRejectionReason clears the value of the "rejection_reason" field.
func (_u *InvoiceApplicationUpdate) ClearRejectionReason() *InvoiceApplicationUpdate {
	_u.mutation.ClearRejectionReason()
	return _u
}

// SetAdminNote sets the "admin_note" field.
func (_u *InvoiceApplicationUpdate) SetAdminNote(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetAdminNote(v)
	return _u
}

// SetNillableAdminNote sets the "admin_note" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableAdminNote(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetAdminNote(*v)
	}
	return _u
}

// ClearAdminNote clears the value of the "admin_note" field.
func (_u *InvoiceApplicationUpdate) ClearAdminNote() *InvoiceApplicationUpdate {
	_u.mutation.ClearAdminNote()
	return _u
}

// SetInvoiceNumber sets the "invoice_number" field.
func (_u *InvoiceApplicationUpdate) SetInvoiceNumber(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetInvoiceNumber(v)
	return _u
}

// SetNillableInvoiceNumber sets the "invoice_number" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableInvoiceNumber(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetInvoiceNumber(*v)
	}
	return _u
}

// SetProcessedAt sets the "processed_at" field.
func (_u *InvoiceApplicationUpdate) SetProcessedAt(v time.Time) *InvoiceApplicationUpdate {
	_u.mutation.SetProcessedAt(v)
	return _u
}

// SetNillableProcessedAt sets the "processed_at" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableProcessedAt(v *time.Time) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetProcessedAt(*v)
	}
	return _u
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (_u *InvoiceApplicationUpdate) ClearProcessedAt() *InvoiceApplicationUpdate {
	_u.mutation.ClearProcessedAt()
	return _u
}

// SetInvoicedAt sets the "invoiced_at" field.
func (_u *InvoiceApplicationUpdate) SetInvoicedAt(v time.Time) *InvoiceApplicationUpdate {
	_u.mutation.SetInvoicedAt(v)
	return _u
}

// SetNillableInvoicedAt sets the "invoiced_at" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableInvoicedAt(v *time.Time) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetInvoicedAt(*v)
	}
	return _u
}

// ClearInvoicedAt clears the value of the "invoiced_at" field.
func (_u *InvoiceApplicationUpdate) ClearInvoicedAt() *InvoiceApplicationUpdate {
	_u.mutation.ClearInvoicedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InvoiceApplicationUpdate) SetUpdatedAt(v time.Time) *InvoiceApplicationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *InvoiceApplicationUpdate) SetUser(v *User) *InvoiceApplicationUpdate {
	return _u.SetUserID(v.ID)
}

// AddOrderIDs adds the "orders" edge to the InvoiceApplicationOrder entity by IDs.
func (_u *InvoiceApplicationUpdate) AddOrderIDs(ids ...int64) *InvoiceApplicationUpdate {
	_u.mutation.AddOrderIDs(ids...)
	return _u
}

// AddOrders adds the "orders" edges to the InvoiceApplicationOrder entity.
func (_u *InvoiceApplicationUpdate) AddOrders(v ...*InvoiceApplicationOrder) *InvoiceApplicationUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOrderIDs(ids...)
}

// Mutation returns the InvoiceApplicationMutation object of the builder.
func (_u *InvoiceApplicationUpdate) Mutation() *InvoiceApplicationMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *InvoiceApplicationUpdate) ClearUser() *InvoiceApplicationUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearOrders clears all "orders" edges to the InvoiceApplicationOrder entity.
func (_u *InvoiceApplicationUpdate) ClearOrders() *InvoiceApplicationUpdate {
	_u.mutation.ClearOrders()
	return _u
}

// RemoveOrderIDs removes the "orders" edge to InvoiceApplicationOrder entities by IDs.
func (_u *InvoiceApplicationUpdate) RemoveOrderIDs(ids ...int64) *InvoiceApplicationUpdate {
	_u.mutation.RemoveOrderIDs(ids...)
	return _u
}

// RemoveOrders removes "orders" edges to InvoiceApplicationOrder entities.
func (_u *InvoiceApplicationUpdate) RemoveOrders(v ...*InvoiceApplicationOrder) *InvoiceApplicationUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOrderIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InvoiceApplicationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceApplicationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InvoiceApplicationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceApplicationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InvoiceApplicationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := invoiceapplication.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceApplicationUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := invoiceapplication.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InvoiceType(); ok {
		if err := invoiceapplication.InvoiceTypeValidator(v); err != nil {
			return &ValidationError{Name: "invoice_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.invoice_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HeaderType(); ok {
		if err := invoiceapplication.HeaderTypeValidator(v); err != nil {
			return &ValidationError{Name: "header_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.header_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HeaderTitle(); ok {
		if err := invoiceapplication.HeaderTitleValidator(v); err != nil {
			return &ValidationError{Name: "header_title", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.header_title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HeaderTaxNumber(); ok {
		if err := invoiceapplication.HeaderTaxNumberValidator(v); err != nil {
			return &ValidationError{Name: "header_tax_number", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.header_tax_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HeaderEmail(); ok {
		if err := invoiceapplication.HeaderEmailValidator(v); err != nil {
			return &ValidationError{Name: "header_email", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.header_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HeaderPhone(); ok {
		if err := invoiceapplication.HeaderPhoneValidator(v); err != nil {
			return &ValidationError{Name: "header_phone", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.header_phone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InvoiceNumber(); ok {
		if err := invoiceapplication.InvoiceNumberValidator(v); err != nil {
			return &ValidationError{Name: "invoice_number", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.invoice_number": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InvoiceApplication.user"`)
	}
	return nil
}

func (_u *InvoiceApplicationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoiceapplication.Table, invoiceapplication.Columns, sqlgraph.NewFieldSpec(invoiceapplication.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(invoiceapplication.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.InvoiceType(); ok {
		_spec.SetField(invoiceapplication.FieldInvoiceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.HeaderType(); ok {
		_spec.SetField(invoiceapplication.FieldHeaderType, field.TypeString, value)
	}
	if value, ok := _u.mutation.HeaderTitle(); ok {
		_spec.SetField(invoiceapplication.FieldHeaderTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.HeaderTaxNumber(); ok {
		_spec.SetField(invoiceapplication.FieldHeaderTaxNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.HeaderEmail(); ok {
		_spec.SetField(invoiceapplication.FieldHeaderEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.HeaderPhone(); ok {
		_spec.SetField(invoiceapplication.FieldHeaderPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.HeaderAddress(); ok {
		_spec.SetField(invoiceapplication.FieldHeaderAddress, field.TypeString, value)
	}
	if _u.mutation.HeaderAddressCleared() {
		_spec.ClearField(invoiceapplication.FieldHeaderAddress, field.TypeString)
	}
	if value, ok := _u.mutation.TotalAmount(); ok {
		_spec.SetField(invoiceapplication.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalAmount(); ok {
		_spec.AddField(invoiceapplication.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.HandledBy(); ok {
		_spec.SetField(invoiceapplication.FieldHandledBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedHandledBy(); ok {
		_spec.AddField(invoiceapplication.FieldHandledBy, field.TypeInt64, value)
	}
	if _u.mutation.HandledByCleared() {
		_spec.ClearField(invoiceapplication.FieldHandledBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.RejectionReason(); ok {
		_spec.SetField(invoiceapplication.FieldRejectionReason, field.TypeString, value)
	}
	if _u.mutation.RejectionReasonCleared() {
		_spec.ClearField(invoiceapplication.FieldRejectionReason, field.TypeString)
	}
	if value, ok := _u.mutation.AdminNote(); ok {
		_spec.SetField(invoiceapplication.FieldAdminNote, field.TypeString, value)
	}
	if _u.mutation.AdminNoteCleared() {
		_spec.ClearField(invoiceapplication.FieldAdminNote, field.TypeString)
	}
	if value, ok := _u.mutation.InvoiceNumber(); ok {
		_spec.SetField(invoiceapplication.FieldInvoiceNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProcessedAt(); ok {
		_spec.SetField(invoiceapplication.FieldProcessedAt, field.TypeTime, value)
	}
	if _u.mutation.ProcessedAtCleared() {
		_spec.ClearField(invoiceapplication.FieldProcessedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.InvoicedAt(); ok {
		_spec.SetField(invoiceapplication.FieldInvoicedAt, field.TypeTime, value)
	}
	if _u.mutation.InvoicedAtCleared() {
		_spec.ClearField(invoiceapplication.FieldInvoicedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invoiceapplication.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceapplication.UserTable,
			Columns: []string{invoiceapplication.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceapplication.UserTable,
			Columns: []string{invoiceapplication.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoiceapplication.OrdersTable,
			Columns: []string{invoiceapplication.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceapplicationorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOrdersIDs(); len(nodes) > 0 && !_u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoiceapplication.OrdersTable,
			Columns: []string{invoiceapplication.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceapplicationorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoiceapplication.OrdersTable,
			Columns: []string{invoiceapplication.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceapplicationorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoiceapplication.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InvoiceApplicationUpdateOne is the builder for updating a single InvoiceApplication entity.
type InvoiceApplicationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InvoiceApplicationMutation
}

// SetUserID sets the "user_id" field.
func (_u *InvoiceApplicationUpdateOne) SetUserID(v int64) *InvoiceApplicationUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableUserID(v *int64) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *InvoiceApplicationUpdateOne) SetStatus(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableStatus(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetInvoiceType sets the "invoice_type" field.
func (_u *InvoiceApplicationUpdateOne) SetInvoiceType(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetInvoiceType(v)
	return _u
}

// SetNillableInvoiceType sets the "invoice_type" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableInvoiceType(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetInvoiceType(*v)
	}
	return _u
}

// SetHeaderType sets the "header_type" field.
func (_u *InvoiceApplicationUpdateOne) SetHeaderType(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetHeaderType(v)
	return _u
}

// SetNillableHeaderType sets the "header_type" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableHeaderType(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetHeaderType(*v)
	}
	return _u
}

// SetHeaderTitle sets the "header_title" field.
func (_u *InvoiceApplicationUpdateOne) SetHeaderTitle(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetHeaderTitle(v)
	return _u
}

// SetNillableHeaderTitle sets the "header_title" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableHeaderTitle(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetHeaderTitle(*v)
	}
	return _u
}

// SetHeaderTaxNumber sets the "header_tax_number" field.
func (_u *InvoiceApplicationUpdateOne) SetHeaderTaxNumber(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetHeaderTaxNumber(v)
	return _u
}

// SetNillableHeaderTaxNumber sets the "header_tax_number" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableHeaderTaxNumber(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetHeaderTaxNumber(*v)
	}
	return _u
}

// SetHeaderEmail sets the "header_email" field.
func (_u *InvoiceApplicationUpdateOne) SetHeaderEmail(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetHeaderEmail(v)
	return _u
}

// SetNillableHeaderEmail sets the "header_email" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableHeaderEmail(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetHeaderEmail(*v)
	}
	return _u
}

// SetHeaderPhone sets the "header_phone" field.
func (_u *InvoiceApplicationUpdateOne) SetHeaderPhone(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetHeaderPhone(v)
	return _u
}

// SetNillableHeaderPhone sets the "header_phone" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableHeaderPhone(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetHeaderPhone(*v)
	}
	return _u
}

// SetHeaderAddress sets the "header_address" field.
func (_u *InvoiceApplicationUpdateOne) SetHeaderAddress(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetHeaderAddress(v)
	return _u
}

// SetNillableHeaderAddress sets the "header_address" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableHeaderAddress(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetHeaderAddress(*v)
	}
	return _u
}

// ClearHeaderAddress clears the value of the "header_address" field.
func (_u *InvoiceApplicationUpdateOne) ClearHeaderAddress() *InvoiceApplicationUpdateOne {
	_u.mutation.ClearHeaderAddress()
	return _u
}

// SetTotalAmount sets the "total_amount" field.
func (_u *InvoiceApplicationUpdateOne) SetTotalAmount(v float64) *InvoiceApplicationUpdateOne {
	_u.mutation.ResetTotalAmount()
	_u.mutation.SetTotalAmount(v)
	return _u
}

// SetNillableTotalAmount sets the "total_amount" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableTotalAmount(v *float64) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetTotalAmount(*v)
	}
	return _u
}

// AddTotalAmount adds value to the "total_amount" field.
func (_u *InvoiceApplicationUpdateOne) AddTotalAmount(v float64) *InvoiceApplicationUpdateOne {
	_u.mutation.AddTotalAmount(v)
	return _u
}

// SetHandledBy sets the "handled_by" field.
func (_u *InvoiceApplicationUpdateOne) SetHandledBy(v int64) *InvoiceApplicationUpdateOne {
	_u.mutation.ResetHandledBy()
	_u.mutation.SetHandledBy(v)
	return _u
}

// SetNillableHandledBy sets the "handled_by" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableHandledBy(v *int64) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetHandledBy(*v)
	}
	return _u
}

// AddHandledBy adds value to the "handled_by" field.
func (_u *InvoiceApplicationUpdateOne) AddHandledBy(v int64) *InvoiceApplicationUpdateOne {
	_u.mutation.AddHandledBy(v)
	return _u
}

// ClearHandledBy clears the value of the "handled_by" field.
func (_u *InvoiceApplicationUpdateOne) ClearHandledBy() *InvoiceApplicationUpdateOne {
	_u.mutation.ClearHandledBy()
	return _u
}

// SetRejectionReason sets the "rejection_reason" field.
func (_u *InvoiceApplicationUpdateOne) SetRejectionReason(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetRejectionReason(v)
	return _u
}

// SetNillableRejectionReason sets the "rejection_reason" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableRejectionReason(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetRejectionReason(*v)
	}
	return _u
}

// ClearRejectionReason clears the value of the "rejection_reason" field.
func (_u *InvoiceApplicationUpdateOne) ClearRejectionReason() *InvoiceApplicationUpdateOne {
	_u.mutation.ClearRejectionReason()
	return _u
}

// SetAdminNote sets the "admin_note" field.
func (_u *InvoiceApplicationUpdateOne) SetAdminNote(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetAdminNote(v)
	return _u
}

// SetNillableAdminNote sets the "admin_note" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableAdminNote(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetAdminNote(*v)
	}
	return _u
}

// ClearAdminNote clears the value of the "admin_note" field.
func (_u *InvoiceApplicationUpdateOne) ClearAdminNote() *InvoiceApplicationUpdateOne {
	_u.mutation.ClearAdminNote()
	return _u
}

// SetInvoiceNumber sets the "invoice_number" field.
func (_u *InvoiceApplicationUpdateOne) SetInvoiceNumber(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetInvoiceNumber(v)
	return _u
}

// SetNillableInvoiceNumber sets the "invoice_number" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableInvoiceNumber(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetInvoiceNumber(*v)
	}
	return _u
}

// SetProcessedAt sets the "processed_at" field.
func (_u *InvoiceApplicationUpdateOne) SetProcessedAt(v time.Time) *InvoiceApplicationUpdateOne {
	_u.mutation.SetProcessedAt(v)
	return _u
}

// SetNillableProcessedAt sets the "processed_at" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableProcessedAt(v *time.Time) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetProcessedAt(*v)
	}
	return _u
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (_u *InvoiceApplicationUpdateOne) ClearProcessedAt() *InvoiceApplicationUpdateOne {
	_u.mutation.ClearProcessedAt()
	return _u
}

// SetInvoicedAt sets the "invoiced_at" field.
func (_u *InvoiceApplicationUpdateOne) SetInvoicedAt(v time.Time) *InvoiceApplicationUpdateOne {
	_u.mutation.SetInvoicedAt(v)
	return _u
}

// SetNillableInvoicedAt sets the "invoiced_at" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableInvoicedAt(v *time.Time) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetInvoicedAt(*v)
	}
	return _u
}

// ClearInvoicedAt clears the value of the "invoiced_at" field.
func (_u *InvoiceApplicationUpdateOne) ClearInvoicedAt() *InvoiceApplicationUpdateOne {
	_u.mutation.ClearInvoicedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InvoiceApplicationUpdateOne) SetUpdatedAt(v time.Time) *InvoiceApplicationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *InvoiceApplicationUpdateOne) SetUser(v *User) *InvoiceApplicationUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddOrderIDs adds the "orders" edge to the InvoiceApplicationOrder entity by IDs.
func (_u *InvoiceApplicationUpdateOne) AddOrderIDs(ids ...int64) *InvoiceApplicationUpdateOne {
	_u.mutation.AddOrderIDs(ids...)
	return _u
}

// AddOrders adds the "orders" edges to the InvoiceApplicationOrder entity.
func (_u *InvoiceApplicationUpdateOne) AddOrders(v ...*InvoiceApplicationOrder) *InvoiceApplicationUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOrderIDs(ids...)
}

// Mutation returns the InvoiceApplicationMutation object of the builder.
func (_u *InvoiceApplicationUpdateOne) Mutation() *InvoiceApplicationMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *InvoiceApplicationUpdateOne) ClearUser() *InvoiceApplicationUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearOrders clears all "orders" edges to the InvoiceApplicationOrder entity.
func (_u *InvoiceApplicationUpdateOne) ClearOrders() *InvoiceApplicationUpdateOne {
	_u.mutation.ClearOrders()
	return _u
}

// RemoveOrderIDs removes the "orders" edge to InvoiceApplicationOrder entities by IDs.
func (_u *InvoiceApplicationUpdateOne) RemoveOrderIDs(ids ...int64) *InvoiceApplicationUpdateOne {
	_u.mutation.RemoveOrderIDs(ids...)
	return _u
}

// RemoveOrders removes "orders" edges to InvoiceApplicationOrder entities.
func (_u *InvoiceApplicationUpdateOne) RemoveOrders(v ...*InvoiceApplicationOrder) *InvoiceApplicationUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOrderIDs(ids...)
}

// Where appends a list predicates to the InvoiceApplicationUpdate builder.
func (_u *InvoiceApplicationUpdateOne) Where(ps ...predicate.InvoiceApplication) *InvoiceApplicationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InvoiceApplicationUpdateOne) Select(field string, fields ...string) *InvoiceApplicationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InvoiceApplication entity.
func (_u *InvoiceApplicationUpdateOne) Save(ctx context.Context) (*InvoiceApplication, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceApplicationUpdateOne) SaveX(ctx context.Context) *InvoiceApplication {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InvoiceApplicationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceApplicationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InvoiceApplicationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := invoiceapplication.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceApplicationUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := invoiceapplication.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InvoiceType(); ok {
		if err := invoiceapplication.InvoiceTypeValidator(v); err != nil {
			return &ValidationError{Name: "invoice_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.invoice_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HeaderType(); ok {
		if err := invoiceapplication.HeaderTypeValidator(v); err != nil {
			return &ValidationError{Name: "header_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.header_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HeaderTitle(); ok {
		if err := invoiceapplication.HeaderTitleValidator(v); err != nil {
			return &ValidationError{Name: "header_title", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.header_title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HeaderTaxNumber(); ok {
		if err := invoiceapplication.HeaderTaxNumberValidator(v); err != nil {
			return &ValidationError{Name: "header_tax_number", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.header_tax_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HeaderEmail(); ok {
		if err := invoiceapplication.HeaderEmailValidator(v); err != nil {
			return &ValidationError{Name: "header_email", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.header_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HeaderPhone(); ok {
		if err := invoiceapplication.HeaderPhoneValidator(v); err != nil {
			return &ValidationError{Name: "header_phone", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.header_phone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InvoiceNumber(); ok {
		if err := invoiceapplication.InvoiceNumberValidator(v); err != nil {
			return &ValidationError{Name: "invoice_number", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.invoice_number": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InvoiceApplication.user"`)
	}
	return nil
}

func (_u *InvoiceApplicationUpdateOne) sqlSave(ctx context.Context) (_node *InvoiceApplication, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoiceapplication.Table, invoiceapplication.Columns, sqlgraph.NewFieldSpec(invoiceapplication.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InvoiceApplication.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invoiceapplication.FieldID)
		for _, f := range fields {
			if !invoiceapplication.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invoiceapplication.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(invoiceapplication.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.InvoiceType(); ok {
		_spec.SetField(invoiceapplication.FieldInvoiceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.HeaderType(); ok {
		_spec.SetField(invoiceapplication.FieldHeaderType, field.TypeString, value)
	}
	if value, ok := _u.mutation.HeaderTitle(); ok {
		_spec.SetField(invoiceapplication.FieldHeaderTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.HeaderTaxNumber(); ok {
		_spec.SetField(invoiceapplication.FieldHeaderTaxNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.HeaderEmail(); ok {
		_spec.SetField(invoiceapplication.FieldHeaderEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.HeaderPhone(); ok {
		_spec.SetField(invoiceapplication.FieldHeaderPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.HeaderAddress(); ok {
		_spec.SetField(invoiceapplication.FieldHeaderAddress, field.TypeString, value)
	}
	if _u.mutation.HeaderAddressCleared() {
		_spec.ClearField(invoiceapplication.FieldHeaderAddress, field.TypeString)
	}
	if value, ok := _u.mutation.TotalAmount(); ok {
		_spec.SetField(invoiceapplication.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalAmount(); ok {
		_spec.AddField(invoiceapplication.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.HandledBy(); ok {
		_spec.SetField(invoiceapplication.FieldHandledBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedHandledBy(); ok {
		_spec.AddField(invoiceapplication.FieldHandledBy, field.TypeInt64, value)
	}
	if _u.mutation.HandledByCleared() {
		_spec.ClearField(invoiceapplication.FieldHandledBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.RejectionReason(); ok {
		_spec.SetField(invoiceapplication.FieldRejectionReason, field.TypeString, value)
	}
	if _u.mutation.RejectionReasonCleared() {
		_spec.ClearField(invoiceapplication.FieldRejectionReason, field.TypeString)
	}
	if value, ok := _u.mutation.AdminNote(); ok {
		_spec.SetField(invoiceapplication.FieldAdminNote, field.TypeString, value)
	}
	if _u.mutation.AdminNoteCleared() {
		_spec.ClearField(invoiceapplication.FieldAdminNote, field.TypeString)
	}
	if value, ok := _u.mutation.InvoiceNumber(); ok {
		_spec.SetField(invoiceapplication.FieldInvoiceNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProcessedAt(); ok {
		_spec.SetField(invoiceapplication.FieldProcessedAt, field.TypeTime, value)
	}
	if _u.mutation.ProcessedAtCleared() {
		_spec.ClearField(invoiceapplication.FieldProcessedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.InvoicedAt(); ok {
		_spec.SetField(invoiceapplication.FieldInvoicedAt, field.TypeTime, value)
	}
	if _u.mutation.InvoicedAtCleared() {
		_spec.ClearField(invoiceapplication.FieldInvoicedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invoiceapplication.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceapplication.UserTable,
			Columns: []string{invoiceapplication.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceapplication.UserTable,
			Columns: []string{invoiceapplication.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoiceapplication.OrdersTable,
			Columns: []string{invoiceapplication.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceapplicationorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOrdersIDs(); len(nodes) > 0 && !_u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoiceapplication.OrdersTable,
			Columns: []string{invoiceapplication.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceapplicationorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoiceapplication.OrdersTable,
			Columns: []string{invoiceapplication.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceapplicationorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &InvoiceApplication{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoiceapplication.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
