// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoicesetting"
)

// InvoiceSettingCreate is the builder for creating a InvoiceSetting entity.
type InvoiceSettingCreate struct {
	config
	mutation *InvoiceSettingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetMinAmount sets the "min_amount" field.
func (_c *InvoiceSettingCreate) SetMinAmount(v float64) *InvoiceSettingCreate {
	_c.mutation.SetMinAmount(v)
	return _c
}

// SetNillableMinAmount sets the "min_amount" field if the given value is not nil.
func (_c *InvoiceSettingCreate) SetNillableMinAmount(v *float64) *InvoiceSettingCreate {
	if v != nil {
		_c.SetMinAmount(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InvoiceSettingCreate) SetCreatedAt(v time.Time) *InvoiceSettingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InvoiceSettingCreate) SetNillableCreatedAt(v *time.Time) *InvoiceSettingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *InvoiceSettingCreate) SetUpdatedAt(v time.Time) *InvoiceSettingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *InvoiceSettingCreate) SetNillableUpdatedAt(v *time.Time) *InvoiceSettingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the InvoiceSettingMutation object of the builder.
func (_c *InvoiceSettingCreate) Mutation() *InvoiceSettingMutation {
	return _c.mutation
}

// Save creates the InvoiceSetting in the database.
func (_c *InvoiceSettingCreate) Save(ctx context.Context) (*InvoiceSetting, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InvoiceSettingCreate) SaveX(ctx context.Context) *InvoiceSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceSettingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceSettingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InvoiceSettingCreate) defaults() {
	if _, ok := _c.mutation.MinAmount(); !ok {
		v := invoicesetting.DefaultMinAmount
		_c.mutation.SetMinAmount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := invoicesetting.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := invoicesetting.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InvoiceSettingCreate) check() error {
	if _, ok := _c.mutation.MinAmount(); !ok {
		return &ValidationError{Name: "min_amount", err: errors.New(`ent: missing required field "InvoiceSetting.min_amount"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "InvoiceSetting.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "InvoiceSetting.updated_at"`)}
	}
	return nil
}

func (_c *InvoiceSettingCreate) sqlSave(ctx context.Context) (*InvoiceSetting, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InvoiceSettingCreate) createSpec() (*InvoiceSetting, *sqlgraph.CreateSpec) {
	var (
		_node = &InvoiceSetting{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(invoicesetting.Table, sqlgraph.NewFieldSpec(invoicesetting.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.MinAmount(); ok {
		_spec.SetField(invoicesetting.FieldMinAmount, field.TypeFloat64, value)
		_node.MinAmount = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(invoicesetting.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(invoicesetting.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceSetting.Create().
//		SetMinAmount(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceSettingUpsert) {
//			SetMinAmount(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceSettingCreate) OnConflict(opts ...sql.ConflictOption) *InvoiceSettingUpsertOne {
	_c.conflict = opts
	return &InvoiceSettingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceSetting.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceSettingCreate) OnConflictColumns(columns ...string) *InvoiceSettingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceSettingUpsertOne{
		create: _c,
	}
}

type (
	// InvoiceSettingUpsertOne is the builder for "upsert"-ing
	//  one InvoiceSetting node.
	InvoiceSettingUpsertOne struct {
		create *InvoiceSettingCreate
	}

	// InvoiceSettingUpsert is the "OnConflict" setter.
	InvoiceSettingUpsert struct {
		*sql.UpdateSet
	}
)

// SetMinAmount sets the "min_amount" field.
func (u *InvoiceSettingUpsert) SetMinAmount(v float64) *InvoiceSettingUpsert {
	u.Set(invoicesetting.FieldMinAmount, v)
	return u
}

// UpdateMinAmount sets the "min_amount" field to the value that was provided on create.
func (u *InvoiceSettingUpsert) UpdateMinAmount() *InvoiceSettingUpsert {
	u.SetExcluded(invoicesetting.FieldMinAmount)
	return u
}

// AddMinAmount adds v to the "min_amount" field.
func (u *InvoiceSettingUpsert) AddMinAmount(v float64) *InvoiceSettingUpsert {
	u.Add(invoicesetting.FieldMinAmount, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceSettingUpsert) SetUpdatedAt(v time.Time) *InvoiceSettingUpsert {
	u.Set(invoicesetting.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceSettingUpsert) UpdateUpdatedAt() *InvoiceSettingUpsert {
	u.SetExcluded(invoicesetting.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.InvoiceSetting.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceSettingUpsertOne) UpdateNewValues() *InvoiceSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(invoicesetting.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceSetting.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InvoiceSettingUpsertOne) Ignore() *InvoiceSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceSettingUpsertOne) DoNothing() *InvoiceSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceSettingCreate.OnConflict
// documentation for more info.
func (u *InvoiceSettingUpsertOne) Update(set func(*InvoiceSettingUpsert)) *InvoiceSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceSettingUpsert{UpdateSet: update})
	}))
	return u
}

// SetMinAmount sets the "min_amount" field.
func (u *InvoiceSettingUpsertOne) SetMinAmount(v float64) *InvoiceSettingUpsertOne {
	return u.Update(func(s *InvoiceSettingUpsert) {
		s.SetMinAmount(v)
	})
}

// AddMinAmount adds v to the "min_amount" field.
func (u *InvoiceSettingUpsertOne) AddMinAmount(v float64) *InvoiceSettingUpsertOne {
	return u.Update(func(s *InvoiceSettingUpsert) {
		s.AddMinAmount(v)
	})
}

// UpdateMinAmount sets the "min_amount" field to the value that was provided on create.
func (u *InvoiceSettingUpsertOne) UpdateMinAmount() *InvoiceSettingUpsertOne {
	return u.Update(func(s *InvoiceSettingUpsert) {
		s.UpdateMinAmount()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceSettingUpsertOne) SetUpdatedAt(v time.Time) *InvoiceSettingUpsertOne {
	return u.Update(func(s *InvoiceSettingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceSettingUpsertOne) UpdateUpdatedAt() *InvoiceSettingUpsertOne {
	return u.Update(func(s *InvoiceSettingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *InvoiceSettingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceSettingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceSettingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InvoiceSettingUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InvoiceSettingUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InvoiceSettingCreateBulk is the builder for creating many InvoiceSetting entities in bulk.
type InvoiceSettingCreateBulk struct {
	config
	err      error
	builders []*InvoiceSettingCreate
	conflict []sql.ConflictOption
}

// Save creates the InvoiceSetting entities in the database.
func (_c *InvoiceSettingCreateBulk) Save(ctx context.Context) ([]*InvoiceSetting, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InvoiceSetting, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InvoiceSettingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InvoiceSettingCreateBulk) SaveX(ctx context.Context) []*InvoiceSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceSettingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceSettingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceSetting.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceSettingUpsert) {
//			SetMinAmount(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceSettingCreateBulk) OnConflict(opts ...sql.ConflictOption) *InvoiceSettingUpsertBulk {
	_c.conflict = opts
	return &InvoiceSettingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceSetting.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceSettingCreateBulk) OnConflictColumns(columns ...string) *InvoiceSettingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceSettingUpsertBulk{
		create: _c,
	}
}

// InvoiceSettingUpsertBulk is the builder for "upsert"-ing
// a bulk of InvoiceSetting nodes.
type InvoiceSettingUpsertBulk struct {
	create *InvoiceSettingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.InvoiceSetting.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceSettingUpsertBulk) UpdateNewValues() *InvoiceSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(invoicesetting.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceSetting.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InvoiceSettingUpsertBulk) Ignore() *InvoiceSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceSettingUpsertBulk) DoNothing() *InvoiceSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceSettingCreateBulk.OnConflict
// documentation for more info.
func (u *InvoiceSettingUpsertBulk) Update(set func(*InvoiceSettingUpsert)) *InvoiceSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceSettingUpsert{UpdateSet: update})
	}))
	return u
}

// SetMinAmount sets the "min_amount" field.
func (u *InvoiceSettingUpsertBulk) SetMinAmount(v float64) *InvoiceSettingUpsertBulk {
	return u.Update(func(s *InvoiceSettingUpsert) {
		s.SetMinAmount(v)
	})
}

// AddMinAmount adds v to the "min_amount" field.
func (u *InvoiceSettingUpsertBulk) AddMinAmount(v float64) *InvoiceSettingUpsertBulk {
	return u.Update(func(s *InvoiceSettingUpsert) {
		s.AddMinAmount(v)
	})
}

// UpdateMinAmount sets the "min_amount" field to the value that was provided on create.
func (u *InvoiceSettingUpsertBulk) UpdateMinAmount() *InvoiceSettingUpsertBulk {
	return u.Update(func(s *InvoiceSettingUpsert) {
		s.UpdateMinAmount()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceSettingUpsertBulk) SetUpdatedAt(v time.Time) *InvoiceSettingUpsertBulk {
	return u.Update(func(s *InvoiceSettingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceSettingUpsertBulk) UpdateUpdatedAt() *InvoiceSettingUpsertBulk {
	return u.Update(func(s *InvoiceSettingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *InvoiceSettingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InvoiceSettingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceSettingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceSettingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
