// Code generated by ent, DO NOT EDIT.

package invoicesetting

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.FieldLTE(FieldID, id))
}

// MinAmount applies equality check predicate on the "min_amount" field. It's identical to MinAmountEQ.
func MinAmount(v float64) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.FieldEQ(FieldMinAmount, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.FieldEQ(FieldUpdatedAt, v))
}

// MinAmountEQ applies the EQ predicate on the "min_amount" field.
func MinAmountEQ(v float64) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.FieldEQ(FieldMinAmount, v))
}

// MinAmountNEQ applies the NEQ predicate on the "min_amount" field.
func MinAmountNEQ(v float64) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.FieldNEQ(FieldMinAmount, v))
}

// MinAmountIn applies the In predicate on the "min_amount" field.
func MinAmountIn(vs ...float64) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.FieldIn(FieldMinAmount, vs...))
}

// MinAmountNotIn applies the NotIn predicate on the "min_amount" field.
func MinAmountNotIn(vs ...float64) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.FieldNotIn(FieldMinAmount, vs...))
}

// MinAmountGT applies the GT predicate on the "min_amount" field.
func MinAmountGT(v float64) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.FieldGT(FieldMinAmount, v))
}

// MinAmountGTE applies the GTE predicate on the "min_amount" field.
func MinAmountGTE(v float64) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.FieldGTE(FieldMinAmount, v))
}

// MinAmountLT applies the LT predicate on the "min_amount" field.
func MinAmountLT(v float64) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.FieldLT(FieldMinAmount, v))
}

// MinAmountLTE applies the LTE predicate on the "min_amount" field.
func MinAmountLTE(v float64) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.FieldLTE(FieldMinAmount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InvoiceSetting) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InvoiceSetting) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InvoiceSetting) predicate.InvoiceSetting {
	return predicate.InvoiceSetting(sql.NotPredicates(p))
}
