-- Runtime schema parity for MySQL raw-SQL tables and post-baseline columns.
-- These objects are referenced by repositories/services but are not generated by Ent.

-- ============================================================
-- audit / reconciliation helper tables
-- ============================================================
CREATE TABLE IF NOT EXISTS `orphan_allowed_groups_audit` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `user_id` bigint NOT NULL,
    `group_id` bigint NOT NULL,
    `recorded_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`id`),
    UNIQUE INDEX `orphan_allowed_groups_audit_user_group_key` (`user_id`, `group_id`),
    INDEX `idx_orphan_allowed_groups_audit_user_id` (`user_id`)
) CHARSET utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `billing_usage_entries` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `usage_log_id` bigint NOT NULL,
    `user_id` bigint NOT NULL,
    `api_key_id` bigint NOT NULL,
    `subscription_id` bigint NULL,
    `billing_type` smallint NOT NULL,
    `applied` bool NOT NULL DEFAULT true,
    `delta_usd` decimal(20,10) NOT NULL DEFAULT 0,
    `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`id`),
    UNIQUE INDEX `billing_usage_entries_usage_log_id_unique` (`usage_log_id`),
    INDEX `idx_billing_usage_entries_user_time` (`user_id`, `created_at`),
    INDEX `idx_billing_usage_entries_created_at` (`created_at`),
    CONSTRAINT `billing_usage_entries_usage_logs_usage_log` FOREIGN KEY (`usage_log_id`) REFERENCES `usage_logs` (`id`) ON DELETE CASCADE,
    CONSTRAINT `billing_usage_entries_users_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
    CONSTRAINT `billing_usage_entries_api_keys_api_key` FOREIGN KEY (`api_key_id`) REFERENCES `api_keys` (`id`) ON DELETE CASCADE,
    CONSTRAINT `billing_usage_entries_user_subscriptions_subscription` FOREIGN KEY (`subscription_id`) REFERENCES `user_subscriptions` (`id`) ON DELETE SET NULL
) CHARSET utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `usage_billing_dedup` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `request_id` varchar(255) NOT NULL,
    `api_key_id` bigint NOT NULL,
    `request_fingerprint` varchar(64) NOT NULL,
    `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`id`),
    UNIQUE INDEX `idx_usage_billing_dedup_request_api_key` (`request_id`, `api_key_id`),
    INDEX `idx_usage_billing_dedup_created_at_brin` (`created_at`)
) CHARSET utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `usage_billing_dedup_archive` (
    `request_id` varchar(255) NOT NULL,
    `api_key_id` bigint NOT NULL,
    `request_fingerprint` varchar(64) NOT NULL,
    `created_at` datetime(6) NOT NULL,
    `archived_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`request_id`, `api_key_id`)
) CHARSET utf8mb4 COLLATE utf8mb4_bin;

-- ============================================================
-- channel raw tables follow-ups
-- ============================================================
SET @col_exists = (
    SELECT COUNT(1)
    FROM information_schema.columns
    WHERE table_schema = DATABASE()
      AND table_name = 'channels'
      AND column_name = 'model_mapping'
);
SET @sql = IF(@col_exists = 0, 'ALTER TABLE `channels` ADD COLUMN `model_mapping` JSON NULL', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists = (
    SELECT COUNT(1)
    FROM information_schema.columns
    WHERE table_schema = DATABASE()
      AND table_name = 'channels'
      AND column_name = 'billing_model_source'
);
SET @sql = IF(@col_exists = 0, 'ALTER TABLE `channels` ADD COLUMN `billing_model_source` varchar(20) NOT NULL DEFAULT ''channel_mapped''', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists = (
    SELECT COUNT(1)
    FROM information_schema.columns
    WHERE table_schema = DATABASE()
      AND table_name = 'channels'
      AND column_name = 'restrict_models'
);
SET @sql = IF(@col_exists = 0, 'ALTER TABLE `channels` ADD COLUMN `restrict_models` bool NOT NULL DEFAULT false', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists = (
    SELECT COUNT(1)
    FROM information_schema.columns
    WHERE table_schema = DATABASE()
      AND table_name = 'channels'
      AND column_name = 'features'
);
SET @sql = IF(@col_exists = 0, 'ALTER TABLE `channels` ADD COLUMN `features` longtext NULL', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

UPDATE `channels`
SET `features` = ''
WHERE `features` IS NULL;

SET @col_exists = (
    SELECT COUNT(1)
    FROM information_schema.columns
    WHERE table_schema = DATABASE()
      AND table_name = 'channels'
      AND column_name = 'features'
);
SET @sql = IF(@col_exists = 1, 'ALTER TABLE `channels` MODIFY COLUMN `features` longtext NOT NULL', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists = (
    SELECT COUNT(1)
    FROM information_schema.columns
    WHERE table_schema = DATABASE()
      AND table_name = 'channels'
      AND column_name = 'features_config'
);
SET @sql = IF(@col_exists = 0, 'ALTER TABLE `channels` ADD COLUMN `features_config` JSON NULL', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists = (
    SELECT COUNT(1)
    FROM information_schema.columns
    WHERE table_schema = DATABASE()
      AND table_name = 'channels'
      AND column_name = 'apply_pricing_to_account_stats'
);
SET @sql = IF(@col_exists = 0, 'ALTER TABLE `channels` ADD COLUMN `apply_pricing_to_account_stats` bool NOT NULL DEFAULT false', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists = (
    SELECT COUNT(1)
    FROM information_schema.columns
    WHERE table_schema = DATABASE()
      AND table_name = 'channel_model_pricing'
      AND column_name = 'platform'
);
SET @sql = IF(@col_exists = 0, 'ALTER TABLE `channel_model_pricing` ADD COLUMN `platform` varchar(50) NOT NULL DEFAULT ''anthropic''', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists = (
    SELECT COUNT(1)
    FROM information_schema.columns
    WHERE table_schema = DATABASE()
      AND table_name = 'channel_model_pricing'
      AND column_name = 'billing_mode'
);
SET @sql = IF(@col_exists = 0, 'ALTER TABLE `channel_model_pricing` ADD COLUMN `billing_mode` varchar(20) NOT NULL DEFAULT ''token''', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists = (
    SELECT COUNT(1)
    FROM information_schema.columns
    WHERE table_schema = DATABASE()
      AND table_name = 'channel_model_pricing'
      AND column_name = 'per_request_price'
);
SET @sql = IF(@col_exists = 0, 'ALTER TABLE `channel_model_pricing` ADD COLUMN `per_request_price` decimal(20,10) NULL', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @idx_exists = (
    SELECT COUNT(1)
    FROM information_schema.statistics
    WHERE table_schema = DATABASE()
      AND table_name = 'channel_model_pricing'
      AND index_name = 'idx_channel_model_pricing_platform'
);
SET @sql = IF(@idx_exists = 0, 'CREATE INDEX idx_channel_model_pricing_platform ON channel_model_pricing (platform)', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

CREATE TABLE IF NOT EXISTS `channel_pricing_intervals` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `pricing_id` bigint NOT NULL,
    `min_tokens` int NOT NULL DEFAULT 0,
    `max_tokens` int NULL,
    `tier_label` varchar(50) NULL,
    `input_price` decimal(20,12) NULL,
    `output_price` decimal(20,12) NULL,
    `cache_write_price` decimal(20,12) NULL,
    `cache_read_price` decimal(20,12) NULL,
    `per_request_price` decimal(20,12) NULL,
    `sort_order` int NOT NULL DEFAULT 0,
    `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`id`),
    INDEX `idx_channel_pricing_intervals_pricing_id` (`pricing_id`),
    CONSTRAINT `channel_pricing_intervals_channel_model_pricing_pricing` FOREIGN KEY (`pricing_id`) REFERENCES `channel_model_pricing` (`id`) ON DELETE CASCADE
) CHARSET utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `channel_account_stats_pricing_rules` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `channel_id` bigint NOT NULL,
    `name` varchar(100) NOT NULL DEFAULT '',
    `group_ids` json NOT NULL,
    `account_ids` json NOT NULL,
    `sort_order` int NOT NULL DEFAULT 0,
    `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`id`),
    INDEX `idx_cas_pricing_rules_channel_id` (`channel_id`),
    CONSTRAINT `channel_account_stats_pricing_rules_channels_channel` FOREIGN KEY (`channel_id`) REFERENCES `channels` (`id`) ON DELETE CASCADE
) CHARSET utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `channel_account_stats_model_pricing` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `rule_id` bigint NOT NULL,
    `platform` varchar(50) NOT NULL DEFAULT '',
    `models` json NOT NULL,
    `billing_mode` varchar(20) NOT NULL DEFAULT 'token',
    `input_price` decimal(20,10) NULL,
    `output_price` decimal(20,10) NULL,
    `cache_write_price` decimal(20,10) NULL,
    `cache_read_price` decimal(20,10) NULL,
    `image_output_price` decimal(20,10) NULL,
    `per_request_price` decimal(20,10) NULL,
    `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`id`),
    INDEX `idx_cas_model_pricing_rule_id` (`rule_id`),
    CONSTRAINT `channel_account_stats_model_pricing_rules_rule` FOREIGN KEY (`rule_id`) REFERENCES `channel_account_stats_pricing_rules` (`id`) ON DELETE CASCADE
) CHARSET utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `channel_account_stats_pricing_intervals` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `pricing_id` bigint NOT NULL,
    `min_tokens` int NOT NULL DEFAULT 0,
    `max_tokens` int NULL,
    `tier_label` varchar(50) NULL,
    `input_price` decimal(20,12) NULL,
    `output_price` decimal(20,12) NULL,
    `cache_write_price` decimal(20,12) NULL,
    `cache_read_price` decimal(20,12) NULL,
    `per_request_price` decimal(20,12) NULL,
    `sort_order` int NOT NULL DEFAULT 0,
    `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`id`),
    INDEX `idx_account_stats_pricing_intervals_pricing_id` (`pricing_id`),
    CONSTRAINT `channel_account_stats_pricing_intervals_pricing_id_fk` FOREIGN KEY (`pricing_id`) REFERENCES `channel_account_stats_model_pricing` (`id`) ON DELETE CASCADE
) CHARSET utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `channel_monitor_aggregation_watermark` (
    `id` int NOT NULL DEFAULT 1,
    `last_aggregated_date` date NULL,
    `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`id`)
) CHARSET utf8mb4 COLLATE utf8mb4_bin;

INSERT IGNORE INTO `channel_monitor_aggregation_watermark` (`id`, `last_aggregated_date`, `updated_at`)
VALUES (1, NULL, CURRENT_TIMESTAMP(6));

-- ============================================================
-- usage_logs follow-ups required by repository queries
-- ============================================================
SET @col_exists = (
    SELECT COUNT(1)
    FROM information_schema.columns
    WHERE table_schema = DATABASE()
      AND table_name = 'usage_logs'
      AND column_name = 'image_output_tokens'
);
SET @sql = IF(@col_exists = 0, 'ALTER TABLE `usage_logs` ADD COLUMN `image_output_tokens` int NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists = (
    SELECT COUNT(1)
    FROM information_schema.columns
    WHERE table_schema = DATABASE()
      AND table_name = 'usage_logs'
      AND column_name = 'image_output_cost'
);
SET @sql = IF(@col_exists = 0, 'ALTER TABLE `usage_logs` ADD COLUMN `image_output_cost` decimal(20,10) NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists = (
    SELECT COUNT(1)
    FROM information_schema.columns
    WHERE table_schema = DATABASE()
      AND table_name = 'usage_logs'
      AND column_name = 'reasoning_effort'
);
SET @sql = IF(@col_exists = 0, 'ALTER TABLE `usage_logs` ADD COLUMN `reasoning_effort` varchar(20) NULL', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists = (
    SELECT COUNT(1)
    FROM information_schema.columns
    WHERE table_schema = DATABASE()
      AND table_name = 'usage_logs'
      AND column_name = 'openai_ws_mode'
);
SET @sql = IF(@col_exists = 0, 'ALTER TABLE `usage_logs` ADD COLUMN `openai_ws_mode` bool NOT NULL DEFAULT false', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists = (
    SELECT COUNT(1)
    FROM information_schema.columns
    WHERE table_schema = DATABASE()
      AND table_name = 'usage_logs'
      AND column_name = 'request_type'
);
SET @sql = IF(@col_exists = 0, 'ALTER TABLE `usage_logs` ADD COLUMN `request_type` smallint NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists = (
    SELECT COUNT(1)
    FROM information_schema.columns
    WHERE table_schema = DATABASE()
      AND table_name = 'usage_logs'
      AND column_name = 'service_tier'
);
SET @sql = IF(@col_exists = 0, 'ALTER TABLE `usage_logs` ADD COLUMN `service_tier` varchar(16) NULL', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists = (
    SELECT COUNT(1)
    FROM information_schema.columns
    WHERE table_schema = DATABASE()
      AND table_name = 'usage_logs'
      AND column_name = 'inbound_endpoint'
);
SET @sql = IF(@col_exists = 0, 'ALTER TABLE `usage_logs` ADD COLUMN `inbound_endpoint` varchar(128) NULL', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists = (
    SELECT COUNT(1)
    FROM information_schema.columns
    WHERE table_schema = DATABASE()
      AND table_name = 'usage_logs'
      AND column_name = 'upstream_endpoint'
);
SET @sql = IF(@col_exists = 0, 'ALTER TABLE `usage_logs` ADD COLUMN `upstream_endpoint` varchar(128) NULL', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists = (
    SELECT COUNT(1)
    FROM information_schema.columns
    WHERE table_schema = DATABASE()
      AND table_name = 'usage_logs'
      AND column_name = 'account_stats_cost'
);
SET @sql = IF(@col_exists = 0, 'ALTER TABLE `usage_logs` ADD COLUMN `account_stats_cost` decimal(20,10) NULL', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @idx_exists = (
    SELECT COUNT(1)
    FROM information_schema.statistics
    WHERE table_schema = DATABASE()
      AND table_name = 'usage_logs'
      AND index_name = 'idx_usage_logs_request_type_created_at'
);
SET @sql = IF(@idx_exists = 0, 'CREATE INDEX idx_usage_logs_request_type_created_at ON usage_logs (request_type, created_at)', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @idx_exists = (
    SELECT COUNT(1)
    FROM information_schema.statistics
    WHERE table_schema = DATABASE()
      AND table_name = 'usage_logs'
      AND index_name = 'idx_usage_logs_service_tier_created_at'
);
SET @sql = IF(@idx_exists = 0, 'CREATE INDEX idx_usage_logs_service_tier_created_at ON usage_logs (service_tier, created_at)', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- ============================================================
-- auth identity migration reports
-- ============================================================
CREATE TABLE IF NOT EXISTS `auth_identity_migration_reports` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `report_type` varchar(80) NOT NULL,
    `report_key` varchar(255) NOT NULL,
    `details` json NOT NULL,
    `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `resolved_at` datetime(6) NULL,
    `resolved_by_user_id` bigint NULL,
    `resolution_note` longtext NULL,
    PRIMARY KEY (`id`),
    INDEX `auth_identity_migration_reports_type_idx` (`report_type`),
    UNIQUE INDEX `auth_identity_migration_reports_type_key` (`report_type`, `report_key`),
    INDEX `idx_auth_identity_migration_reports_resolved_at` (`resolved_at`)
) CHARSET utf8mb4 COLLATE utf8mb4_bin;

-- ============================================================
-- user/group and affiliate raw tables
-- ============================================================
CREATE TABLE IF NOT EXISTS `user_group_rate_multipliers` (
    `user_id` bigint NOT NULL,
    `group_id` bigint NOT NULL,
    `rate_multiplier` decimal(10,4) NULL,
    `rpm_override` int NULL,
    `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`user_id`, `group_id`),
    INDEX `idx_user_group_rate_multipliers_group_id` (`group_id`),
    CONSTRAINT `user_group_rate_multipliers_users_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
    CONSTRAINT `user_group_rate_multipliers_groups_group` FOREIGN KEY (`group_id`) REFERENCES `groups` (`id`) ON DELETE CASCADE
) CHARSET utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `user_affiliates` (
    `user_id` bigint NOT NULL,
    `aff_code` varchar(32) NOT NULL,
    `inviter_id` bigint NULL,
    `aff_count` int NOT NULL DEFAULT 0,
    `aff_quota` decimal(20,8) NOT NULL DEFAULT 0,
    `aff_history_quota` decimal(20,8) NOT NULL DEFAULT 0,
    `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`user_id`),
    UNIQUE INDEX `user_affiliates_aff_code_key` (`aff_code`),
    INDEX `idx_user_affiliates_inviter_id` (`inviter_id`),
    INDEX `idx_user_affiliates_aff_quota` (`aff_quota`),
    CONSTRAINT `user_affiliates_users_affiliate` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
    CONSTRAINT `user_affiliates_users_inviter` FOREIGN KEY (`inviter_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) CHARSET utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `user_affiliate_ledger` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `user_id` bigint NOT NULL,
    `action` varchar(32) NOT NULL,
    `amount` decimal(20,8) NOT NULL,
    `source_user_id` bigint NULL,
    `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`id`),
    INDEX `idx_user_affiliate_ledger_user_id` (`user_id`),
    INDEX `idx_user_affiliate_ledger_action` (`action`),
    CONSTRAINT `user_affiliate_ledger_users_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
    CONSTRAINT `user_affiliate_ledger_users_source_user` FOREIGN KEY (`source_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) CHARSET utf8mb4 COLLATE utf8mb4_bin;

-- ============================================================
-- payment audit idempotency hardening
-- ============================================================
DELETE p1
FROM `payment_audit_logs` p1
INNER JOIN `payment_audit_logs` p2
    ON p1.`order_id` = p2.`order_id`
   AND p1.`action` = p2.`action`
   AND p1.`id` > p2.`id`;

SET @idx_exists = (
    SELECT COUNT(1)
    FROM information_schema.statistics
    WHERE table_schema = DATABASE()
      AND table_name = 'payment_audit_logs'
      AND index_name = 'idx_payment_audit_logs_order_action_uniq'
);
SET @sql = IF(@idx_exists = 0, 'CREATE UNIQUE INDEX idx_payment_audit_logs_order_action_uniq ON payment_audit_logs (order_id, action)', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
