CREATE TABLE IF NOT EXISTS `audit_logs` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `actor_user_id` BIGINT NULL,
    `actor_email` VARCHAR(255) NOT NULL DEFAULT '',
    `actor_role` VARCHAR(32) NOT NULL DEFAULT '',
    `auth_method` VARCHAR(32) NOT NULL DEFAULT '',
    `credential_masked` VARCHAR(160) NOT NULL DEFAULT '',
    `action` VARCHAR(128) NOT NULL DEFAULT '',
    `method` VARCHAR(16) NOT NULL DEFAULT '',
    `path` VARCHAR(512) NOT NULL DEFAULT '',
    `request_id` VARCHAR(64) NOT NULL DEFAULT '',
    `client_ip` VARCHAR(64) NOT NULL DEFAULT '',
    `user_agent` VARCHAR(512) NOT NULL DEFAULT '',
    `request_body` LONGTEXT NOT NULL,
    `status_code` INT NOT NULL DEFAULT 0,
    `latency_ms` BIGINT NOT NULL DEFAULT 0,
    `extra` JSON NOT NULL DEFAULT (JSON_OBJECT()),
    PRIMARY KEY (`id`),
    KEY `idx_audit_logs_created_at_id` (`created_at` DESC, `id` DESC),
    KEY `idx_audit_logs_actor_created` (`actor_user_id`, `created_at` DESC),
    KEY `idx_audit_logs_action` (`action`),
    KEY `idx_audit_logs_client_ip` (`client_ip`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
