CREATE TABLE IF NOT EXISTS `prompt_audit_jobs` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `request_id` VARCHAR(128) NOT NULL DEFAULT '',
    `user_id` BIGINT NULL,
    `username_snapshot` VARCHAR(255) NOT NULL DEFAULT '',
    `user_email_snapshot` VARCHAR(320) NOT NULL DEFAULT '',
    `api_key_id` BIGINT NULL,
    `api_key_name_snapshot` VARCHAR(255) NOT NULL DEFAULT '',
    `group_id` BIGINT NULL,
    `group_name` VARCHAR(255) NOT NULL DEFAULT '',
    `provider` VARCHAR(64) NOT NULL DEFAULT '',
    `endpoint` VARCHAR(128) NOT NULL DEFAULT '',
    `protocol` VARCHAR(64) NOT NULL DEFAULT '',
    `model` VARCHAR(255) NOT NULL DEFAULT '',
    `prompt_hash` VARCHAR(64) NOT NULL DEFAULT '',
    `redacted_preview` LONGTEXT NOT NULL,
    `prompt_length` INT NOT NULL DEFAULT 0,
    `message_count` INT NOT NULL DEFAULT 0,
    `stage` VARCHAR(32) NOT NULL DEFAULT 'http',
    `execution_mode` VARCHAR(32) NOT NULL DEFAULT 'async_audit',
    `config_version` BIGINT NOT NULL DEFAULT 1,
    `status` VARCHAR(32) NOT NULL DEFAULT 'staging',
    `attempts` INT NOT NULL DEFAULT 0,
    `max_attempts` INT NOT NULL DEFAULT 3,
    `claim_version` BIGINT NOT NULL DEFAULT 0,
    `next_attempt_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `processing_started_at` DATETIME(6) NULL,
    `processed_at` DATETIME(6) NULL,
    `last_error_code` VARCHAR(64) NOT NULL DEFAULT '',
    `last_error_message` VARCHAR(512) NOT NULL DEFAULT '',
    `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_prompt_audit_jobs_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
    CONSTRAINT `fk_prompt_audit_jobs_api_key` FOREIGN KEY (`api_key_id`) REFERENCES `api_keys` (`id`) ON DELETE SET NULL,
    CONSTRAINT `fk_prompt_audit_jobs_group` FOREIGN KEY (`group_id`) REFERENCES `groups` (`id`) ON DELETE SET NULL,
    CONSTRAINT `chk_prompt_audit_jobs_status` CHECK (`status` IN ('staging', 'queued', 'processing', 'retry', 'done', 'failed')),
    CONSTRAINT `chk_prompt_audit_jobs_execution_mode` CHECK (`execution_mode` IN ('async_audit', 'blocking')),
    CONSTRAINT `chk_prompt_audit_jobs_nonnegative` CHECK (`attempts` >= 0 AND `max_attempts` >= 0 AND `claim_version` >= 0 AND `prompt_length` >= 0 AND `message_count` >= 0 AND `config_version` >= 1),
    KEY `idx_prompt_audit_jobs_schedule` (`status`, `next_attempt_at`, `id`),
    KEY `idx_prompt_audit_jobs_request` (`request_id`),
    KEY `idx_prompt_audit_jobs_user_created` (`user_id`, `created_at` DESC),
    KEY `idx_prompt_audit_jobs_api_key_created` (`api_key_id`, `created_at` DESC),
    KEY `idx_prompt_audit_jobs_group_created` (`group_id`, `created_at` DESC),
    KEY `idx_prompt_audit_jobs_prompt_hash` (`prompt_hash`),
    KEY `idx_prompt_audit_jobs_created` (`created_at` DESC, `id` DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `prompt_audit_events` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `job_id` BIGINT NOT NULL,
    `request_id` VARCHAR(128) NOT NULL DEFAULT '',
    `user_id` BIGINT NULL,
    `username_snapshot` VARCHAR(255) NOT NULL DEFAULT '',
    `user_email_snapshot` VARCHAR(320) NOT NULL DEFAULT '',
    `api_key_id` BIGINT NULL,
    `api_key_name_snapshot` VARCHAR(255) NOT NULL DEFAULT '',
    `group_id` BIGINT NULL,
    `group_name` VARCHAR(255) NOT NULL DEFAULT '',
    `provider` VARCHAR(64) NOT NULL DEFAULT '',
    `endpoint` VARCHAR(128) NOT NULL DEFAULT '',
    `protocol` VARCHAR(64) NOT NULL DEFAULT '',
    `model` VARCHAR(255) NOT NULL DEFAULT '',
    `prompt_hash` VARCHAR(64) NOT NULL DEFAULT '',
    `redacted_preview` LONGTEXT NOT NULL,
    `stage` VARCHAR(32) NOT NULL DEFAULT 'http',
    `decision` VARCHAR(32) NOT NULL DEFAULT 'pass',
    `risk_level` VARCHAR(32) NOT NULL DEFAULT 'low',
    `action` VARCHAR(32) NOT NULL DEFAULT 'Allow',
    `categories` JSON NOT NULL DEFAULT (JSON_ARRAY()),
    `matched_scanners` JSON NOT NULL DEFAULT (JSON_ARRAY()),
    `scanner_scores` JSON NOT NULL DEFAULT (JSON_OBJECT()),
    `scanner_evidence` JSON NOT NULL DEFAULT (JSON_OBJECT()),
    `scanner_backend` VARCHAR(64) NOT NULL DEFAULT 'qwen3guard-openai',
    `scanner_version` VARCHAR(128) NOT NULL DEFAULT '',
    `guard_endpoint_id` VARCHAR(128) NOT NULL DEFAULT '',
    `policy_id` VARCHAR(128) NOT NULL DEFAULT '',
    `policy_version` INT NOT NULL DEFAULT 0,
    `config_version` BIGINT NOT NULL DEFAULT 1,
    `chunk_total` INT NOT NULL DEFAULT 0,
    `latency_ms` INT NOT NULL DEFAULT 0,
    `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_prompt_audit_events_job` FOREIGN KEY (`job_id`) REFERENCES `prompt_audit_jobs` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_prompt_audit_events_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
    CONSTRAINT `fk_prompt_audit_events_api_key` FOREIGN KEY (`api_key_id`) REFERENCES `api_keys` (`id`) ON DELETE SET NULL,
    CONSTRAINT `fk_prompt_audit_events_group` FOREIGN KEY (`group_id`) REFERENCES `groups` (`id`) ON DELETE SET NULL,
    CONSTRAINT `chk_prompt_audit_events_decision` CHECK (`decision` IN ('pass', 'flag', 'critical')),
    CONSTRAINT `chk_prompt_audit_events_risk_level` CHECK (`risk_level` IN ('low', 'medium', 'high', 'critical')),
    CONSTRAINT `chk_prompt_audit_events_action` CHECK (`action` IN ('Allow', 'Warn', 'Block')),
    CONSTRAINT `chk_prompt_audit_events_nonnegative` CHECK (`policy_version` >= 0 AND `config_version` >= 1 AND `chunk_total` >= 0 AND `latency_ms` >= 0),
    CONSTRAINT `chk_prompt_audit_events_categories_json` CHECK (JSON_TYPE(`categories`) = 'ARRAY'),
    CONSTRAINT `chk_prompt_audit_events_scanners_json` CHECK (JSON_TYPE(`matched_scanners`) = 'ARRAY'),
    CONSTRAINT `chk_prompt_audit_events_scores_json` CHECK (JSON_TYPE(`scanner_scores`) = 'OBJECT'),
    CONSTRAINT `chk_prompt_audit_events_evidence_json` CHECK (JSON_TYPE(`scanner_evidence`) = 'OBJECT'),
    KEY `idx_prompt_audit_events_job` (`job_id`),
    KEY `idx_prompt_audit_events_request` (`request_id`),
    KEY `idx_prompt_audit_events_decision_created` (`decision`, `created_at` DESC, `id` DESC),
    KEY `idx_prompt_audit_events_risk_created` (`risk_level`, `created_at` DESC, `id` DESC),
    KEY `idx_prompt_audit_events_user_created` (`user_id`, `created_at` DESC, `id` DESC),
    KEY `idx_prompt_audit_events_api_key_created` (`api_key_id`, `created_at` DESC, `id` DESC),
    KEY `idx_prompt_audit_events_group_created` (`group_id`, `created_at` DESC, `id` DESC),
    KEY `idx_prompt_audit_events_prompt_hash` (`prompt_hash`),
    KEY `idx_prompt_audit_events_created` (`created_at` DESC, `id` DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
