CREATE TABLE IF NOT EXISTS `ops_ingress_reject_aggregates` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `bucket_start` DATETIME(6) NOT NULL,
    `reject_reason` VARCHAR(64) NOT NULL,
    `route_family` VARCHAR(64) NOT NULL,
    `protocol` VARCHAR(32) NOT NULL,
    `client_ip` VARCHAR(45) NOT NULL,
    `user_id` BIGINT NOT NULL DEFAULT 0,
    `api_key_id` BIGINT NOT NULL DEFAULT 0,
    `request_count` BIGINT NOT NULL DEFAULT 0,
    `first_seen` DATETIME(6) NOT NULL,
    `last_seen` DATETIME(6) NOT NULL,
    `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`id`),
    UNIQUE KEY `ops_ingress_reject_aggregates_dimensions_unique` (`bucket_start`, `reject_reason`, `route_family`, `protocol`, `client_ip`, `user_id`, `api_key_id`),
    KEY `idx_ops_ingress_reject_aggregates_bucket` (`bucket_start` DESC),
    KEY `idx_ops_ingress_reject_aggregates_reason_bucket` (`reject_reason`, `bucket_start` DESC),
    KEY `idx_ops_ingress_reject_aggregates_ip_bucket` (`client_ip`, `bucket_start` DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
