CREATE TABLE IF NOT EXISTS `composite_model_routes` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `group_id` BIGINT NOT NULL,
    `public_model` VARCHAR(200) NOT NULL,
    `match_type` VARCHAR(20) NOT NULL DEFAULT 'exact',
    `target_platform` VARCHAR(50) NOT NULL,
    `upstream_model` VARCHAR(200) NOT NULL DEFAULT '',
    `endpoint` VARCHAR(50) NOT NULL DEFAULT 'any',
    `priority` INT NOT NULL DEFAULT 100,
    `enabled` BOOLEAN NOT NULL DEFAULT TRUE,
    `notes` LONGTEXT NULL,
    `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `deleted_at` DATETIME(6) NULL,
    `active_marker` TINYINT GENERATED ALWAYS AS (CASE WHEN `deleted_at` IS NULL THEN 1 ELSE NULL END) STORED,
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_composite_model_routes_unique_active` (`group_id`, `endpoint`, `match_type`, `public_model`, `active_marker`),
    KEY `idx_composite_model_routes_group_enabled` (`group_id`, `enabled`, `deleted_at`),
    KEY `idx_composite_model_routes_group_priority` (`group_id`, `priority`, `id`, `deleted_at`),
    CONSTRAINT `chk_composite_model_routes_match_type` CHECK (`match_type` IN ('exact', 'prefix')),
    CONSTRAINT `chk_composite_model_routes_endpoint` CHECK (`endpoint` IN ('any', 'messages', 'count_tokens', 'responses', 'chat_completions', 'embeddings', 'images', 'gemini')),
    CONSTRAINT `chk_composite_model_routes_target_platform` CHECK (`target_platform` IN ('anthropic', 'openai', 'gemini', 'antigravity', 'grok')),
    CONSTRAINT `fk_composite_model_routes_group` FOREIGN KEY (`group_id`) REFERENCES `groups` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
