CREATE TABLE IF NOT EXISTS `sub2api_plugin_installations` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `plugin_key` VARCHAR(160) NOT NULL,
    `name` VARCHAR(160) NOT NULL,
    `version` VARCHAR(64) NOT NULL,
    `description` TEXT NOT NULL,
    `author` VARCHAR(160) NOT NULL,
    `manifest` JSON NOT NULL,
    `artifact_path` TEXT NOT NULL,
    `install_path` TEXT NOT NULL,
    `binary_path` TEXT NOT NULL,
    `binary_sha256` VARCHAR(64) NOT NULL,
    `signature_status` VARCHAR(32) NOT NULL DEFAULT 'unsigned',
    `state` VARCHAR(32) NOT NULL DEFAULT 'disabled',
    `config_encrypted` LONGTEXT NOT NULL,
    `last_error` TEXT NOT NULL,
    `installed_by` BIGINT NULL,
    `artifact_data` LONGBLOB NULL,
    `installed_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `enabled_at` DATETIME(6) NULL,
    `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`id`),
    UNIQUE KEY `sub2api_plugin_installations_plugin_key_uq` (`plugin_key`),
    KEY `sub2api_plugin_installations_state_idx` (`state`),
    CONSTRAINT `sub2api_plugin_installations_user_fk` FOREIGN KEY (`installed_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
    CONSTRAINT `sub2api_plugin_installations_state_check` CHECK (`state` IN ('disabled','starting','enabled','error','incompatible')),
    CONSTRAINT `sub2api_plugin_installations_signature_check` CHECK (`signature_status` IN ('trusted','unsigned'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `sub2api_plugin_bindings` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `plugin_id` BIGINT NOT NULL,
    `capability` VARCHAR(160) NOT NULL,
    `platform` VARCHAR(32) NOT NULL,
    `account_type` VARCHAR(32) NOT NULL,
    `enabled` BOOLEAN NOT NULL DEFAULT FALSE,
    `rollout_percent` INT NOT NULL DEFAULT 100,
    `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`id`),
    UNIQUE KEY `sub2api_plugin_bindings_scope_uq` (`plugin_id`,`capability`,`platform`,`account_type`),
    KEY `sub2api_plugin_bindings_enabled_scope_idx` (`platform`,`account_type`,`capability`,`enabled`),
    CONSTRAINT `sub2api_plugin_bindings_plugin_fk` FOREIGN KEY (`plugin_id`) REFERENCES `sub2api_plugin_installations` (`id`) ON DELETE CASCADE,
    CONSTRAINT `sub2api_plugin_bindings_rollout_check` CHECK (`rollout_percent` BETWEEN 0 AND 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
